---
author: "Mohammed Saqr & Sonsoles López-Pernas"
toc: false
margin-footer: |
    <span></span>
include-after-body:
  text: |
    <script>
      document.querySelector(".quarto-title-meta-heading").innerHTML = "Editors"
    </script>
---
#    {.unnumbered}

This is the website for the book **“Learning analytics methods and tutorials: A practical guide using R”** which will be published by Springer in 2024. 

Learning analytics is a fast-paced discipline at the cross-section of cutting-edge methodological advances and theoretical innovations. Most of the methods have been born long before the field of learning analytics and continue to be developed and advanced across diverse fields. Therefore, researchers and students have to navigate through fragmented literature from several fields and learn to apply such methods. Notwithstanding the difficulties of identifying which literature or guides one can use, several methodological questions remain unanswered in these books. This is of course because such literature was prepared for other disciplines and offers case studies that are oftentimes not relevant. 
Being learning analytics researchers ourselves, we have been through these difficulties. Learning a new methodology took several trials and searching for answers that were rather hard to get. Collaboration with other researchers from learning analytics and other fields —e.g., statistics and methodology— has helped us navigate these difficulties. In many situations, we would contact statisticians, or package developers to help with solving an issue or collaborate on a paper. With the publication of our papers, we got several emails from researchers asking about technical details. It has become clear to us that there is a need for a well-documented resource for learning analytics methods. In fact, this is how we —the editors of this book— met. Sonsoles was doing mobility in Sweden, where Mohammed was working, and she wanted to do a learning analytics study for a dataset she collected from a programming course. Lacking any resource that could help her kickstart her exploration of the emerging field, she sought collaboration. Ever since, we had an interesting journey of working together on so many projects.
The lack of resources and methodological guidance was a problem then, and continues to be a problem today. We thought that the arduous journey in learning analytics should not be endured by everyone and we decided to make that resource with the help of the community as well as our collaborators. More than a year of intensive work is within your hands now. We hope that we have contributed to LA by providing an informative resource that students, researchers, and practitioners can use. 
In this book, we tried to include all the basics of R as a programming language as well as the basics of data cleaning, statistics, and data manipulation. In doing so, we wanted the newcomers to find an easy entry to the field. We also tried to be as comprehensive as we could and included almost all major methodologies. For every method, we started with the basics, explaining the main concepts, the essential techniques, and basic functions. In subsequent chapters, we went deeper into advanced methods that are at the forefront of novel methodological innovations. We also used real-life learning analytics data and made it readily available to researchers. To do so, we collaborated with world-renowned researchers, package developers, and methodological experts from other fields to offer an unprecedented resource on novel topics that are hard to find any resource for. 
We hope the readers find this book useful as a guiding light through the intricate pathways of learning analytics methods, illuminating the ways in which data-driven insights can elevate educational experiences and benefit educators, learners, and researchers alike.

The editors

[Mohammed](https://saqr.me) and [Sonsoles](https://sonsoles.me)
