---
title: "Capturing the Wealth and Diversity of Learning Processes with Learning Analytics Methods"
format: 
  pdf:
    number-sections: true
    documentclass: article
    papersize: a4
    template-partials:
      - ../../title.tex
    geometry:
      - top=25.4mm
      - bottom=25.4mm
      - right=25.4mm
      - left=25.4mm
    include-in-header:
      text: |
        \usepackage{fontawesome}
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}
        \usepackage{float}
        \floatplacement{table}{H}
        \floatplacement{figure}{H}

execute:
  message: FALSE
  warning: FALSE
author: 
   - name: "Sonsoles López-Pernas"
     email: "sonsoles.lopez@uef.fi"
     affil-id: 1,*
   - name: "Kamila Misiejuk"
     email: "kamila.misiejuk@uib.no"
     affil-id: 2
   - name: "Rogers Kaliisa"
     email: "rogers.kaliisa@iped.uio.no"
     affil-id: 3     
   - name: "Miguel Á. Conde-González"
     email: "mcong@unileon.es"
     affil-id: 4
   - name: "Mohammed Saqr"
     email: "mohammed.saqr@uef.fi"
     affil-id: 1
affiliations:
  - id: 1
    name: "School of Computing, University of Eastern Finland"
  - id: 2
    name: "Centre for the Science of Learning & Technology (SLATE), University of Bergen"
  - id: 3
    name: "Department of Education, University of Oslo, Oslo, Norway"
  - id: 4
    name: "Robotics Research Group, Engineering School, University of León"
  - id: "*"
    name: "Corresponding author: Sonsoles López-Pernas, `sonsoles.lopez@uef.fi`"
crossref:
  fig-title: '**Figure**'
  fig-labels: arabic
  title-delim: "**.**"
abstract-title: "Abstract"
abstract: "The unique position of learning analytics at the intersection of education and computer science while reaching out to several other disciplines such as statistics, psychometrics, econometrics, mathematics, and linguistics has accelerated the growth and expansion of the field. Therefore, it is a crucial endeavor for learning analytics researchers to stay abreast of the latest methodological and computational advances to drive their research forward. The diversity and complexity of the existing methods can make this task overwhelming both for newcomers to the learning analytics field and for experienced researchers. With the motivation to accompany researchers in this challenging journey, the book \"Learning Analytics Methods and Tutorials - A Practical Guide Using R\"  aims to provide a methodological guide for researchers to study, consult, and embark upon the first steps toward innovation in the learning analytics field. Thanks to the unique wealth of authors’ backgrounds and expertise, which include authors of R packages and experts in methods and applications, the book offers a comprehensive array of methods that are described thoroughly with a primer on their usage in prior research in education. These methods include sequence analysis, Markov models, factor analysis, process mining, network analysis, predictive modeling, and cluster analysis among others. A step-by-step tutorial using the R programming language with real-life datasets and case studies is presented for each method. In addition, the initial chapters are devoted to getting novice researchers up to speed with the R programming learners and the basics of data analysis. The present chapter serves as an introduction to the book describing its main aim and intended audience. It describes the structure of the book and the methods covered by each chapter. It also points the readers to the companion code and data repositories to facilitate following the tutorials present in the book chapter."
keywords: "learning analytics, educational data mining, tutorial, methods, learning analytics, curriculum"
fontsize: "9pt"
dpi: 900
editor: source
keep-tex: true
bibliography: references.bib
csl: "../../springer.cls"
pdf-engine: pdflatex
extract-media: "img"
---

**Keywords:** {{< meta keywords >}}

# Introduction

The official birth of the field of learning analytics is often ascribed to the first Learning Analytics & Knowledge Conference in 2011, where the widely used definition was coined as “the measurement, collection, analysis, and reporting of data about learners and their contexts, for purposes of understanding and optimizing learning and the environments in which it occurs” [@Conole_Gašević_Long_Siemens_2011]. Over the years, learning analytics has grown in scope, scale, and diversity and has since attracted researchers from diverse backgrounds bringing several disciplines together under one umbrella. Such increasing interest has resulted in a large number of publications, research projects, specialized units, and funding of large projects. Although other data-intensive fields started before learning analytics (e.g., academic analytics in 2007 and educational data mining in 2008), interest in such methods —and in closely related fields at large— has surged only after the rapid adoption of learning analytics. 
The unique position of learning analytics at the intersection of education and computer science while reaching out to several other disciplines such as statistics, psychometrics, econometrics, mathematics, and linguistics has accelerated the growth and expansion of the field. Therefore, it is a crucial endeavor for learning analytics researchers to stay abreast of the latest methodological and computational advances to drive their research forward. The diversity and complexity of the existing methods can make this task overwhelming both for newcomers to the learning analytics field and for experienced researchers. When conducting learning analytics research, researchers need to decide which data can and must be collected from learners to give answers to their research questions. They need to understand and decide which analytical methods may apply to such data and their potential limitations. They also need to interpret the findings and contextualize them in light of the existing literature and learning theories. With the motivation to accompany researchers in this challenging journey, this book aims to provide a methodological guide for researchers to study, consult, and embark upon the first steps toward innovation. 

Every method described in this book was developed before learning analytics, for instance, predicting students’ performance can be traced back to almost a century ago [@Cornog_Stoddard_1925], and using social network analysis to understand students’ networks dates back to over five decades ago [@Platts_Wyant_1969]. Similarly, process mining, sequence analysis, and Markov models can all be traced to times before the birth of the field of learning analytics (e.g., [@Pechenizkiy_Trcka_Vasilyeva_Van_der_Aalst_De_Bra_2009;@Soller_Lesgold_2003;@Wang_2002]). Not only were these methods born outside learning analytics, but they also continue to be developed, refined and advanced in their relevant fields. Nevertheless, learning analytics has succeeded in taking advantage of these methodological developments as well as the increasingly available digital data, computational resources, and data science, and in popularizing data-intensive research in education to bring this field together [@Adam_Bakar_Fakhreldin_Majid_2018]. 

The diversity of methods and fields that have given rise to the field of analytics is evident in the list of authors of the chapters of this book, which include authors of R packages, and experts in methods and applications to drive a state-of-the-art blend. In the first category, we have the world renowned sequence analysis experts Gilbert Ritschard and Matthias Studer (University of Geneva), who are the creators of `TraMineR`, which is the most central R package for sequence analysis. Closely related, we have Satu and Jouni Helske (University of Turku), developers of `seqHMM`, an innovative R package for Mixture Hidden Markov Models of sequential data with tons of visualizations and statistical analysis potentials. Also, our list of authors includes Luca Scrucca (University of Perugia), author of `mclust`, one of the most widely used clustering packages for classification, and density estimation using Gaussian finite mixture models, and Keefe Murphy (Maynooth University), creator of several R packages such as `MoEClust` for Gaussian parsimonious clustering models with covariates. Our list of authors also includes David Williamson Shaffer (University of Wisconsin-Madison), the creator of `rENA` (an R package for Epistemic Network Analysis) along with other members of the `rENA` and the Ordered Network Analysis groups: Yuanru Tan and Andrew Ruis (University of Wisconsin-Madison), and Zachari Swiecki (Monash University). We also have Leonie V.D.E. Vogelsmeier (Tilburg University), author of `lmfa`, an innovative  R package for latent Markov factor analysis which offers transition, and mixture factor analysis. We also have Santtu Tikka (University of Jyväskylä), author of the `dynamite` R package for dynamic multivariate panel models. In addition, among our authors, we have prominent methodology experts in several domains: Joran Jongerling (Tilburg University); Emorie Beck (UC Davis); Merja Heinäniemi and Juho Kopra (University of Eastern Finland), and Marieke Schreuder (KU Leuven). Lastly, we count on several senior and emerging learning analytics researchers: Jelena Jovanović (University of Belgrade); Ángel Hernández-García, Javier Conde, Laura Del-Río-Carazo, and Carlos Cuenca-Enrique (Universidad Politécnica de Madrid); Adrienne Traxler (University of Copenhagen); Kamila Misiejuk (University of Bergen); Miguel Ángel Conde (University of Leon), and Marion Durand (University of Eastern Finland). Besides, the editors (Mohammed Saqr and Sonsoles López-Pernas) from the University of Eastern Finland have a long history of learning analytics research working with diverse methods and interdisciplinary research that spans most learning analytics methods. 

Thanks to the breadth and diversity of authors' backgrounds and expertise, the book offers a comprehensive array of methods that are described thoroughly. A step-by-step tutorial using the R programming language with real-life datasets and case studies is presented for each method. The book starts with an introductory section for readers to get up-to-speed with R programming, in which we cover the basics of the language, data preprocessing, basic statistics, and data visualization. Then, we delve into classic machine learning methods, such as prediction and clustering applied to educational data. These methods enable readers to predict achievement, dropout, and students at risk, as well as to group students into different groups or profiles according to certain characteristics such as motivation or engagement. This is followed by an extensive section devoted to temporal methods such as sequence analysis, Markovian modeling, and process mining, which allow taking advantage of the endless possibilities of trace log data. The book then moves on to discuss network analysis in its many forms including social network analysis, epistemic network analysis, ordered network analysis, and temporal networks. Such methods are crucial for understanding collaboration and relationships between individuals and concepts, which are key aspects of learning. The book concludes with a section on psychometrics such as psychological networks, factor analysis, and structural equation modeling, which are fundamental tools for the analysis of self-reported data among others. We hope the readers find this book useful as a guide through learning analytics methods, higlighting the ways in which data-driven insights can benefit educators, learners, and researchers alike. 

The book targets learning analytics researchers (and education researchers at large) at all stages. It is suitable to teach newcomers to the field, even with no experience in R, since the introductory chapters are aimed at getting readers acquainted with the basics of R programming and data analysis. The book also covers advanced methods that may be of interest to experts in the field of learning analytics or data science in general. Moreover, the skills taught are transferable to other fields, i.e., can be applied in other contexts outside education.

We hope the readers find this book useful as a guide through learning analytics methods, higlighting the ways in which data-driven insights can benefit educators, learners, and researchers.




# How the book is structured

## Introductory chapters

The first section of the book provides the basis for getting up to speed with the R programming language and the data that will be analyzed throughout the book. This section covers the fundamental steps of the data analysis process, such as data preprocessing and exploratory analysis. During data preprocessing, educational data is cleaned and prepared for further analysis. Many crucial decisions about building and conceptualizing learning indicators from raw data are made in this essential step of the learning analytics process. Exploratory analysis enables an early detection of interesting phenomena that can be discovered in the data using visualizations or simple statistics. Using these techniques helps to guide the direction of the in-depth analysis and the selection of more advanced analytical methods. 

**Chapter 2: A Broad Collection of Datasets for Educational Research Training and Application** [@López-Pernas_Saqr_Conde_Del-Río-Carazo_2024]

*Sonsoles López-Pernas, Mohammed Saqr, Javier Conde, Laura Del-Río-Carazo*

Since the goal of this book is to provide a guide and tutorial on how to implement learning analytics methods, the use of relevant data is a key aspect of the contextualization of these methods within learning analytics research. Chapter 2 kicks off the book with an introduction to the most relevant types of data in learning analytics and provides a diverse collection of curated datasets that we will use throughout the book to illustrate the different methods. Understanding the data under examination is a crucial step for the interpretability of the analyses that we will learn to perform in this book, and therefore, readers should familiarize themselves with the datasets described in this chapter to facilitate following the tutorials presented in subsequent ones.

**Chapter 3: Getting started with R for Education Research** [@Tikka_Kopra_Heinäniemi_López-Pernas_Saqr_2024a]

*Santtu Tikka, Juho Kopra, Merja Heinäniemi, Sonsoles López-Pernas, Mohammed Saqr*

The first tutorial-like chapter of the book provides an introduction to the basics of R programming, with a focus on the Rstudio integrated development environment and the `tidyverse` programming paradigm. The R programming language has become a popular tool for conducting data analysis in the field of learning analytics. The chapter covers topics such as data types and structures, control structures, pipes, functions, loops, and input/output operations. By the end of the chapter, readers should have a solid understanding of the basics of R programming and have the necessary tools to learn more in-depth topics such as data wrangling and basic statistics using R.

**Chapter 4: An R Approach to Data Cleaning and Wrangling for Education** [@Kopra_Tikka_Heinäniemi_López-Pernas_Saqr_2024]

*Juho Kopra, Santtu Tikka, Merja Heinäniemi, Sonsoles López-Pernas, Mohammed Saqr*

After learning the basics of the R programming language, Chapter 4 goes one step further by introducing the reader to data wrangling, also known as data cleaning and preprocessing. Data wrangling is a critical step in the data analysis process, particularly in the context of learning analytics. This chapter provides an introduction to data wrangling using R and covers topics such as data importing, cleaning, manipulation, and reshaping with a focus on tidy data. Specifically, readers will learn how to read data from different file formats (e.g., CSV, Excel), how to manipulate data using the `dplyr` package, and how to reshape data using the `tidyr` package. Additionally, the chapter covers techniques for combining multiple data sources.


**Chapter 5: Introductory Statistics with R for Educational Researchers** [@Tikka_Kopra_Heinäniemi_López-Pernas_Saqr_2024b]

*Santtu Tikka, Juho Kopra, Merja Heinäniemi, Sonsoles López-Pernas, Mohammed Saqr*

Statistics play a fundamental role in learning analytics, providing a means to analyze and make sense of the vast amounts of data generated by learning environments, visualize relationships, test hypotheses, and make comparisons. Chapter 5 in this book provides an introduction to basic statistical concepts using R and covers topics such as measures of central tendency, variability, correlation, and regression analysis. Specifically, readers will learn how to compute descriptive statistics, test hypotheses, and perform simple linear regression analysis. The chapter also includes practical examples using realistic data sets from the field of learning analytics. By the end of the chapter, readers should have a solid understanding of the basic statistical concepts and methods commonly used in learning analytics, as well as a practical understanding of how to use R to conduct statistical analysis of learning data.


**Chapter 6: Visualizing and Reporting Educational Data with R**  [@López-Pernas_Misiejuk_Tikka_Saqr_Kopra_Heinäniemi_2024]

*Sonsoles López-Pernas, Kamila Misiejuk, Santtu Tikka, Mohammed Saqr, Juho Kopra, Merja Heinäniemi*

Visualizing data is central in learning analytics research, underpins learning dashboards, and is a prime method for reporting results and insights to stakeholders. Chapter 6 guides the reader through the process of generating meaningful and aesthetically pleasing visualizations of different types of datasets using well-known R packages. The main visualization types will be demonstrated with an explanation of their usage and use cases. Furthermore, learning-related examples will be discussed in detail. For instance, readers will learn how to visualize learners' logs extracted from learning management systems to show how trace data can be used to track students’ learning activities. Readers will also be able to generate professional-looking tables with summary statistics.

## Machine learning methods

The next section follows with some of the classic machine learning methods of learning analytics, which date to the early beginnings of the field: predictive modelling and cluster analysis. Predictive modelling is a supervised learning method used widely in learning analytics research, where past data patterns are analysed to predict students' future outcomes. Clustering is an unsupervised learning method that detects similar patterns in the data and is typically used to group students based on their personal characteristics, observed behavior, or learning outcomes. Both methods are applied to address various challenges in education, such as preventing student drop-out, comparing strategies to improve academic performance, or identifying disengaged students. In addition, the results are often used to trigger specific interventions to help students succeed or to raise awareness about students' performance based on specific indicators.

**Chapter 7: Predictive Modelling in Learning Analytics using R**  [@Jovanovic_López-Pernas_Saqr_2024]

*Jelena Jovanovic, Sonsoles López Pernas, Mohamed Saqr*

Prediction of learners’ course performance has been a central theme in learning analytics since the inception of the field. The main motivation behind it has been to identify learners who are at risk of low achievement so that they could be offered timely support based on intervention strategies derived from analysis of learners’ data. To predict student success, numerous indicators, from varying data sources, have been examined and reported in the literature, as well as various predictive algorithms. Chapter 7 introduces the reader to predictive modeling, through a review of the main objectives, indicators, and algorithms that have been operationalized in previous works as well as a step-by-step tutorial on how to perform predictive modeling in learning analytics using R. The tutorial demonstrates how to predict student success using learning traces originating from a learning management system, guiding the reader through all the required steps from the data preparation to the evaluation of the built models.

**Chapter 8: Dissimilarity-based Clustering Educational Data using R** [@Murphy_López-Pernas_Saqr_2024]

*Keefe Murphy, Sonsoles López-Pernas, Mohammed Saqr*

Chapter 8 presents another central method in learning analytics research: clustering. Clustering is a collective term that refers to techniques aimed at uncovering patterns and subgroups within the data. Finding patterns or differences among students enables teachers and researchers to improve their understanding of the diversity of students ---and their learning processes--- and tailor their support to different needs. This chapter introduces the theory underpinning the dissimilarity-based clustering methods. Then, we focus on some of the most widely-used heuristic dissimilarity-based clustering algorithms; namely, $K$-means, $K$-medoids, and agglomerative hierarchical clustering. Methods for choosing the optimal number of clusters are provided, particularly the criteria that can guide the choice of clustering solution among multiple competing methodologies, and not only the choice of the number of clusters $K$ for a given method. All of these are demonstrated in detail with a tutorial in R using a real-life educational dataset.


**Chapter 9: An Introduction and R Tutorial to Model-based Clustering in Education via Latent Profile Analysis**  [@Scrucca_Saqr_López-Pernas_Murphy_2024]

*Luca Scrucca, Mohammed Saqr, Sonsoles López-Pernas, Keefe Murphy*

Chapter 9 presents an alternative approach for capturing different patterns or subgroups within students' behavior or functioning. Assuming that there is an average pattern that represents the entirety of student populations requires the measured construct to have the same causal mechanism, the same development pattern, and affect students in exactly the same way. Using a person-centered method (Finite Gaussian mixture model or latent profile analysis), this chapter offers an introduction to model-based clustering that includes the principles of the methods, a guide to the choice of number of clusters, an evaluation of clustering results and a detailed guide with code and a real-life dataset. The tutorial part shows how to uncover the heterogeneity within engagement data by identifying latent or unobserved clusters. The discussion elaborates on the interpretation of the results, the advantages of model-based clustering as well as how this method compares with others.

## Temporal methods

We continue our journey with an introduction to temporal methods in learning analytics. Unlike the methods based on mere counts of events or activities, temporal methods acknowledge the order and temporality of events, as well as the transitions thereof, which are key aspects of learning. Temporal methods have garnered increasing attention since they allow researchers to take advantage of the trace log data that students leave behind when using educational technology and also to study longitudinal processes (e.g., a whole study program). Such methods originate in social sciences and have been imported and adapted into the learning analytics field. We provide three chapters focused on sequence analysis, and two on transition analysis through Markovian modeling and process mining.

**Chapter 10: Sequence Analysis in Education: Principles, Technique, and Tutorial with R** [@Saqr_López-Pernas_Helske_Durand_Murphy_Studer_Ritschard_2024]

*Mohammed Saqr, Sonsoles López-Pernas, Satu Helske, Marion Durand, Keefe Murphy, Matthias Studer, Gilbert Ritschard*

Sequence analysis is a data mining technique that is increasingly gaining ground in learning analytics. Sequence analysis enables researchers to extract meaningful insights from sequential data, i.e., to summarize the sequential patterns of learning data and classify those patterns into homogeneous groups. Chapter 10 introduces readers to sequence analysis techniques and tools through real-life step-by-step examples of sequential trace log data of students’ online activities. Readers are guided on how to visualize the common sequence plots and interpret such visualizations. An essential part of sequence analysis is the discovery of patterns within sequences through clustering techniques. Therefore, this chapter demonstrates the various sequence clustering methods, calculation of cluster indices, and evaluation of clustering results.

**Chapter 11: Modeling the Dynamics of Longitudinal Processes in Education. A tutorial with R for The VaSSTra Method**  [@López-Pernas_Saqr_2024]

*Sonsoles López-Pernas, Mohammed Saqr*

Building upon the knowledge acquired in the previous chapter, Chapter 11 covers VaSSTra, a method for analyzing multiple variables across multiple time points. The idea behind this method is to summarize multiple variables at each time point into a single state using person-based methods. Then, sequence analysis can be used to analyze the sequences of such states for each person, and clustering techniques can be implemented to detect similar trajectories of the evolution of such states. The method is illustrated in a case study about engagement. Several engagement-related variables are derived from students’ online activities (frequency of each activity, regularity, etc.). These variables are used for clustering students into three states (active, moderate, and disengaged) at each course. Then, sequence analysis is used to map the sequence of engagement states across a whole program. Lastly, clustering mechanisms are used to detect distinct trajectories of engagement.

**Chapter 12: A Modern Approach to Transition Analysis and Process Mining with Markov Models in Education** [@Helske_Helske_Saqr_López-Pernas_Murphy_2024]

*Jouni Helske, Satu Helske, Mohammed Saqr, Sonsoles López-Pernas, Keefe Murphy*

Chapter 13 presents Markov models, a widely used technique to model temporal processes. Contrary to the deterministic approach seen in the previous sequence analysis chapters, Markovian models are probabilistic models, focusing on the transitions between states instead of studying sequences as a whole. The chapter provides an introduction to Markov models and differentiates between its most common variations: first-order Markov models, hidden Markov models, mixture Markov models, and hidden mixture Markov models. All implementations are illustrated with a step-by-step tutorial using the R package seqHMM using students’ longitudinal data. The chapter also provides a complete guide to performing stochastic process mining with Markovian models as well as plotting, comparing, and clustering different process models

**Chapter 13: Multichannel Sequence Analysis in Educational Research Using R** [@López-Pernas_Saqr_Helske_Murphy_2024]

*Sonsoles López-Pernas, Satu Helske, Mohammed Saqr, Keefe Murphy*

When dealing with learners’ data, sometimes one single source of information is not enough to capture all of the dimensions of the learning process. Fortunately, sequence analysis as a method supports the examination of multiple sequences (termed channels) at the same time as long as they follow the same time scheme. Chapter 13 covers multi-channel sequence analysis, allowing the reader to study and visualize synchronized sequences together, and cluster them into distinct trajectories based on the values of the various channels. We present two methods for clustering: one distance-based (see Chapter 10) and one based on Markovian models (see Chapter 12). We illustrate the method by studying the longitudinal association between student engagement and achievement across a study program.

**Chapter 14: The Why, the How, and the When of Educational Process Mining in R** [@Lopez-Pernas2024-as]

*Sonsoles López-Pernas, Mohammed Saqr*

Process mining is a recent analytical method that enables the extraction of meaningful insights from time-ordered event logs. The goal of process mining is to discover processes from the data, evaluate process efficiency, and help or enhance processes. Since its introduction in education, process mining has been used to map students' learning processes, visualize learners’ strategies, as well as demonstrate differences in approach to learning across different learning groups. Chapter 14 illustrates how to prepare learners’ data for process mining and how to visualize the process data using the `bupaverse` framework. Moreover, readers will learn how to examine the transitions between phases or activities within a learning process. 

## Network Analysis 

The next section of the book deals with the relational aspects of analyzing educational data such as relationships between students, teachers, and topics. Network analysis is the underlying method used to study such relational aspects. Social network analysis allows researchers to study collaboration and discussion between peers and understand the role each student occupies in the network. Moreover, community finding allows the detection of distinct groups of peers in the network that interact with each other more than with the rest. We can even combine network analysis with the temporal methods presented in the last section through temporal networks or use epistemic or ordered network analysis to explore topic or construct co-occurrence.

**Chapter 15: Social Network Analysis: A Primer, a Guide and a Tutorial in R**  [@Saqr_López-Pernas_Conde_Hernández-García_2024]

*Mohammed Saqr, Sonsoles López-Pernas, Miguel Ángel Conde, Ángel Hernández-García*

For five decades, learning networks have been used to map collaboration networks among students, study the influence of peers, and capture the relational dimension of collaborative learning. Additionally, networks have been used to study the semantics of discourse, relations between behaviors, and patterns of relations among teachers. Networks offer a powerful framework with vast potential for data analysis. Chapter 15 introduces the concept and methods of social network analysis and a detailed guide on how researchers can use network analysis using real-world data. The chapter demonstrates network analysis and visualisation with an emphasis on learners’ roles and relevance to the educational context. The chapter further provides a  mathematical analysis and interpretation of the different social network metrics such as centrality and betweenness measures with several examples of how they can be used in practice.  

**Chapter 16: Community Detection in Learning Networks Using R** [@Hernández-García_Cuenca-Enrique_Traxler_López-Pernas_Conde_Saqr_2024]

*Ángel Hernández-García, Carlos Cuenca-Enrique, Adrienne Traxler, Sonsoles López-Pernas, Miguel Ángel Conde, Mohammed Saqr*

In learning situations, communities can be groups of students within a whole cohort who collaborate with each to a larger extent than with other students in a learning situation. Finding these communities is integral to understanding the interaction process, the structure and behaviour of the formed groups and how they contribute to the overall learning process. Chapter 16 builds on the principles of social networks from Chapter 15 and introduces the topic of community detection. The main aim of community detection is to identify different groups or clusters of nodes within the network that share some similar characteristics. One way of understanding communities in social networks is as subnetworks where the number of internal connections is larger than the number of external connections, and therefore members of a community have a higher probability of being connected to each other than to members of other communities. The chapter focuses on detecting communities (groups of highly connected nodes) within a wider network and shows how to visualize them using R.

**Chapter 17: Temporal Network Analysis: Introduction, Methods, and Analysis with R**  [@Saqr_2024]

*Mohammed Saqr*

Learning can be viewed as relational, interdependent, and temporal and therefore, methods that account for such multifaceted dynamic processes that unfold overtime are required. Chapter 17 combines the temporal and relational aspects in a single analytics framework: temporal networks. Temporal networks allow modeling of the temporal learning processes i.e., the emergence and flow of activities, communities, and social processes through fine-grained dynamic analysis. This can provide insights into phenomena like knowledge co-construction, information flow, and relationship building. This chapter introduces the basic concepts of temporal networks, their types (i.e, contact and interval), and techniques. The chapter further provides a detailed guide to temporal network analysis, which involves network building, visualization, and statistical analysis at the graph and node level. 

**Chapter 18: Epistemic Network Analysis and Ordered Network Analysis in Learning Analytics** [@Tan_Swiecki_Ruis_Shaffer_2024]

*Yuanru Tan, Zachari Swiecki, Andrew Ruis, David Williamson Shaffer*

The increasing use of technology in many areas of society and life has led to an increasing amount of Big Data about human behavior and interaction. However, this volume of data is usually too large and strains the capabilities of human interpretation and the traditional social science research approaches. Chapter 18 presents two quantitative ethnographic approaches that links the power of statistics and in-depth ethnographic approaches to understand learning behaviour through large-scale qualitative data.  Epistemic Network Analysis (ENA) and Ordered Network Analysis (ONA), are two methods for quantifying, visualizing, and interpreting network data. Taking coded data as input, ENA and ONA represent associations between codes (e.g., topics or categories) in undirected or directed weighted network models, respectively. Both techniques measure the strength of association among codes and illustrate the structure of connections in network graphs, quantify changes in the composition and strength of those connections over time, and enable comparison of networks. The chapter presents a thorough description of the methods and a step-by-step guide on how to implement them with R.

##  Psychometrics  

We finalize the book with a section on psychometrics. In the field of educational psychology, psychometrics aims to study how psychological constructs (e.g., intelligence or aptitude) are related to observable variables (e.g., test scores). Traditionally, psychometric methods in educational psychology have relied on self-reported data from validated questionnaire-like instruments, although nowadays researchers have begun to make use of digital data. We present several techniques to investigate the relationship between measured variables and to test hypotheses and theories: psychological networks, factor analysis, and structural equation modeling (SEM).

**Chapter 19: Psychological Networks: A Modern Approach to Analysis of Learning and Complex Learning Processes** [@Saqr_Beck_López-Pernas_2024]

*Mohammed Saqr, Emorie Beck, Sonsoles López-Pernas*

When analyzing psychological phenomena that take place in educational settings, a multitude of variables are at play that may interact with, trigger, and influence each other. To understand such dependency between variables, it is not enough to analyze the linear relationships between each pair of variables, but rather such complexity calls for using more sophisticated methods that capture the full breadth of the interplay between variables: psychological networks. ​As opposed to social networks where nodes often represent people and edges represent the interactions or relations between them, the nodes in psychological networks represent observed psychological variables and edges represent a statistical relationship between them. Chapter 19 opens the section on psychometric methods by presenting the concept of psychological networks as well as a tutorial for their estimation, visualization, and interpretation with R.


**Chapter 20: Factor Analysis in Education Research using R**  [@Vogelsmeier_Saqr_López-Pernas_Jongerling_2024]

*Leonie V. D. E. Vogelsmeier, Mohammed Saqr, Sonsoles López-Pernas,  Joran Jongerling*

Chapter 20 presents factor analysis, a method employed to reduce a large number of variables into fewer numbers of factors. The method is commonly used to identify which observable indicators are representative of latent, not directly-observed constructs. This is a key step in developing valid instruments to assess latent constructs such as student engagement in educational research. The chapter describes the two main approaches for conducting factor analysis in detail and provides a tutorial on how to implement both techniques. The first is confirmatory factor analysis (CFA), a more theory-driven approach,  in which a researcher actively specifies the number of underlying constructs as well as the pattern of relations between these dimensions and observed variables. The second is exploratory factor analysis (EFA), a more data-driven approach,  in which the number of underlying constructs is inferred from the data, and all underlying constructs are assumed to influence all observed variables (at least to some degree).

**Chapter 21: Structural Equation Modeling with R for Education Scientists**  [@Jongerling_López-Pernas_Saqr_Vogelsmeier_2024]

*Joran Jongerling,  Sonsoles López-Pernas, Mohammed Saqr, Leonie V. D .E. Vogelsmeier*

Chapter 21 presents the last method in our book: Structural Equation Modeling (SEM). SEM is a suitable and useful method for modeling the multitude of relationships between latent variables and the observable indicators, as well as the relationship between the latent variables themselves to test theories. In its most common form, SEM combines CFA (covered in Chapter 20) with another method named path analysis. Just like CFA, SEM relates observed variables to latent variables that are measured by those observed variables and, as path analysis does, SEM allows for a wide range of regression-type relations between sets of variables (both latent and observed). This chapter presents an introduction to SEM, an integrated strategy for conducting SEM analysis that is well-suited for educational sciences, and a tutorial on how to carry out an SEM analysis in R. 


# The companion code and data

To enhance your learning experience and practical understanding of the concepts discussed in this book, we have developed a companion code repository that accompanies each chapter. The repository contains all the code included in the step-by-step tutorials that illustrate how to implement the different learning analytics methods covered in the book chapters. The code also contains custom functions that automate complex operations, making it easier for anyone to apply the techniques to their own datasets. Moreover, the code will guide the reader on how to generate visualizations, graphs, and plots aimed at helping to interpret and communicate findings effectively. The companion code repository can be accessed at:

\faGithub{}  [https://github.com/lamethods/code](https://github.com/lamethods/code)

Along with the code, we provide a collection of datasets carefully curated to represent educational scenarios, allowing you to experiment with the techniques discussed in the book and beyond. Each dataset is described in detail in Chapter 2.

\faGithub{}  [https://github.com/lamethods/data](https://github.com/lamethods/data)

By combining theoretical knowledge with practical application through the companion code and datasets, the reader will be well-equipped to embark on a journey into the fascinating world of learning analytics.


# References
