<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Santtu Tikka">
<meta name="author" content="Juho Kopra">
<meta name="author" content="Merja Heinäniemi">
<meta name="author" content="Sonsoles López-Pernas">
<meta name="author" content="Mohammed Saqr">
<meta name="keywords" content="statistics, learning analytics, hypothesis testing">

<title>Learning analytics methods and tutorials - 5&nbsp; Introductory Statistics with R for Educational Researchers</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/ch06-data-visualization/ch6-viz.html" rel="next">
<link href="../../chapters/ch04-data-cleaning/ch4-datacleaning.html" rel="prev">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-Y4VBV3J9WD"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-Y4VBV3J9WD', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  });
});
</script> 
  

<link href="../../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../../site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="twitter:title" content="Learning analytics methods and tutorials - 5&nbsp; Introductory Statistics with R for Educational Researchers">
<meta name="twitter:description" content="Statistics play a fundamental role in learning analytics, providing a means to analyze and make sense of the vast amounts of data generated by learning environments.">
<meta name="twitter:card" content="summary">
<meta name="citation_title" content="[5]{.chapter-number}&nbsp; [Introductory Statistics with R for Educational Researchers]{.chapter-title}">
<meta name="citation_abstract" content="Statistics play a fundamental role in learning analytics, providing a means to analyze and make sense of the vast amounts of data generated by learning environments. This chapter provides an introduction to basic statistical concepts using R and covers topics such as measures of central tendency, variability, correlation, and regression analysis. Specifically, readers will learn how to compute descriptive statistics, conduct hypothesis tests, and perform simple linear regression analysis. The chapter also includes practical examples using realistic data sets from the field of learning analytics. By the end of the chapter, readers should have a solid understanding of the basic statistical concepts and methods commonly used in learning analytics, as well as a practical understanding of how to use R to conduct statistical analysis of learning data.">
<meta name="citation_keywords" content="statistics, learning analytics, hypothesis testing">
<meta name="citation_author" content="Santtu Tikka">
<meta name="citation_author" content="Juho Kopra">
<meta name="citation_author" content="Merja Heinäniemi">
<meta name="citation_author" content="Sonsoles López-Pernas">
<meta name="citation_author" content="Mohammed Saqr">
<meta name="citation_fulltext_html_url" content="https://lamethods.github.io/ch5-stats.html">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=R: A language and environment for statistical computing;,citation_author=R Core Team;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://www.R-project.org/;">
<meta name="citation_reference" content="citation_title=RStudio: Integrated development environment for R;,citation_author=RStudio Team;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_fulltext_html_url=http://www.rstudio.com/;">
<meta name="citation_reference" content="citation_title=dplyr: A grammar of data manipulation;,citation_author=Hadley Wickham;,citation_author=Romain François;,citation_author=Lionel Henry;,citation_author=Kirill Müller;,citation_author=Davis Vaughan;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://CRAN.R-project.org/package=dplyr;">
<meta name="citation_reference" content="citation_title=tidyr: Tidy messy data;,citation_author=Hadley Wickham;,citation_author=Davis Vaughan;,citation_author=Maximilian Girlich;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://CRAN.R-project.org/package=tidyr;">
<meta name="citation_reference" content="citation_title=tibble: Simple data frames;,citation_author=Kirill Müller;,citation_author=Hadley Wickham;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://CRAN.R-project.org/package=tibble;">
<meta name="citation_reference" content="citation_title=readxl: Read excel files;,citation_author=Hadley Wickham;,citation_author=Jennifer Bryan;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://CRAN.R-project.org/package=readxl;">
<meta name="citation_reference" content="citation_title=readr: Read rectangular text data;,citation_author=Hadley Wickham;,citation_author=Jim Hester;,citation_author=Jennifer Bryan;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://CRAN.R-project.org/package=readr;">
<meta name="citation_reference" content="citation_title=Dates and times made easy with lubridate;,citation_author=Garrett Grolemund;,citation_author=Hadley Wickham;,citation_publication_date=2011;,citation_cover_date=2011;,citation_year=2011;,citation_fulltext_html_url=https://www.jstatsoft.org/v40/i03/;,citation_issue=3;,citation_volume=40;,citation_journal_title=Journal of Statistical Software;">
<meta name="citation_reference" content="citation_title=Automated results reporting as a practical tool to improve reproducibility and methodological best practices adoption;,citation_author=Dominique Makowski;,citation_author=Daniel Lüdecke;,citation_author=Indrajeet Patil;,citation_author=Rémi Thériault;,citation_author=Mattan S. Ben-Shachar;,citation_author=Brenton M. Wiernik;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://easystats.github.io/report/;,citation_journal_title=CRAN;">
<meta name="citation_reference" content="citation_title=Methods and algorithms for correlation analysis in R;,citation_author=Dominique Makowski;,citation_author=Mattan S. Ben-Shachar;,citation_author=Indrajeet Patil;,citation_author=Daniel Lüdecke;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_fulltext_html_url=https://joss.theoj.org/papers/10.21105/joss.02306;,citation_issue=51;,citation_doi=10.21105/joss.02306;,citation_volume=5;,citation_journal_title=Journal of Open Source Software;">
<meta name="citation_reference" content="citation_title=Welcome to the tidyverse;,citation_author=Hadley Wickham;,citation_author=Mara Averick;,citation_author=Jennifer Bryan;,citation_author=Winston Chang;,citation_author=Lucy D’Agostino McGowan;,citation_author=Romain François;,citation_author=Garrett Grolemund;,citation_author=Alex Hayes;,citation_author=Lionel Henry;,citation_author=Jim Hester;,citation_author=Max Kuhn;,citation_author=Thomas Lin Pedersen;,citation_author=Evan Miller;,citation_author=Stephan Milton Bache;,citation_author=Kirill Müller;,citation_author=Jeroen Ooms;,citation_author=David Robinson;,citation_author=Dana Paige Seidel;,citation_author=Vitalie Spinu;,citation_author=Kohske Takahashi;,citation_author=Davis Vaughan;,citation_author=Claus Wilke;,citation_author=Kara Woo;,citation_author=Hiroaki Yutani;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_issue=43;,citation_doi=10.21105/joss.01686;,citation_volume=4;,citation_journal_title=Journal of Open Source Software;">
<meta name="citation_reference" content="citation_title=performance: An R package for assessment, comparison and testing of statistical models;,citation_author=Daniel Lüdecke;,citation_author=Mattan S. Ben-Shachar;,citation_author=Indrajeet Patil;,citation_author=Philip Waggoner;,citation_author=Dominique Makowski;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_issue=60;,citation_doi=10.21105/joss.03139;,citation_volume=6;,citation_journal_title=Journal of Open Source Software;">
<meta name="citation_reference" content="citation_title=easystats: Framework for easy statistical modeling, visualization, and reporting;,citation_author=Daniel Lüdecke;,citation_author=Mattan S. Ben-Shachar;,citation_author=Indrajeet Patil;,citation_author=Brenton M. Wiernik;,citation_author=Etienne Bacher;,citation_author=Rémi Thériault;,citation_author=Dominique Makowski;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://easystats.github.io/easystats/;,citation_journal_title=CRAN;">
<meta name="citation_reference" content="citation_title=rio: A swiss-army knife for data file I/O;,citation_author=Chung-hong Chan;,citation_author=Geoffrey CH Chan;,citation_author=Thomas J. Leeper;,citation_author=Jason Becker;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;">
<meta name="citation_reference" content="citation_title=broom: Convert statistical objects into tidy tibbles;,citation_author=David Robinson;,citation_author=Alex Hayes;,citation_author=Simon Couch;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://CRAN.R-project.org/package=broom;">
<meta name="citation_reference" content="citation_title=see: An R package for visualizing statistical models;,citation_author=Daniel Lüdecke;,citation_author=Indrajeet Patil;,citation_author=Mattan S. Ben-Shachar;,citation_author=Brenton M. Wiernik;,citation_author=Philip Waggoner;,citation_author=Dominique Makowski;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_issue=64;,citation_doi=10.21105/joss.03393;,citation_volume=6;,citation_journal_title=Journal of Open Source Software;">
<meta name="citation_reference" content="citation_title=Gephi: An open source software for exploring and manipulating networks;,citation_author=Mathieu Bastian;,citation_author=Sebastien Heymann;,citation_author=Mathieu Jacomy;,citation_publication_date=2009;,citation_cover_date=2009;,citation_year=2009;,citation_fulltext_html_url=https://ojs.aaai.org/index.php/ICWSM/article/view/13937;,citation_doi=10.1609/icwsm.v3i1.13937;,citation_volume=3;,citation_conference_title=Third international AAAI conference on weblogs and social media;">
<meta name="citation_reference" content="citation_title=A tutorial on regularized partial correlation networks;,citation_author=S. Epskamp;,citation_author=E. I. Fried;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_issue=4;,citation_doi=10.1037/met0000167;,citation_volume=23;,citation_journal_title=Psychological Methods;">
<meta name="citation_reference" content="citation_title=R packages: Organize, test, document, and share your code;,citation_author=Hadley Wickham;,citation_publication_date=2015;,citation_cover_date=2015;,citation_year=2015;">
<meta name="citation_reference" content="citation_title=R for data science: Import, tidy, transform, visualize, and model data;,citation_author=Hadley Wickham;,citation_author=Garret Grolemund;,citation_publication_date=2016;,citation_cover_date=2016;,citation_year=2016;">
<meta name="citation_reference" content="citation_title=The probable error of a mean;,citation_author=William “Student” Sealy Gosset;,citation_publication_date=1908;,citation_cover_date=1908;,citation_year=1908;,citation_issue=1;,citation_doi=10.1093/biomet/6.1.1;,citation_volume=6;,citation_journal_title=Biometrika;">
<meta name="citation_reference" content="citation_title=The generalization of &amp;amp;amp;quot;student’s&amp;quot; problem when several different population variances are involved;,citation_author=B. L. Welch;,citation_publication_date=1947;,citation_cover_date=1947;,citation_year=1947;,citation_issue=1–2;,citation_doi=10.1093/biomet/34.1-2.28;,citation_volume=34;,citation_journal_title=Biometrika;">
<meta name="citation_reference" content="citation_title=On the criterion that a given system of deviations from the probable in the case of a correlated system of variables is such that it can be reasonably supposed to have arisen from random sampling;,citation_author=Karl Pearson;,citation_publication_date=1900;,citation_cover_date=1900;,citation_year=1900;,citation_issue=302;,citation_doi=10.1080/14786440009463897;,citation_volume=50;,citation_journal_title=Philosophical Magazine. Series 5;">
<meta name="citation_reference" content="citation_title=On the interpretation of \chi^2 from contingency tables, and the calculation of P;,citation_author=Ronald Aylmer Fisher;,citation_publication_date=1922;,citation_cover_date=1922;,citation_year=1922;,citation_issue=1;,citation_volume=85;,citation_journal_title=Journal of the Royal Statistical Society;">
<meta name="citation_reference" content="citation_title=On the “probable error” of a coefficient of correlation deduced from a small sample;,citation_author=Ronald Aylmer Fisher;,citation_publication_date=1921;,citation_cover_date=1921;,citation_year=1921;,citation_volume=1;,citation_journal_title=Metron;">
<meta name="citation_reference" content="citation_title=Use of ranks in one-criterion variance analysis;,citation_author=William H. Kruskal;,citation_author=W. Allen Wallis;,citation_publication_date=1952;,citation_cover_date=1952;,citation_year=1952;,citation_issue=260;,citation_doi=10.1080/01621459.1952.10483441;,citation_volume=47;,citation_journal_title=Journal of the American Statistical Association;">
<meta name="citation_reference" content="citation_title=Robust tests for equality of variances;,citation_author=Howard Levene;,citation_editor=Ingram Olkin;,citation_editor=Harold Hotelling;,citation_editor=others;,citation_publication_date=1960;,citation_cover_date=1960;,citation_year=1960;,citation_conference_title=Contributions to probability and statistics: Essays in honor of harold hotelling;,citation_conference=Stanford University Press;">
<meta name="citation_reference" content="citation_title=An analysis of variance test for normality (complete samples);,citation_author=Samuel Sanford Shapiro;,citation_author=Martin Bradbury Wilk;,citation_publication_date=1965;,citation_cover_date=1965;,citation_year=1965;,citation_issue=3–4;,citation_doi=10.1093/biomet/52.3-4.591;,citation_volume=52;,citation_journal_title=Biometrika;">
<meta name="citation_reference" content="citation_title=Properties of sufficiency and statistical tests;,citation_author=Maurice Stevenson Bartlett;,citation_publication_date=1937;,citation_cover_date=1937;,citation_year=1937;,citation_issue=901;,citation_volume=160;,citation_journal_title=Proceedings of the Royal Statistical Society, Series A;">
<meta name="citation_reference" content="citation_title=Johdatus tieteenfilosofiaan: Käsitteen- ja teorianmuodostus;,citation_author=Ilkka Niiniluoto;,citation_publication_date=1980;,citation_cover_date=1980;,citation_year=1980;">
<meta name="citation_reference" content="citation_title=Introductory statistics;,citation_author=Sheldon M. Ross;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;">
<meta name="citation_reference" content="citation_title=Testing statistical hypotheses;,citation_author=E. L. Lehmann;,citation_author=Joseph P. Romano;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_doi=https://doi.org/10.1007/978-3-030-70578-7;">
<meta name="citation_reference" content="citation_title=An introduction to generalized linear models;,citation_author=A. J. Dobson;,citation_publication_date=1990;,citation_cover_date=1990;,citation_year=1990;">
<meta name="citation_reference" content="citation_title=An R approach to data cleaning and wrangling for education research;,citation_author=Juho Kopra;,citation_author=Santtu Tikka;,citation_author=Merja Heinäniemi;,citation_author=Sonsoles López-Pernas;,citation_author=Mohammed Saqr;,citation_editor=Mohammed Saqr;,citation_editor=Sonsoles López-Pernas;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_inbook_title=Learning analytics methods and tutorials: A practical guide using R;">
<meta name="citation_reference" content="citation_title=Introductory statistics with R for educational researchers;,citation_author=Santtu Tikka;,citation_author=Juho Kopra;,citation_author=Merja Heinäniemi;,citation_author=Sonsoles López-Pernas;,citation_author=Mohammed Saqr;,citation_editor=Mohammed Saqr;,citation_editor=Sonsoles López-Pernas;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_inbook_title=undefined;">
<meta name="citation_reference" content="citation_title=Visualizing and reporting educational data with R;,citation_author=Sonsoles López-Pernas;,citation_author=Kamila Misiejuk;,citation_author=Santtu Tikka;,citation_author=Mohammed Saqr;,citation_author=Juho Kopra;,citation_author=Merja Heinäniemi;,citation_editor=Mohammed Saqr;,citation_editor=Sonsoles López-Pernas;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_inbook_title=Learning analytics methods and tutorials: A practical guide using R;">
<meta name="citation_reference" content="citation_title=The essential guide to effect sizes: Statistical power, meta-analysis, and the interpretation of research results;,citation_author=Paul D. Ellis;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;">
<meta name="citation_reference" content="citation_title=Statistical power analysis for the behavioral sciences;,citation_author=Jacob Cohen;,citation_publication_date=1988;,citation_cover_date=1988;,citation_year=1988;">
<meta name="citation_reference" content="citation_title=R markdown: The definititive guide;,citation_author=Yihui Xie;,citation_author=J. J. Allaire;,citation_author=Garret Grolemund;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;">
<meta name="citation_reference" content="citation_title=Statistical analysis with missing data;,citation_author=Roderick JA Little;,citation_author=Donald B Rubin;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_volume=793;">
<meta name="citation_reference" content="citation_title=Flexible imputation of missing data;,citation_author=Stef Buuren;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_fulltext_html_url=https://stefvanbuuren.name/fimd/;">
<meta name="citation_reference" content="citation_title=Statistical modelling of selective non-participation in health examination surveys;,citation_author=Juho Kopra;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_issue=164;,citation_journal_title=Report/University of Jyväskylä, Department of Mathematics and Statistics;,citation_publisher=University of Jyväskylä;">
<meta name="citation_reference" content="citation_title=mice: Multivariate imputation by chained equations in R;,citation_author=Stef Buuren;,citation_author=Karin Groothuis-Oudshoorn;,citation_publication_date=2011;,citation_cover_date=2011;,citation_year=2011;,citation_issue=3;,citation_doi=10.18637/jss.v045.i03;,citation_volume=45;,citation_journal_title=Journal of Statistical Software;">
<meta name="citation_reference" content="citation_title=stringr: Simple, consistent wrappers for common string operations;,citation_author=Hadley Wickham;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://CRAN.R-project.org/package=stringr;">
<meta name="citation_reference" content="citation_title=A broad collection of datasets for educational research training and application;,citation_author=Sonsoles López-Pernas;,citation_author=Mohammed Saqr;,citation_author=Javier Conde;,citation_author=Laura Del Rio;,citation_editor=Mohammed Saqr;,citation_editor=Sonsoles López-Pernas;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_inbook_title=Learning analytics methods and tutorials: A practical guide using R;">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Introductory Statistics with R for Educational Researchers</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Learning analytics methods and tutorials</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/lamethods/labook-code/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../contributors.html" class="sidebar-item-text sidebar-link">Contributors</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch01-intro/intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Getting started</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch02-data/ch2-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch03-intro-r/ch3-intor.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Intro to R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch04-data-cleaning/ch4-datacleaning.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data cleaning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch05-basic-stats/ch5-stats.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basic statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch06-data-visualization/ch6-viz.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data visualization</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Machine Learning</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch07-prediction/ch7-pred.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Predictive modeling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch08-clustering/ch8-clus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Clustering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch09-model-based-clustering/ch9-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Model-based clustering</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Temporal methods</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch10-sequence-analysis/ch10-seq.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequence analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch11-vasstra/ch11-vasstra.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">VaSSTra</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch12-markov/ch12-markov.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Markov models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch13-multichannel/ch13-multi.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Multi-channel sequences</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch14-process-mining/ch14-process.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Process mining</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Network analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch15-sna/ch15-sna.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Social Network Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch16-community/ch16-comm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Community detection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch17-temporal-networks/ch17-tna.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Temporal Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch18-ena-ona/ch18-ena.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Epistemic Network Analysis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">Psychometrics</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch19-psychological-networks/ch19-psych.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Psychological networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch20-factor-analysis/ch20-factor.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Factor analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch21-sem/ch21-sem.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Structured Equation Modeling</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch22-conclusion/ch22-conclusion.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Conclusion</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="toc-section-number">1</span>  Introduction</a></li>
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics"><span class="toc-section-number">2</span>  Descriptive statistics</a>
  <ul class="collapse">
  <li><a href="#measures-of-central-tendency" id="toc-measures-of-central-tendency" class="nav-link" data-scroll-target="#measures-of-central-tendency"><span class="toc-section-number">2.1</span>  Measures of central tendency</a></li>
  <li><a href="#measures-of-dispersion" id="toc-measures-of-dispersion" class="nav-link" data-scroll-target="#measures-of-dispersion"><span class="toc-section-number">2.2</span>  Measures of dispersion</a></li>
  <li><a href="#sec-covcorr" id="toc-sec-covcorr" class="nav-link" data-scroll-target="#sec-covcorr"><span class="toc-section-number">2.3</span>  Covariance and Correlation</a></li>
  <li><a href="#other-common-statistics" id="toc-other-common-statistics" class="nav-link" data-scroll-target="#other-common-statistics"><span class="toc-section-number">2.4</span>  Other common statistics</a></li>
  </ul></li>
  <li><a href="#statistical-hypothesis-testing" id="toc-statistical-hypothesis-testing" class="nav-link" data-scroll-target="#statistical-hypothesis-testing"><span class="toc-section-number">3</span>  Statistical hypothesis testing</a>
  <ul class="collapse">
  <li><a href="#students-t-test" id="toc-students-t-test" class="nav-link" data-scroll-target="#students-t-test"><span class="toc-section-number">3.1</span>  Student’s t-test</a></li>
  <li><a href="#chi-squared-test" id="toc-chi-squared-test" class="nav-link" data-scroll-target="#chi-squared-test"><span class="toc-section-number">3.2</span>  Chi-squared test</a></li>
  <li><a href="#analysis-of-variance" id="toc-analysis-of-variance" class="nav-link" data-scroll-target="#analysis-of-variance"><span class="toc-section-number">3.3</span>  Analysis of variance</a></li>
  <li><a href="#levenes-test" id="toc-levenes-test" class="nav-link" data-scroll-target="#levenes-test"><span class="toc-section-number">3.4</span>  Levene’s test</a></li>
  <li><a href="#shapiro-wilk-test" id="toc-shapiro-wilk-test" class="nav-link" data-scroll-target="#shapiro-wilk-test"><span class="toc-section-number">3.5</span>  Shapiro-Wilk test</a></li>
  </ul></li>
  <li><a href="#sec-correlation" id="toc-sec-correlation" class="nav-link" data-scroll-target="#sec-correlation"><span class="toc-section-number">4</span>  Correlation</a></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression"><span class="toc-section-number">5</span>  Linear regression</a></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression"><span class="toc-section-number">6</span>  Logistic regression</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="toc-section-number">7</span>  Conclusion</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading"><span class="toc-section-number">8</span>  Further reading</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">References</a></li>
  </ul>
</nav>
    <div class="quarto-margin-footer"><div class="margin-footer-item">
<p><small>© 2023 The authors</small></p>
</div></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Introductory Statistics with R for Educational Researchers</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Santtu Tikka </p>
             <p>Juho Kopra </p>
             <p>Merja Heinäniemi </p>
             <p>Sonsoles López-Pernas </p>
             <p>Mohammed Saqr </p>
          </div>
  </div>
    
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="abstract-title">Abstract</div>
    Statistics play a fundamental role in learning analytics, providing a means to analyze and make sense of the vast amounts of data generated by learning environments. This chapter provides an introduction to basic statistical concepts using R and covers topics such as measures of central tendency, variability, correlation, and regression analysis. Specifically, readers will learn how to compute descriptive statistics, conduct hypothesis tests, and perform simple linear regression analysis. The chapter also includes practical examples using realistic data sets from the field of learning analytics. By the end of the chapter, readers should have a solid understanding of the basic statistical concepts and methods commonly used in learning analytics, as well as a practical understanding of how to use R to conduct statistical analysis of learning data.
  </div>
</div>

</header>

<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>Learning analytics involves the practical application of statistical methods to quantitative data, which can represent various aspects of the learning process such as student engagement, progress, and outcomes. Thus, knowledge about basic statistical methods is essential. Let’s start with how statistics connects with the research process and how it is also linked with philosophy of science. According to Niiniluoto <span class="citation" data-cites="niiniluoto1980">[<a href="#ref-niiniluoto1980" role="doc-biblioref">1</a>]</span>, the research process can be described with the following eight steps:</p>
<ol type="1">
<li>Setting up a problem.</li>
<li>Disambiguation of the problem. Building a research strategy.</li>
<li>Collecting data.</li>
<li>Describing the data.</li>
<li>Analysis of data.</li>
<li>Interpreting the analyses.</li>
<li>Writing the report.</li>
<li>Publishing the results.</li>
</ol>
<p>Steps 1 and 2 require knowledge and skills related to the applied field, but also general scientific aptitude. Knowledge about statistics is central in steps 3, 4, 5, and 6. Finally, steps 7 and 8 mostly require skills in writing and communication. Overall, it can be argued that a solid understanding of statistics and statistical methods is crucial for anyone conducting research with quantitative data.</p>
<p>This chapter of the book concentrates on steps 4, 5, and 6 of the research process. We start with descriptive statistics, which are statistics that describe the overall features of the data. In contrast, inferential statistics are used to draw conclusions and make inferences about the population under study. Afterwards, we explain the basics of statistical hypothesis testing, which is the most common — although not the only — way to analyze data. The most common statistical tests, such as Student’s t-test, Chi-squared test, Analysis of variance, Levene’s test, and Shapiro-Wilk test are covered in this chapter. We also explain how to interpret the results of each test. We also present the linear regression model, which is not a statistical test but one of the most powerful statistical tools. Basic understanding of linear regression is essential for anyone interested in more advanced regression techniques, including logistic regression which is covered in the final section of this chapter. For a more in-depth view on the statistical tests covered in this chapter, we refer the reader to works such as <span class="citation" data-cites="sheldon2017 lehmann2022">[<a href="#ref-sheldon2017" role="doc-biblioref">2</a>, <a href="#ref-lehmann2022" role="doc-biblioref">3</a>]</span>.</p>
</section>
<section id="descriptive-statistics" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="descriptive-statistics"><span class="header-section-number">2</span> Descriptive statistics</h2>
<p>Descriptive statistics are used to provide a meaningful quantitative overview of data, and to summarize potentially vast amounts of information into more easily comprehensible and manageable quantities. In general, descriptive statistics are used as a first step in a data analysis workflow. In this section we will focus on numeric descriptors while visualizations are the topic of Chapter 6 <span class="citation" data-cites="LAbook6">[<a href="#ref-LAbook6" role="doc-biblioref">4</a>]</span>. For this chapter, we will use the combined Moodle data with students’ demographics, results, and summarized Moodle event activity. For more information about the dataset, please refer to Chapter 2 in this book <span class="citation" data-cites="LAbook2">[<a href="#ref-LAbook2" role="doc-biblioref">5</a>]</span>. We begin by installing all R packages that we will use in this chapter.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">"car"</span>, <span class="st">"rio"</span>, <span class="st">"see"</span>, <span class="st">"dplyr"</span>, <span class="st">"tidyr"</span>, </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"broom"</span>, <span class="st">"report"</span>, <span class="st">"correlation"</span>, <span class="st">"performance"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We use the <code>rio</code> <span class="citation" data-cites="rio">[<a href="#ref-rio" role="doc-biblioref">6</a>]</span> package to read the data files into R via the <code>import()</code> function. The <code>Events</code> dataset contains log data on the student’s Moodle activity such as Moodle event types and names. The <code>Demographics</code> dataset contains background information on the students such as their gender and location of study (categorical variables). Finally, the <code>Results</code> data contains grades on various aspects of the Moodle course including the final course grade (numeric variables). We also create a new variable called <code>AchievingGroup</code> that categorizes the students into bottom and top 50% of achievers in terms of the final grade. We will leverage the <code>dplyr</code> <span class="citation" data-cites="dplyr">[<a href="#ref-dplyr" role="doc-biblioref">7</a>]</span> and <code>tidyr</code> <span class="citation" data-cites="tidyr">[<a href="#ref-tidyr" role="doc-biblioref">8</a>]</span> packages to wrangle the data into a single combined dataset. We begin by reading the data files and by constructing the <code>AchievingGroup</code> variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"rio"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyr"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://github.com/lamethods/data/raw/main/1_moodleLAcourse/"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>events <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="fu">paste0</span>(url, <span class="st">"Events.xlsx"</span>), <span class="at">setclass =</span> <span class="st">"tibble"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>demographics <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="fu">paste0</span>(url, <span class="st">"Demographics.xlsx"</span>), <span class="at">setclass =</span> <span class="st">"tibble"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="fu">paste0</span>(url, <span class="st">"Results.xlsx"</span>), <span class="at">setclass =</span> <span class="st">"tibble"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">AchievingGroup =</span> <span class="fu">factor</span>(</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">case_when</span>(</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ntile</span>(Final_grade, <span class="dv">2</span>) <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Low achiever"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ntile</span>(Final_grade, <span class="dv">2</span>) <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"High achiever"</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we summarize the student’s engagement based on their Moodle activity into three groups: Low activity, Moderate activity and High Activity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>events_summary <span class="ot">&lt;-</span> events <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(user) <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tally</span>() <span class="sc">|&gt;</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Frequency.Total =</span> n) <span class="sc">|&gt;</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">ActivityGroup =</span> <span class="fu">factor</span>(</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">case_when</span>(</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ntile</span>(Frequency.Total, <span class="dv">3</span>) <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Low activity"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ntile</span>(Frequency.Total, <span class="dv">3</span>) <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"Moderate activity"</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ntile</span>(Frequency.Total, <span class="dv">3</span>) <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"High activity"</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We also count the different types of Moodle events.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>events_types <span class="ot">&lt;-</span> events <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(user, Action) <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Action) <span class="sc">|&gt;</span> </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> <span class="st">"Action"</span>, </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_prefix =</span> <span class="st">"Frequency."</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> <span class="st">"n"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_fill =</span> <span class="dv">0</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, we combine the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>all_combined <span class="ot">&lt;-</span> demographics <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(events_types, <span class="at">by =</span> <span class="st">"user"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(events_summary, <span class="at">by =</span> <span class="st">"user"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(results, <span class="at">by =</span> <span class="st">"user"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The various steps of the combined data construction are discussed in greater detail in Chapter 4 <span class="citation" data-cites="LAbook4">[<a href="#ref-LAbook4" role="doc-biblioref">9</a>]</span>.</p>
<section id="measures-of-central-tendency" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="measures-of-central-tendency"><span class="header-section-number">2.1</span> Measures of central tendency</h3>
<p>A typical way to summarize a univariate data sample is to describe its “middle point” using an appropriate statistic depending on the measurement scale of the data. The most common statistics to describe such a value are the <em>mean</em>, the <em>median</em>, and the <em>mode</em>.</p>
<p>For data on the interval or ratio scales (and sometimes also on the ordinal scale), the most common option is to use the arithmetic mean, which is available via the base R function <code>mean()</code>. This function takes a vector of values as its input.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>all_combined <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_grade =</span> <span class="fu">mean</span>(Final_grade),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_total =</span> <span class="fu">mean</span>(Frequency.Total)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["mean_grade"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["mean_total"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"7.253896","2":"735.5846"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The means are reported as a <code>tibble</code> with a single column for both variables.</p>
<p>For data on the ordinal scale (or interval or ratio scales), the median can be used which is defined as the value that separates the lower half from the bottom half of the data sample, i.e., the 50% quantile. The median can be computed in R using the built-in <code>median()</code> function. Similarly to <code>mean()</code>, this function also takes a vector of values as its input.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>all_combined <span class="sc">|&gt;</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_grade =</span> <span class="fu">median</span>(Final_grade),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_total =</span> <span class="fu">median</span>(Frequency.Total)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["median_grade"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["median_total"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"7.953882","2":"606"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Just like before, the medians are reported as a <code>tibble</code> with each value in its own column.</p>
<p>For data on the nominal or ordinal scale, the mode is a suitable choice as it describes the category with the highest number of observations. Unfortunately, there is no readily available function in R to compute the mode, and the reader should take care not to mistakenly use the <code>mode()</code> function, which is used to determine the internal storage mode of a variable (similar to the <code>typeof()</code> function). However, we can easily write our own function to compute the statistical mode as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>stat_mode <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  u <span class="ot">&lt;-</span> <span class="fu">unique</span>(x)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  u[<span class="fu">which.max</span>(<span class="fu">tabulate</span>(<span class="fu">match</span>(x, u)))]</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Functions in R are written using the following syntax. First, we define the name of the function, just like we would define the name of a variable when assigning data into it, in this case the name is <code>stat_mode</code>. Next, we assign the function definition, which starts with the keyword <code>function</code>. Next, we describe the function arguments within the parentheses, in this case we call our argument <code>x</code>, which we assume contains the data vector we wish to compute the mode for. Next, we define the body of the function within the braces. The body determines what the function does and what its output should be. Within the body, we first determine the unique values in the data vector <code>x</code>, and assign the result to a variable <code>u</code>. Next, we need to count the number of occurrences of each unique value. To start, we first match each observed value in <code>x</code> to the unique values in <code>u</code> to get the corresponding indices, which we will then count using tabulate. We obtain the index of the value with the highest number of occurrences with the function <code>which.max()</code>, and finally the corresponding unique value by selecting it from <code>u</code> using the subset operator, i.e., the brackets. Our function will now work on all types of data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>all_combined <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mode_gender =</span> <span class="fu">stat_mode</span>(Gender),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mode_location =</span> <span class="fu">stat_mode</span>(Location)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["mode_gender"],"name":[1],"type":["chr"],"align":["left"]},{"label":["mode_location"],"name":[2],"type":["chr"],"align":["left"]}],"data":[{"1":"F","2":"On campus"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The output is now similar to the <code>mean</code> and <code>median</code> functions that we used earlier, showing the modes of <code>Gender</code> and <code>Location</code> as a two-column <code>tibble</code>. For nominal variables, it is common to also compute the frequencies of each category. This can easily be done with the base R function <code>table()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(all_combined<span class="sc">$</span>Gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 F  M 
65 65 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(all_combined<span class="sc">$</span>Location)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
On campus    Remote 
      106        24 </code></pre>
</div>
</div>
<p>The function outputs the names of the categories and the frequency of each category as an integer vector.</p>
</section>
<section id="measures-of-dispersion" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="measures-of-dispersion"><span class="header-section-number">2.2</span> Measures of dispersion</h3>
<p>For data on the interval and ratio scales (and sometimes also on the ordinal scale), it is also meaningful to describe how clustered or scattered the values in the sample are, i.e., how far apart the values are from one another. Commonly used measures of statistical dispersion include the <em>variance</em>, <em>standard deviation</em>, and the <em>interquartile range</em>. Typically, such measures have the value 0 when all values in the sample are identical, and the value increases as the dispersion in the data grows.</p>
<p>All three measures can be readily computed with built-in R functions <code>var()</code>, <code>sd()</code>, and <code>IQR()</code> respectively. Like <code>mean()</code> and <code>median()</code>, these functions accept a vector or numeric values as input.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>all_combined <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">var_grade =</span> <span class="fu">var</span>(Final_grade),</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_grade =</span> <span class="fu">sd</span>(Final_grade),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">iqr_grade =</span> <span class="fu">IQR</span>(Final_grade)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["var_grade"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["sd_grade"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["iqr_grade"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"4.807344","2":"2.192566","3":"3.340339"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The variance, standard deviation and interquartile range of the final grade are returned as a <code>tibble</code> with three columns.</p>
</section>
<section id="sec-covcorr" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="sec-covcorr"><span class="header-section-number">2.3</span> Covariance and Correlation</h3>
<p>Covariance and correlation measure the linear dependence between two variables. Correlation is a unitless measure between -1 and 1, whereas covariance is not, and its scale depends on the scale of the variables. The sign of both measures indicates the tendency of the relationship. Positive sign means that as the value of one variable increases, the value of the other variable tends to increase as well. Conversely, a negative sign indicates that the value of the second variable tends to decrease as the value of the first variable increases.</p>
<p>Both covariance and correlation and be computed directly in R using the functions <code>cov()</code> and <code>cor()</code>, respectively.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>all_combined <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cov_grade_total =</span> <span class="fu">cov</span>(Final_grade, Frequency.Total),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">cor_grade_total =</span> <span class="fu">cor</span>(Final_grade, Frequency.Total),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["cov_grade_total"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["cor_grade_total"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"504.0414","2":"0.5131985"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>We obtain the covariance and correlation between the final grade and total number of Moodle events. We will familiarize ourselves with correlations in greater depth in <a href="#sec-correlation"><span>Section&nbsp;5.4</span></a>.</p>
</section>
<section id="other-common-statistics" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="other-common-statistics"><span class="header-section-number">2.4</span> Other common statistics</h3>
<p>The extreme values of a data sample can be found using the function <code>range()</code>, which computes the minimum and maximum values of the sample as a vector. These values can also be computed individually with the corresponding functions <code>min()</code> and <code>max()</code>. Because <code>summarise()</code> only allows a single value as output per row, we use the <code>reframe()</code> function instead when computing the range.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>all_combined <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">reframe</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">range_grade =</span> <span class="fu">range</span>(Final_grade)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["range_grade"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"0"},{"1":"10"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>all_combined <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(Final_grade),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(Final_grade)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["min"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["max"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"0","2":"10"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>With <code>reframe()</code>, we obtain a <code>tibble</code> with two rows, the first containing the minimum value and the second the maximum value of the final grade. If we instead use <code>summarise()</code> like before, we can only obtain one value per computed variable. The <code>summary()</code> function can also be used to quickly compute several of the most common descriptive statistics for all variables of a dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>results <span class="sc">|&gt;</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Grade.SNA_1<span class="sc">:</span>Grade.Group_self) <span class="sc">|&gt;</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Grade.SNA_1      Grade.SNA_2      Grade.Review    Grade.Group_self
 Min.   : 0.000   Min.   : 0.000   Min.   : 0.000   Min.   : 0.000  
 1st Qu.: 8.000   1st Qu.: 9.000   1st Qu.: 6.670   1st Qu.: 9.000  
 Median : 9.000   Median :10.000   Median : 8.000   Median :10.000  
 Mean   : 8.346   Mean   : 9.262   Mean   : 7.724   Mean   : 8.085  
 3rd Qu.:10.000   3rd Qu.:10.000   3rd Qu.: 9.670   3rd Qu.:10.000  
 Max.   :10.000   Max.   :10.000   Max.   :10.000   Max.   :10.000  </code></pre>
</div>
</div>
<p>The output shows the minimum and maximum values, the quartiles, and the mean of each variable that we selected.</p>
</section>
</section>
<section id="statistical-hypothesis-testing" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="statistical-hypothesis-testing"><span class="header-section-number">3</span> Statistical hypothesis testing</h2>
<p>Statistical hypothesis testing aims to evaluate hypotheses about a population of interest using probabilistic inference. The starting point of any statistical test is a so-called <em>null hypothesis</em> (denoted by <span class="math inline">\(H_0\)</span>), which typically corresponds to a scenario, where evidence supporting a specific hypothesis is a result of pure chance. For example, when evaluating whether a new drug is an efficient form of treatment via a randomized controlled trial, the null hypothesis could be that the drug has no effect on the response. A null hypothesis is always associated with an <em>alternative hypothesis</em> (denoted by <span class="math inline">\(H_1\)</span>), which is typically the inverse of the null hypothesis and corresponds to the hypothesis of interest, e.g., the drug has an effect on the response.</p>
<p>Statistical tests operate by assuming that the null hypothesis is true, and highly unlikely events under this assumption are typically regarded as giving cause for rejecting the null hypothesis. A statistical test is associated with a <em>test statistic</em>, which is a measure of how much the observations deviate from the null hypothesis scenario. The distribution of the test statistic under the null hypothesis and the sample test statistic can be used to compute the probability of obtaining a test statistic as extreme or more extreme than the one observed, assuming that the null hypothesis is true. This probability is known as the <em>p-value</em>, which is often mischaracterized even in scientific literature. For instance, the p-value is not the probability that the null hypothesis is true or that the alternative hypothesis is false. The p-value also does not quantify the size of the observed effect, or its real-world importance.</p>
<p>Typically, a <em>confidence level</em> is decided before applying a statistical test (usually denoted by <span class="math inline">\(\alpha\)</span>), and the null hypothesis is rejected if the observed p-value is smaller than this confidence level. If the p-value is greater than the confidence level, the null hypothesis is not rejected. Traditionally, the confidence level is 0.05, but this convention varies by field, and should be understood as being arbitrary, i.e., there is nothing special about the value 0.05. If the p-value falls below the confidence level, the result is regarded as <em>statistically significant</em>.</p>
<p>Hypothesis testing is a powerful tool for drawing conclusions from data, but it is important to use it appropriately and to understand its limitations. Every statistical test is associated with a set of assumptions which are often related to the distribution of the data sample. If these assumptions are violated, then the results of the test may be unreliable. In the following sections, some of the most common statistical tests are introduced. We will take advantage of the <code>report</code> <span class="citation" data-cites="report">[<a href="#ref-report" role="doc-biblioref">10</a>]</span> package and the corresponding function <code>report()</code> to showcase the results of the various statistical tests. For more information on the concepts and principles related to statistical hypothesis testing, see e.g., <span class="citation" data-cites="sheldon2017 lehmann2022">[<a href="#ref-sheldon2017" role="doc-biblioref">2</a>, <a href="#ref-lehmann2022" role="doc-biblioref">3</a>]</span>.</p>
<section id="students-t-test" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="students-t-test"><span class="header-section-number">3.1</span> Student’s t-test</h3>
<p>Student’s t-test <span class="citation" data-cites="student">[<a href="#ref-student" role="doc-biblioref">11</a>]</span> is one of the most well-known statistical tests. It compares the mean values of variables either between two populations or between a single population and a reference level and is thus applicable to continuous variables. The test assumes homogeneity of variance and that the data originates from a normal distribution. For nonhomogeneous data, the test can still be performed by using an approximation <span class="citation" data-cites="welch">[<a href="#ref-welch" role="doc-biblioref">12</a>]</span>. In R, all variants of the t-test test can be applied using the function <code>t.test()</code>.</p>
<p>Our goal is to compare the students’ Moodle activity with respect to their final grade. For this purpose, we use the binary variable called <code>AchievingGroup</code> which categorizes the students into top and bottom 50% achievers in terms of the final grade.</p>
<section id="one-sample-t-test" class="level4" data-number="3.1.1">
<h4 data-number="3.1.1" class="anchored" data-anchor-id="one-sample-t-test"><span class="header-section-number">3.1.1</span> One-sample t-test</h4>
<p>The one-sample t-test compares the mean of a data sample against a reference value, typically defined by the null hypothesis. Let us begin by testing the hypothesis that the average number of Moodle events (<code>Frequency.Total</code>) is 600 (<span class="math inline">\(H_0 : \mu = 600\)</span>). The function <code>t.test()</code> can be used in various ways, but in this example we provide the function with a <code>formula</code> object <code>Frequency.Total ~ 1</code> as the first argument. The formula syntax is a standard method for defining statistical models and other dependency structures in R. The formula defines that the left-hand side of the <code>~</code> symbol is a response variable which is explained by the terms on the right-hand side. Because we’re not conducting the test with respect to any other variable, the right-hand side of the formula is simply <code>1</code>, which means that it is a constant in the R formula syntax. This does not mean for example, that our null hypothesis would be that the number of Moodle events is 1. The expected value that the test is applied against (i.e., the value we assume <span class="math inline">\(\mu\)</span> to have under the null hypothesis) is defined via the argument <code>mu</code>, which by default has the value 0 for a one-sample t-test. Argument <code>data</code> defines in which environment the formula should be evaluated. By providing the <code>all_combined</code> data, we do not have to explicitly extract the <code>FrequencyTotal</code> variable from the data in the formula by writing <code>all_combined$Frequency.Total</code> or by using <code>pull()</code>. This is especially useful when the formula contains several variables from the same data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>ttest_one <span class="ot">&lt;-</span> <span class="fu">t.test</span>(Frequency.Total <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> all_combined, <span class="at">mu =</span> <span class="dv">600</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>ttest_one</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  Frequency.Total
t = 3.4511, df = 129, p-value = 0.0007553
alternative hypothesis: true mean is not equal to 600
95 percent confidence interval:
 657.8530 813.3163
sample estimates:
mean of x 
 735.5846 </code></pre>
</div>
</div>
<p>As a result, we obtain the value of the test statistic (<code>t = 3.4511</code>), the degrees of freedom (<code>df = 129</code>), and the p-value of the test (<code>p-value = 0.0007553</code>). Because the p-value is very small (much smaller than the standard 0.05 confidence level), we reject the null hypothesis, which means that the average number of Moodle events is significantly different from 600. The output of the test result object also describes the alternative hypothesis <span class="math inline">\(H_1\)</span> under <code>alternative hypothesis</code>, and the confidence interval of the test statistic.</p>
<p>We produce a summarized report of the test results with the <code>report()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(ttest_one)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Unable to retrieve data from htest object.
  Returning an approximate effect size using t_to_d().</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Effect sizes were labelled following Cohen's (1988) recommendations.

The One Sample t-test testing the difference between Frequency.Total (mean =
735.58) and mu = 600 suggests that the effect is positive, statistically
significant, and small (difference = 135.58, 95% CI [657.85, 813.32], t(129) =
3.45, p &lt; .001; Cohen's d = 0.30, 95% CI [0.13, 0.48])</code></pre>
</div>
</div>
<p>This produces a description of the results of the test that is easier to read and interpret than the direct output of the test result object. We note that a warning is also produced which we can safely ignore in this case. The warning occurs because the test result object <code>ttest_one</code> does not retain the original data <code>all_combined</code> which we used to carry out the test. If non-approximate effect sizes are desired, the test should be carried out by supplying the variables being compared directly without using the formula interface of the <code>t.test()</code> function. For more information on the effect size, see e.g., <span class="citation" data-cites="ellis2010 cohen1988">[<a href="#ref-ellis2010" role="doc-biblioref">13</a>, <a href="#ref-cohen1988" role="doc-biblioref">14</a>]</span>.</p>
</section>
<section id="two-sample-t-test" class="level4" data-number="3.1.2">
<h4 data-number="3.1.2" class="anchored" data-anchor-id="two-sample-t-test"><span class="header-section-number">3.1.2</span> Two-sample t-test</h4>
<p>In contrast to the one-sample t-test, the two-sample t-test compares the means of two data samples against one another. For example, suppose that we’re interested in the hypothesis that the average number of Moodle events is the same for the top and bottom 50% achievers (<span class="math inline">\(H_0: \mu_1 = \mu_2\)</span>). We can once again leverage the formula syntax, but instead of the constant <code>1</code> on the right-hand side of the formula, we will now replace it with the variable <code>Achievement</code> which defines the achievement level.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>ttest_two <span class="ot">&lt;-</span> <span class="fu">t.test</span>(Frequency.Total <span class="sc">~</span> AchievingGroup, <span class="at">data =</span> all_combined)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>ttest_two</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Frequency.Total by AchievingGroup
t = 4.4749, df = 95.988, p-value = 2.102e-05
alternative hypothesis:
true difference in means between group 1 and group 2 is not equal to 0
95 percent confidence interval:
 182.6427 473.8496
sample estimates:
mean in group High achiever  mean in group Low achiever 
                   899.7077                    571.4615 </code></pre>
</div>
</div>
<p>The contents of the result object are mostly the same as in the case of the one-sample t-test. The result is again statistically significant (using the 0.05 confidence level) meaning that according to the test, the average number of Moodle events is higher for the top 50% achievers. The <code>report()</code> function can be used to produce a similar summary as in the case of the one-sample t-test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(ttest_two)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Unable to retrieve data from htest object.
  Returning an approximate effect size using t_to_d().</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Effect sizes were labelled following Cohen's (1988) recommendations.

The Welch Two Sample t-test testing the difference of Frequency.Total by
AchievingGroup (mean in group High achiever = 899.71, mean in group Low achiever =
571.46) suggests that the effect is positive, statistically significant, and large
(difference = 328.25, 95% CI [182.64, 473.85], t(95.99) = 4.47, p &lt; .001; Cohen's d
= 0.91, 95% CI [0.49, 1.33])</code></pre>
</div>
</div>
<p>This produces the same warning as before in the one-sample case, but we can safely ignore it again.</p>
</section>
<section id="paired-two-sample-t-test" class="level4" data-number="3.1.3">
<h4 data-number="3.1.3" class="anchored" data-anchor-id="paired-two-sample-t-test"><span class="header-section-number">3.1.3</span> Paired two-sample t-test</h4>
<p>Instead of directly comparing the means of two groups, it may sometimes be of interest to compare differences between pairs of measurements. Such a scenario typically arises in an experiment, where subjects are paired, or two sets of measurements are taken from the same subjects. While our Moodle event data does not contain such measurement pairs, we could still imagine that our data was organized such that each student in the bottom 50% achievers was paired with a student in the top 50% achievers and that there is a one-to-one correspondence between the two achievement groups. This dependency between the two groups is the key difference between the paired test and the two-sample test.</p>
<p>A more suitable approach for paired data is to test the differences between the pairs, e.g., the differences between the number of Moodle events in our scenario. We supply the <code>t.test()</code> function with the argument <code>paired = TRUE</code> so that it will take the measurement pairs into account. In this test, the null hypothesis is that the mean difference between the student pairs is zero (<span class="math inline">\(H_0 : \mu_d = 0\)</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>ttest_paired <span class="ot">&lt;-</span> <span class="fu">t.test</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  Frequency.Total <span class="sc">~</span> AchievingGroup, <span class="at">data =</span> all_combined, <span class="at">paired =</span> <span class="cn">TRUE</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>ttest_paired</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  Frequency.Total by AchievingGroup
t = 4.3733, df = 64, p-value = 4.599e-05
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 178.3014 478.1910
sample estimates:
mean difference 
       328.2462 </code></pre>
</div>
</div>
<p>The result is once again statistically significant, and we reject the null hypothesis. Because the mean difference between the pairs is positive, this means average number of Moodle events is higher for the top 50% achievers of the pairs.</p>
<p>Paired two-sample t-test is also supported by <code>report()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(ttest_paired)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Unable to retrieve data from htest object.
  Returning an approximate effect size using t_to_d().</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Effect sizes were labelled following Cohen's (1988) recommendations.

The Paired t-test testing the difference of Frequency.Total by AchievingGroup (mean
difference = 328.25) suggests that the effect is positive, statistically
significant, and medium (difference = 328.25, 95% CI [178.30, 478.19], t(64) =
4.37, p &lt; .001; Cohen's d = 0.55, 95% CI [0.28, 0.81])</code></pre>
</div>
</div>
<p>We can once again safely ignore the produced warning message.</p>
</section>
</section>
<section id="chi-squared-test" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="chi-squared-test"><span class="header-section-number">3.2</span> Chi-squared test</h3>
<p>The chi-squared test is used for the analysis of contingency tables; it tests whether two categorical variables are independent or not <span class="citation" data-cites="chisq">[<a href="#ref-chisq" role="doc-biblioref">15</a>]</span>. A typical use case for this test is to investigate differences between groups such as student attendance by location or gender. The basic idea of the test is to compare the observed contingency table to a table under the null hypothesis where the variables are independent. The chi-squared test is based on the cell-specific differences between these two tables. As a general rule, the test assumes that the expected value is at least 5 in at least 80% of the cells, and that no expected values are below 1. If these assumptions are violated, the results of the test may not be reliable. In such cases, Fisher’s exact test <span class="citation" data-cites="fishertest">[<a href="#ref-fishertest" role="doc-biblioref">16</a>]</span> can be used instead via the function <code>fisher.test()</code>, but it may be computationally slow for large contingency tables. Both the chi-squared test and Fisher’s exact test assume that the data is a random sample from the population.</p>
<p>We will use the combined Moodle data to investigate whether the achievement level and the activity level of the students are independent. First, we must create the contingency table from the individual-level data. We use the <code>table()</code> function for this purpose.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">table</span>(all_combined<span class="sc">$</span>ActivityGroup, all_combined<span class="sc">$</span>AchievingGroup)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   
                    High achiever Low achiever
  High activity                27           16
  Low activity                 14           30
  Moderate activity            24           19</code></pre>
</div>
</div>
<p>The table shows the observed frequencies in each cell, i.e., for each combination of activity and achievement. Next, we apply the chi-squared test using the <code>chisq.test()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>Xsq_test <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(tab)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>Xsq_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tab
X-squared = 9.2135, df = 2, p-value = 0.009984</code></pre>
</div>
</div>
<p>Printing the test result object shows the test statistic (<code>X-squared</code>), the associated degrees of freedom (<code>df</code>) and the p-value (<code>p-value</code>). The p-value is very small, meaning that we reject the null hypothesis. In other words, the achievement and activity levels of the students are not independent. This is not a surprising result, as more active students are more likely to engage with the course content and perform better in terms of the learning outcomes. We can confirm that the assumptions of the test related to the expected values of the cells were not violated by using the test result object, which contains the expected values of the cells in the element <code>expected</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(Xsq_test<span class="sc">$</span>expected <span class="sc">&gt;=</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(Xsq_test<span class="sc">$</span>expected <span class="sc">&gt;=</span> <span class="dv">5</span>) <span class="sc">&gt;=</span> <span class="fl">0.80</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>All expected values were greater than one, and over 80% of the expected values were greater than 5. This means that the assumptions are satisfied for our data and thus the results are reliable. Here, we used the function <code>all()</code> which takes a <code>logical</code> vector as input and returns <code>TRUE</code> if all elements of the vector were <code>TRUE</code>. Otherwise, the function returns <code>FALSE</code>. Unfortunately, the <code>report()</code> function does not support the chi-squared test.</p>
</section>
<section id="analysis-of-variance" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="analysis-of-variance"><span class="header-section-number">3.3</span> Analysis of variance</h3>
<p>Analysis of variance (ANOVA) <span class="citation" data-cites="anova">[<a href="#ref-anova" role="doc-biblioref">17</a>]</span> can be viewed as the generalization of Student’s t-test, where instead of one or two groups, the means of a variable are compared across multiple groups simultaneously. The name of the method comes from its test statistic, which is based on a decomposition of the total variance of the variable into variance within the groups and between the groups. ANOVA makes several assumptions: the observations are independent, the residuals of the underlying linear model follow a normal distribution, and that the variance of the variable is the same across groups (homoscedasticity). If these assumptions are violated, the results of the test may not be reliable. One alternative in such instances is to use the non-parametric Kruskal-Wallis test <span class="citation" data-cites="kruskal">[<a href="#ref-kruskal" role="doc-biblioref">18</a>]</span> instead, which is available in R via the function <code>kruskal.test()</code>. This test uses the ranks of the observations, and the null hypothesis is that the medians are the same for each group.</p>
<p>We use our combined Moodle data to demonstrate ANOVA. Instead of comparing the total number of Moodle events between top and bottom 50% of achievers, this time we will compare the final grade of the students across three activity groups: low activity, moderate activity, and high activity, described by the variable <code>ActivityGroup</code>. Thus the null and alternative hypotheses are in this case:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The expected values of the final grade are the same across the three activity groups (<span class="math inline">\(\mu_1 = \mu_2 = \mu_3\)</span>),</li>
<li><span class="math inline">\(H_1\)</span>: At least one activity group has a different expected final grade (<span class="math inline">\(\mu_i \ne \mu_j\)</span> for at least one pair <span class="math inline">\(i \ne j\)</span>).</li>
</ul>
<p>To carry out the analysis, we apply the <code>aov</code> function, which uses the same formula syntax to define the response variable and the groups as the <code>t.test()</code> function does. Next, we apply the <code>summary()</code> function to the <code>aov()</code> function return object <code>fit</code>, as the default output of <code>aov()</code> is not very informative.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">aov</span>(Final_grade <span class="sc">~</span> ActivityGroup, <span class="at">data =</span> all_combined)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
ActivityGroup   2  175.7   87.87   25.11 6.47e-10 ***
Residuals     127  444.4    3.50                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The summary contains the following columns: <code>Df</code> describes the degrees of freedom of the <span class="math inline">\(F\)</span>-distribution associated with the test, <code>Sum Sq</code> reports the sum of squares related to the groups and the residuals, <code>Mean Sq</code> reports the corresponding mean sum of squares, <code>F value</code> is the value of the test statistic, and finally <code>Pr(&gt;F)</code> is the p-value of the test. For this example, the p-value is very small, which means that the null hypothesis is rejected, and there are statistically significant differences in the final grade between the groups according to the test. In the following sections we will learn how to test for the assumptions related to normality and homoscedasticity. The <code>report()</code> function can be used for the output of <code>aov()</code> as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The ANOVA (formula: Final_grade ~ ActivityGroup) suggests that:

  - The main effect of ActivityGroup is statistically significant and large (F(2,
127) = 25.11, p &lt; .001; Eta2 = 0.28, 95% CI [0.17, 1.00])

Effect sizes were labelled following Field's (2013) recommendations.</code></pre>
</div>
</div>
<p>This output also reports the degrees of freedom, the test statistic value and the p-value but in a more easily readable format.</p>
<p>Note that ANOVA simply measures if there are differences between the groups but does not provide information on how these differences emerge. For example, there could be a single group that is different from all the rest, or two subgroups where the means are similar within each group, but different between the subgroups. Visualizations can be a helpful tool for gaining more insight into the differences, and post-hoc pairwise tests can be carried out to compare the pairs of groups.</p>
</section>
<section id="levenes-test" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="levenes-test"><span class="header-section-number">3.4</span> Levene’s test</h3>
<p>Levene’s test is used to investigate whether the variance of a variable is the same across two or more groups <span class="citation" data-cites="levene">[<a href="#ref-levene" role="doc-biblioref">19</a>]</span>. Compared to alternatives such as Bartlett’s test <span class="citation" data-cites="bartlett">[<a href="#ref-bartlett" role="doc-biblioref">20</a>]</span>, Levene’s test is less sensitive to non-normal observations. The test is not available in base R, but it can be found in the <code>car</code> package as the function <code>leveneTest()</code>. The function uses the same formula syntax as <code>t.test()</code> and <code>aov()</code>. We will investigate the homogeneity of the variance of the final grade between the activity groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"car"</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(Final_grade <span class="sc">~</span> ActivityGroup, <span class="at">data =</span> all_combined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["F value"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"5.720416","3":"0.004180801","_rn_":"group"},{"1":"127","2":"NA","3":"NA","_rn_":""}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The output of <code>leveneTest()</code> is analogous to the output of the ANOVA summary, and it contains the degrees of freedom (<code>Df</code>), the value of the test statistic (<code>F value</code>) and the p-value of the test (<code>Pr(&gt;F)</code>). The p-value is very small, so we reject the null hypothesis meaning that the variance of the final grade is not the same across the groups according to the test. This means that the assumption of homoscedasticity is violated for the analysis of variance of the final grade, and thus the results may not be reliable. The <code>report()</code> function is not supported for <code>leveneTest()</code>.</p>
</section>
<section id="shapiro-wilk-test" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="shapiro-wilk-test"><span class="header-section-number">3.5</span> Shapiro-Wilk test</h3>
<p>Shapiro-Wilk test tests the null hypothesis that a data sample originated from a normal distribution <span class="citation" data-cites="shapirowilk">[<a href="#ref-shapirowilk" role="doc-biblioref">21</a>]</span>. The test is available in base R as the function <code>shapiro.test()</code>. Unfortunately, this function does not support the formula syntax unlike the other test functions we have used thus far. The function only accepts a single <code>numeric</code> vector as its argument. Therefore, to test the normality of multiple groups simultaneously, the data must first be split into the groups to be tested. We apply the test to the final grade in each achievement group. With the help of the <code>broom</code> package <span class="citation" data-cites="broom">[<a href="#ref-broom" role="doc-biblioref">22</a>]</span>, we wrap the test results into a tidy format.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"broom"</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>all_combined <span class="sc">|&gt;</span> </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Performs the computations in each activity group</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ActivityGroup) <span class="sc">|&gt;</span> </span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Apply a function in each group</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_modify</span>(<span class="sc">~</span>{</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Apply the Shapiro test in each group and create tidy output</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">shapiro.test</span>(.<span class="sc">$</span>Final_grade) <span class="sc">|&gt;</span> </span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">tidy</span>()</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  }) <span class="sc">|&gt;</span> </span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Selection of variables to keep in the output</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ActivityGroup, statistic, p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["ActivityGroup"],"name":[1],"type":["fct"],"align":["left"]},{"label":["statistic"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["p.value"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"High activity","2":"0.9176265","3":"0.0044842184"},{"1":"Low activity","2":"0.9094477","3":"0.0021518690"},{"1":"Moderate activity","2":"0.8615623","3":"0.0001034062"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>This is also a great example of the tidyverse paradigm. First, we group the data by <code>ActivityGroup</code> using <code>group_by()</code>, and then apply a function in each group using <code>group_modify()</code>. We apply the <code>shapiro.test()</code> function to the <code>Final_grade</code> variable, and then we convert the test results into a tidy tibble using the <code>tidy()</code> function from the <code>broom</code> package. We also use the special dot notation <code>.</code> to select the final grade variable from the data in each group. Finally, we select the grouping variable (<code>ActivityGroup</code>), the test statistic (<code>statistic</code>) and the p-value (<code>p.value</code>) of each test using <code>select()</code> and print the results. The resulting object is a tibble with three columns: <code>ActivityGroup</code>, <code>statistic</code> and <code>p.value</code>, the last two of which give the test statistic and p-value of the test for the activity group of the first column.</p>
<p>We can see that according to the test, the <code>Final_grade</code> variable is not normally distributed in any of the activity groups, as the p-values are very small. As a consequence, the results of the analysis of variance carried out earlier may not be reliable.</p>
</section>
</section>
<section id="sec-correlation" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="sec-correlation"><span class="header-section-number">4</span> Correlation</h2>
<p>In <a href="#sec-covcorr"><span>Section&nbsp;5.2.3</span></a>, we briefly described covariance and correlation, and showcased the base R functions to compute them. However, there are several powerful and user-friendly packages for the analysis and reporting of correlations, such as the <code>correlation</code> <span class="citation" data-cites="correlation">[<a href="#ref-correlation" role="doc-biblioref">23</a>]</span> package which we will demonstrate in this section.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"correlation"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For example, the package can easily compute all pairwise correlations between the numeric variables of the data with the function <code>correlation()</code>. The argument <code>select</code> can be used to compute the correlations only for a subset of the variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>corrs <span class="ot">&lt;-</span> <span class="fu">correlation</span>(</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  all_combined, </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">select =</span> <span class="fu">c</span>(<span class="st">"Frequency.Total"</span>, <span class="st">"Grade.Theory"</span>, <span class="st">"Final_grade"</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>corrs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Parameter1"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Parameter2"],"name":[2],"type":["chr"],"align":["left"]},{"label":["r"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["CI"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["CI_low"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["CI_high"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["t"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["df_error"],"name":[8],"type":["int"],"align":["right"]},{"label":["p"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["Method"],"name":[10],"type":["chr"],"align":["left"]},{"label":["n_Obs"],"name":[11],"type":["int"],"align":["right"]}],"data":[{"1":"Frequency.Total","2":"Grade.Theory","3":"0.3148386","4":"0.95","5":"0.1508291","6":"0.4619804","7":"3.752842","8":"128","9":"2.640097e-04","10":"Pearson correlation","11":"130","_rn_":"1"},{"1":"Frequency.Total","2":"Final_grade","3":"0.5131985","4":"0.95","5":"0.3740671","6":"0.6297375","7":"6.764980","8":"128","9":"1.286134e-09","10":"Pearson correlation","11":"130","_rn_":"2"},{"1":"Grade.Theory","2":"Final_grade","3":"0.4494841","4":"0.95","5":"0.3005598","6":"0.5770124","7":"5.692823","8":"128","9":"1.623322e-07","10":"Pearson correlation","11":"130","_rn_":"3"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The columns <code>Parameter1</code> and <code>Parameter2</code> describe the variables that the correlation was computed for, <code>r</code> is the value of the sample correlation, and the remaining columns report the 95% confidence interval, the value of the test statistic, and the p-value of the test (a t-test for correlations) along with the statistical significance. By default, Pearson’s correlation coefficient is calculated, but the package also supports many alternative correlation measures. The correlation coefficient to be computed can be selected with the argument <code>method</code> that has the value <code>"pearson"</code> by default. Selecting for example <code>method = "spearman"</code> would compute the Spearman correlation coefficient instead. We can also obtain a correlation matrix by using <code>summary()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(corrs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Parameter"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Final_grade"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Grade.Theory"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"Frequency.Total","2":"0.5131985","3":"0.3148386","_rn_":"1"},{"1":"Grade.Theory","2":"0.4494841","3":"NA","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>By default, redundant correlations are omitted, but they can be obtained by setting <code>redundant = TRUE</code> in the call to <code>summary()</code>. A plot of the correlation matrix can be produced with the help of the package <code>see</code> <span class="citation" data-cites="see">[<a href="#ref-see" role="doc-biblioref">24</a>]</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"see"</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>corrs <span class="sc">|&gt;</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Also include redundant correlations</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(<span class="at">redundant =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ch5-stats_files/figure-html/corrmatrixplot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The plot shows the strength of the correlations where darker colors imply stronger correlations. Visualizations will be covered at greater length in Chapter 6 <span class="citation" data-cites="LAbook6">[<a href="#ref-LAbook6" role="doc-biblioref">4</a>]</span>.</p>
</section>
<section id="linear-regression" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="linear-regression"><span class="header-section-number">5</span> Linear regression</h2>
<p>Linear regression is a statistical tool where one continuous variable is explained by the values of other variables. The variable of interest is said to be a dependent, while the other variables are called predictors. Predictors may also be called explanatory variables, independent variables or covariates depending on the context, applied field, and perspective.</p>
<p>Consider a very simple case, where we only have one predictor, which happens to be a continuous variable. In this case, fitting a linear regression model is merely the same as fitting a straight line to a scatterplot. It is assumed that deviations from this line are simply a result of random variation. <!-- The line must just be fit so that the distance of each point to a line is measured with respect to the y-axis. (Insert a simple plot here) --></p>
<p>Now, let’s go through the formal definition of a linear regression model. Let <span class="math inline">\(Y\)</span> be a dependent variable with measurements <span class="math inline">\(y_1 \ldots, y_n\)</span>, and let <span class="math inline">\(X_1, X_2, \ldots, X_k\)</span> be predictor variables with measurements <span class="math inline">\(x_{1i}, \ldots, x_{ki}\)</span> for all <span class="math inline">\(i = 1,\ldots,n\)</span> where <span class="math inline">\(i\)</span> refers to an individual measurement. Then, the regression equation is <span class="math display">\[
y_i = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \cdots + \beta_k x_{ki} + \varepsilon_i, \quad \varepsilon_i \sim N(0, \sigma^2), \quad i = 1,\ldots,n
\]</span> where we have the regression coefficients <span class="math inline">\(\beta_0, \beta_1, \ldots \beta_k\)</span> and the error variance <span class="math inline">\(\sigma^2\)</span>. The first parameter <span class="math inline">\(\beta_0\)</span> is called the intercept that models the conditional expectation of <span class="math inline">\(Y\)</span> when all the predictors have the value <span class="math inline">\(0\)</span>. From the regression equation, several assumptions become apparent. First, as the name of the model suggests, a linear relationship is assumed between the response and the predictors. Next, the variance <span class="math inline">\(\sigma^2\)</span> of the errors <span class="math inline">\(\varepsilon_i\)</span> is constant, and does not depend on the values of the predictors (homoscedasticity). The errors are also assumed independent. The predictor variables are assumed fixed and their values perfectly measured without error.</p>
<p>Let’s fit a linear regression model that predicts the final grade with the number of Moodle events of different types. To simplify the exposition, we will only use three types of Moodle events as predictors. We use the <code>lm()</code> function which has the same formula interface that we are already familiar with. First, we must define the dependent variable on the left-hand side of the formula, followed by the predictors on the right-hand side separated by a <code>+</code> sign. We must also supply the <code>data</code> argument, which tells the function where the actual values of the variables can be accessed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  Final_grade <span class="sc">~</span> Frequency.Applications <span class="sc">+</span> Frequency.Assignment <span class="sc">+</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>    Frequency.La_types,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> all_combined</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Final_grade ~ Frequency.Applications + Frequency.Assignment + 
    Frequency.La_types, data = all_combined)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.0382 -0.8872  0.3665  1.2372  3.4422 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             5.800211   0.405963  14.288  &lt; 2e-16 ***
Frequency.Applications  0.076516   0.022294   3.432 0.000811 ***
Frequency.Assignment   -0.005049   0.005734  -0.881 0.380225    
Frequency.La_types      0.088252   0.027314   3.231 0.001574 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.914 on 126 degrees of freedom
Multiple R-squared:  0.2559,    Adjusted R-squared:  0.2382 
F-statistic: 14.45 on 3 and 126 DF,  p-value: 3.798e-08</code></pre>
</div>
</div>
<p>The <code>summary()</code> function provides a compact overview of the model fit for <code>lm</code> objects. First, a summary of the residuals (i.e., the differences between the observed and predicted values) is provided under <code>Residuals</code>. Next, a summary of the regression coefficients <span class="math inline">\(\beta\)</span> is provided under <code>Coefficients</code>, including their estimates (<code>Estimate</code>), standard errors (<code>Std. Error</code>), test statistics for t-tests that test whether the coefficients are significantly different from zero (<code>t value</code>), p-values of the tests (<code>Pr(&gt;|t|)</code>) and statistical significance (indicated by the asterisks). For instance, we see that the number of group work events is statistically significant. The notation used for the significance levels of the tests is described following <code>Signif. codes</code>. Estimate of the square root of the error variance <span class="math inline">\(\sigma^2\)</span> is reported following <code>Residual standard error</code>. The two <code>R-squared</code> values are estimates of the proportion of variance of the data that is explained by the model. Finally, the <code>F-statistic</code> reports the results of ANOVA when applied with the same model formula that was used for the linear regression model.</p>
<p>The <code>report()</code> function provides a more comprehensive summary of the model fit and the regression coefficients:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a linear model (estimated using OLS) to predict Final_grade with
Frequency.Applications, Frequency.Assignment and Frequency.La_types (formula:
Final_grade ~ Frequency.Applications + Frequency.Assignment + Frequency.La_types).
The model explains a statistically significant and moderate proportion of variance
(R2 = 0.26, F(3, 126) = 14.45, p &lt; .001, adj. R2 = 0.24). The model's intercept,
corresponding to Frequency.Applications = 0, Frequency.Assignment = 0 and
Frequency.La_types = 0, is at 5.80 (95% CI [5.00, 6.60], t(126) = 14.29, p &lt; .001).
Within this model:

  - The effect of Frequency Applications is statistically significant and positive
(beta = 0.08, 95% CI [0.03, 0.12], t(126) = 3.43, p &lt; .001; Std. beta = 0.32, 95%
CI [0.13, 0.50])
  - The effect of Frequency Assignment is statistically non-significant and negative
(beta = -5.05e-03, 95% CI [-0.02, 6.30e-03], t(126) = -0.88, p = 0.380; Std. beta =
-0.08, 95% CI [-0.26, 0.10])
  - The effect of Frequency La types is statistically significant and positive (beta
= 0.09, 95% CI [0.03, 0.14], t(126) = 3.23, p = 0.002; Std. beta = 0.31, 95% CI
[0.12, 0.49])

Standardized parameters were obtained by fitting the model on a standardized
version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed
using a Wald t-distribution approximation.</code></pre>
</div>
</div>
<p>Again, the report output has condensed the information about the model fit into a format that can be read in a straightforward manner.</p>
<p>The assumption of normality of the residuals can be assessed with a quantile-quantile plot, or q-q plot for short. The residuals of the model fit can be accessed with the function <code>resid()</code>. The function <code>qqnorm()</code> draws the quantiles of the residuals against the quantiles of the normal distribution. The function <code>qqline()</code> adds a straight line through the plot that passes through the second and third quantiles, by default. Ideally, the residuals should fall on this line, and large deviations indicate that the normality assumption may not hold.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Draw the quantiles of the residuals and the theoretical quantiles</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(fit))</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Add a line through the theoretical quantiles</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">resid</span>(fit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch5-stats_files/figure-html/gradeqq-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>The vast majority of residuals fall nicely onto the line for our model. Besides the q-q plot, we can obtain more model diagnostics with the help of the <code>performance</code> <span class="citation" data-cites="performance">[<a href="#ref-performance" role="doc-biblioref">25</a>]</span> package. This package provides a wide array of tools to assess how well models fit to the data. The general-purpose function <code>check_model(</code> provides a visual overview of the model fit using several metrics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"performance"</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(fit, <span class="at">theme =</span> see<span class="sc">::</span><span class="fu">theme_lucid</span>(<span class="at">base_size =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ch5-stats_files/figure-html/lmperformance-1.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<p>The functions performs various tests related to the assumptions of the linear regression model. For example, the bottom right panel contains the same q-q plot that we previously constructed using the <code>qqnorm()</code> and <code>qqline()</code> functions. We refer the reader to the documentation of the <code>performance</code> package for more information on the remaining tests.</p>
</section>
<section id="logistic-regression" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="logistic-regression"><span class="header-section-number">6</span> Logistic regression</h2>
<p>Logistic regression is a similar tool to linear regression, but with a binary outcome instead of a continuous one. Instead of modeling the outcome variable directly, a linear model is constructed for the logarithmic odds of the probability of “success” for the binary outcome, e.g., obtaining a passing grade. There is also no explicit error term <span class="math inline">\(\varepsilon\)</span> in the model, as the uncertainty in the outcome is already captured by the success probability. Formally, the model is <span class="math display">\[
\mbox{logit}\left(P(y_i = 1)\right) = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \cdots + \beta_k x_{ki}, \quad i = 1,\ldots,n,
\]</span> where the logit-function is defined as <span class="math inline">\(\mbox{logit}(x) = \log(x/(1-x))\)</span>. Here, the logit-function serves as the so-called <em>link function</em> that connects the expected value of the response to the predictors.</p>
<p>We fit a logistic regression model where the outcome variable is the level of achievement (<code>AchievingGroup</code>) and the predictors are the Moodle event counts of each type. The logistic regression model is a <em>generalized linear model</em>: a class of models that extend the linear regression model and that can be fitted in R with the function <code>glm()</code>. The syntax of <code>glm()</code> is analogous to <code>lm()</code>, but we must also specify the distribution of the outcome and the link function via the <code>family</code> argument. We use the function <code>binomial()</code> and supply the argument <code>link = "logit"</code> to define that the model should be a logistic regression model (in this case the <code>link</code> argument is optional, as <code>"logit"</code> is the default value). Because <code>AchievingGroup</code> is a factor, we must first convert it into a binary response that attains values 1 and 0 (or <code>TRUE</code> and <code>FALSE</code>). We can do this within the formula via the <code>I()</code> function, so that we do not have to modify our data. When used in a formula, this function will first compute its argument expression when evaluated, so that the expression is not mistaken for a variable name in the data (that does not exist). We select the high achievers as the “success” category for the outcome.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>fit_logistic <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Use the I() function to construct a binary response in the formula</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">I</span>(AchievingGroup <span class="sc">==</span> <span class="st">"High achiever"</span>) <span class="sc">~</span> Frequency.Applications <span class="sc">+</span> </span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>    Frequency.Assignment <span class="sc">+</span> Frequency.La_types,</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> all_combined,</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Our response is binary, so we use the binomial family with logit link</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_logistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = I(AchievingGroup == "High achiever") ~ Frequency.Applications + 
    Frequency.Assignment + Frequency.La_types, family = binomial(link = "logit"), 
    data = all_combined)

Coefficients:
                       Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)            -0.66272    0.62914  -1.053  0.29217    
Frequency.Applications  0.30443    0.07778   3.914 9.07e-05 ***
Frequency.Assignment   -0.04477    0.01402  -3.193  0.00141 ** 
Frequency.La_types      0.12245    0.04710   2.600  0.00933 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 180.22  on 129  degrees of freedom
Residual deviance: 120.21  on 126  degrees of freedom
AIC: 128.21

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>The summary of a <code>glm()</code> function output is very similar to the output of a <code>lm()</code> summary. First, the <code>Call</code> is reported, which simply restates how the model was fitted. Next, <code>Coefficients</code> reports the estimates of the regression coefficients <span class="math inline">\(\beta\)</span>, and their standard errors and statistical significance. Lastly, two deviance measures and their degrees of freedom are reported. The null deviance is twice the difference between the log-likelihood of the saturated model and the null model, and residual deviance is twice the difference between the saturated model and the model that was fitted. In simpler terms, the saturated model is a perfect model in a sense that there is a parameter for each observation. Conversely, the null model only has the intercept term. The deviance serves as a generalization of the residual sum of squares of the linear regression model, and it can be used to assess the quality of the model fit <span class="citation" data-cites="dobson1990">[<a href="#ref-dobson1990" role="doc-biblioref">26</a>]</span>.</p>
<p>The <code>report()</code> function is applicable to models fitted with <code>glm()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(fit_logistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a logistic model (estimated using ML) to predict AchievingGroup with
Frequency.Applications, Frequency.Assignment and Frequency.La_types (formula:
I(AchievingGroup == "High achiever") ~ Frequency.Applications +
Frequency.Assignment + Frequency.La_types). The model's explanatory power is
substantial (Tjur's R2 = 0.38). The model's intercept, corresponding to
Frequency.Applications = 0, Frequency.Assignment = 0 and Frequency.La_types = 0, is
at -0.66 (95% CI [-1.94, 0.56], p = 0.292). Within this model:

  - The effect of Frequency Applications is statistically significant and positive
(beta = 0.30, 95% CI [0.17, 0.48], p &lt; .001; Std. beta = 1.62e-14, 95% CI
[-73784.14, 73784.14])
  - The effect of Frequency Assignment is statistically significant and negative
(beta = -0.04, 95% CI [-0.07, -0.02], p = 0.001; Std. beta = -9.05e-16, 95% CI
[-71374.92, 71374.92])
  - The effect of Frequency La types is statistically significant and positive (beta
= 0.12, 95% CI [0.04, 0.22], p = 0.009; Std. beta = -2.52e-17, 95% CI [-75547.24,
75547.24])

Standardized parameters were obtained by fitting the model on a standardized
version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed
using a Wald z-distribution approximation.</code></pre>
</div>
</div>
<p>The output describes succinctly the model that was fitted, and the effects of the predictors on the response. The <code>performance</code> package is also applicable to models fitted with the <code>glm()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(fit_logistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ch5-stats_files/figure-html/logisticperformance-1.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<p>We note that a different set of diagnostic checks is carried out for the logistic regression model compared to the linear regression model. For example, there is no assumption of homoscedasticity of variance as there is no explicit error term <span class="math inline">\(\varepsilon\)</span> in the model. Again, we refer the reader to the documentation of the <code>performance</code> package for more details on these checks.</p>
</section>
<section id="conclusion" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">7</span> Conclusion</h2>
<p>Basic statistics are an essential component of learning analytics. Learning analytics involves the collection, analysis, and interpretation of data related to the learning process, and statistical methods are used to identify patterns and trends in this data and to draw conclusions. Basic descriptive statistics such as measures of central tendency, variability and correlation are crucial for analyzing, interpreting, and visualizing data. Understanding these concepts is important for anyone involved in conducting research with quantitative data in the field of learning analytics. Moreover, mastery of basic statistics can facilitate the comprehension of more advanced statistical methods that are commonly used in learning analytics, such as logistic regression and cluster analysis. <a href="../ch10-sequence-analysis/ch10-seq.html#tbl-summary">Table&nbsp;<span>10.1</span></a> contains a summary of the statistical tests that were introduced in this chapter.</p>
<div id="tbl-summary" class="anchored">
<table class="table">
<caption>Table&nbsp;1<strong>.</strong> Summary of the statistical tests, their null hypotheses, and the number of groups they compare simultaneously.</caption>
<colgroup>
<col style="width: 27%">
<col style="width: 23%">
<col style="width: 25%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Null Hypothesis</th>
<th>Groups</th>
<th>R function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Student’s t-test</td>
<td>Equal means</td>
<td>One, two or paired</td>
<td><code>t.test()</code></td>
</tr>
<tr class="even">
<td>Chi-squared test</td>
<td>Independence</td>
<td>One</td>
<td><code>chisq.test()</code></td>
</tr>
<tr class="odd">
<td>Fisher’s test</td>
<td>Independence</td>
<td>One</td>
<td><code>fisher.test()</code></td>
</tr>
<tr class="even">
<td>ANOVA</td>
<td>Equal means</td>
<td>Two or more</td>
<td><code>aov()</code></td>
</tr>
<tr class="odd">
<td>Kruskal-Wallis test</td>
<td>Equal medians</td>
<td>Two or more</td>
<td><code>kruskal.test()</code></td>
</tr>
<tr class="even">
<td>Levene’s test</td>
<td>Homoscedasticity</td>
<td>Two or more</td>
<td><code>leveneTest()</code></td>
</tr>
<tr class="odd">
<td>Shapiro-Wilk test</td>
<td>Normality</td>
<td>One</td>
<td><code>shapiro.test()</code></td>
</tr>
</tbody>
</table>
</div>
<p>We emphasize that when using any statistical test or a statistical model, it is important to keep the various assumptions related to the chosen method in mind, and to assess them beforehand whenever possible. If the assumptions are violated, the results of the method may not be reliable, and thus suitable alternatives should be considered.</p>
</section>
<section id="further-reading" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="further-reading"><span class="header-section-number">8</span> Further reading</h2>
<p>This chapter scratched the surface of the full features of packages such as <code>correlation</code>, <code>report</code> and <code>performance</code> that can streamline the statistical analysis and reporting process. We refer the reader to the documentation of these packages to gain a more thorough understanding of their features. These packages are part of a package collection called <em>easystats</em> <span class="citation" data-cites="easystats">[<a href="#ref-easystats" role="doc-biblioref">27</a>]</span> (). There are several other packages in this collection that were not discussed in this chapter that can be useful for R users working with learning analytics. The book “Learning Statistics with R” by Danielle Navarro is freely available online and provides a comprehensive introduction to statistics using R (). For a general introductory text to statistical methods and inference, see e.g., <span class="citation" data-cites="sheldon2017">[<a href="#ref-sheldon2017" role="doc-biblioref">2</a>]</span>.</p>


</section>
<section id="bibliography" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body" role="doc-bibliography">
<div id="ref-niiniluoto1980" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Niiniluoto I (1980) Johdatus tieteenfilosofiaan: Käsitteen- ja teorianmuodostus. Otava</div>
</div>
<div id="ref-sheldon2017" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Ross SM (2010) Introductory statistics, 4th ed. Elsevier</div>
</div>
<div id="ref-lehmann2022" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Lehmann EL, Romano JP (2022) <a href="https://doi.org/10.1007/978-3-030-70578-7">Testing statistical hypotheses</a>, 4th ed. Springer Cham</div>
</div>
<div id="ref-LAbook6" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">López-Pernas S, Misiejuk K, Tikka S, Saqr M, Kopra J, Heinäniemi M (2024) Visualizing and reporting educational data with <span>R</span>. In: Saqr M, López-Pernas S (eds) Learning analytics methods and tutorials: A practical guide using <span>R</span>. Springer</div>
</div>
<div id="ref-LAbook2" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">López-Pernas S, Saqr M, Conde J, Del Rio L (2024) A broad collection of datasets for educational research training and application. In: Saqr M, López-Pernas S (eds) Learning analytics methods and tutorials: A practical guide using <span>R</span>. Springer, pp in–press</div>
</div>
<div id="ref-rio" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Chan C, Chan GC, Leeper TJ, Becker J (2021) <span class="nocase">rio</span>: A swiss-army knife for data file <span>I/O</span></div>
</div>
<div id="ref-dplyr" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">7. </div><div class="csl-right-inline">Wickham H, François R, Henry L, Müller K, Vaughan D (2023) <a href="https://CRAN.R-project.org/package=dplyr"><span class="nocase">dplyr</span>: A grammar of data manipulation</a></div>
</div>
<div id="ref-tidyr" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">8. </div><div class="csl-right-inline">Wickham H, Vaughan D, Girlich M (2023) <a href="https://CRAN.R-project.org/package=tidyr"><span class="nocase">tidyr</span>: Tidy messy data</a></div>
</div>
<div id="ref-LAbook4" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">9. </div><div class="csl-right-inline">Kopra J, Tikka S, Heinäniemi M, López-Pernas S, Saqr M (2024) An <span>R</span> approach to data cleaning and wrangling for education research. In: Saqr M, López-Pernas S (eds) Learning analytics methods and tutorials: A practical guide using <span>R</span>. Springer</div>
</div>
<div id="ref-report" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">10. </div><div class="csl-right-inline">Makowski D, Lüdecke D, Patil I, Thériault R, Ben-Shachar MS, Wiernik BM (2023) <a href="https://easystats.github.io/report/">Automated results reporting as a practical tool to improve reproducibility and methodological best practices adoption</a>. CRAN</div>
</div>
<div id="ref-student" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">11. </div><div class="csl-right-inline">Gosset W“Student”S (1908) The probable error of a mean. Biometrika 6:1–25. https://doi.org/<a href="https://doi.org/10.1093/biomet/6.1.1">10.1093/biomet/6.1.1</a></div>
</div>
<div id="ref-welch" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">12. </div><div class="csl-right-inline">Welch BL (1947) The generalization of "student’s" problem when several different population variances are involved. Biometrika 34:28–35. https://doi.org/<a href="https://doi.org/10.1093/biomet/34.1-2.28">10.1093/biomet/34.1-2.28</a></div>
</div>
<div id="ref-ellis2010" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">13. </div><div class="csl-right-inline">Ellis PD (2010) The essential guide to effect sizes: Statistical power, meta-analysis, and the interpretation of research results. Cambridge University Press</div>
</div>
<div id="ref-cohen1988" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">14. </div><div class="csl-right-inline">Cohen J (1988) Statistical power analysis for the behavioral sciences. Routledge</div>
</div>
<div id="ref-chisq" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">15. </div><div class="csl-right-inline">Pearson K (1900) On the criterion that a given system of deviations from the probable in the case of a correlated system of variables is such that it can be reasonably supposed to have arisen from random sampling. Philosophical Magazine Series 5 50:157–175. https://doi.org/<a href="https://doi.org/10.1080/14786440009463897">10.1080/14786440009463897</a></div>
</div>
<div id="ref-fishertest" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">16. </div><div class="csl-right-inline">Fisher RA (1922) On the interpretation of <span class="math inline">\(\chi^2\)</span> from contingency tables, and the calculation of <span>P</span>. Journal of the Royal Statistical Society 85:87–94</div>
</div>
<div id="ref-anova" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">17. </div><div class="csl-right-inline">Fisher RA (1921) On the <span>“probable error”</span> of a coefficient of correlation deduced from a small sample. Metron 1:3–32</div>
</div>
<div id="ref-kruskal" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">18. </div><div class="csl-right-inline">Kruskal WH, Wallis WA (1952) Use of ranks in one-criterion variance analysis. Journal of the American Statistical Association 47:583–621. https://doi.org/<a href="https://doi.org/10.1080/01621459.1952.10483441">10.1080/01621459.1952.10483441</a></div>
</div>
<div id="ref-levene" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">19. </div><div class="csl-right-inline">Levene H (1960) Robust tests for equality of variances. In: Olkin I, Hotelling H, others (eds) Contributions to probability and statistics: Essays in honor of harold hotelling. Stanford University Press, pp 278–292</div>
</div>
<div id="ref-bartlett" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">20. </div><div class="csl-right-inline">Bartlett MS (1937) Properties of sufficiency and statistical tests. Proceedings of the Royal Statistical Society, Series A 160:268–282</div>
</div>
<div id="ref-shapirowilk" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">21. </div><div class="csl-right-inline">Shapiro SS, Wilk MB (1965) An analysis of variance test for normality (complete samples). Biometrika 52:591–611. https://doi.org/<a href="https://doi.org/10.1093/biomet/52.3-4.591">10.1093/biomet/52.3-4.591</a></div>
</div>
<div id="ref-broom" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">22. </div><div class="csl-right-inline">Robinson D, Hayes A, Couch S (2023) <a href="https://CRAN.R-project.org/package=broom"><span class="nocase">broom</span>: Convert statistical objects into tidy tibbles</a></div>
</div>
<div id="ref-correlation" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">23. </div><div class="csl-right-inline">Makowski D, Ben-Shachar MS, Patil I, Lüdecke D (2020) Methods and algorithms for correlation analysis in <span>R</span>. Journal of Open Source Software 5:2306. https://doi.org/<a href="https://doi.org/10.21105/joss.02306">10.21105/joss.02306</a></div>
</div>
<div id="ref-see" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">24. </div><div class="csl-right-inline">Lüdecke D, Patil I, Ben-Shachar MS, Wiernik BM, Waggoner P, Makowski D (2021) <span class="nocase">see</span>: An <span>R</span> package for visualizing statistical models. Journal of Open Source Software 6:3393. https://doi.org/<a href="https://doi.org/10.21105/joss.03393">10.21105/joss.03393</a></div>
</div>
<div id="ref-performance" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">25. </div><div class="csl-right-inline">Lüdecke D, Ben-Shachar MS, Patil I, Waggoner P, Makowski D (2021) <span class="nocase">performance</span>: An <span>R</span> package for assessment, comparison and testing of statistical models. Journal of Open Source Software 6:3139. https://doi.org/<a href="https://doi.org/10.21105/joss.03139">10.21105/joss.03139</a></div>
</div>
<div id="ref-dobson1990" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">26. </div><div class="csl-right-inline">Dobson AJ (1990) An introduction to generalized linear models. Chapman; Hall</div>
</div>
<div id="ref-easystats" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">27. </div><div class="csl-right-inline">Lüdecke D, Ben-Shachar MS, Patil I, Wiernik BM, Bacher E, Thériault R, Makowski D (2022) <a href="https://easystats.github.io/easystats/"><span class="nocase">easystats</span>: Framework for easy statistical modeling, visualization, and reporting</a>. CRAN</div>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/ch04-data-cleaning/ch4-datacleaning.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data cleaning</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/ch06-data-visualization/ch6-viz.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data visualization</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
      <div class="nav-footer-center"><div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
  </div>
</footer>
<script>
  document.querySelector(".quarto-title").innerHTML =  '<div class="badge bs-warning bg-warning text-dark" style="float:right;">Pre-print</div>' +  document.querySelector(".quarto-title").innerHTML
  var keywords = document.querySelector('meta[name="keywords"]')
  if (keywords && keywords.content) {
    document.getElementById("title-block-header").innerHTML = document.getElementById("title-block-header").innerHTML + 
      '<div class="abstract"><div class="abstract-title">Keywords</div><div class="quarto-title-meta-contents"><p>'+
      keywords.content +
      '</p></div></div>'
  }
</script>



</body></html>