<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mohammed Saqr">
<meta name="author" content="Sonsoles López-Pernas">
<meta name="author" content="Miguel Ángel Conde">
<meta name="author" content="Ángel Hernández-García">
<meta name="keywords" content="learning analytics, social network analysis, centrality measures, tutorial">

<title>Learning analytics methods and tutorials - 15&nbsp; Social Network Analysis: A primer, a guide and a tutorial in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/ch16-community/ch16-comm.html" rel="next">
<link href="../../chapters/ch14-process-mining/ch14-process.html" rel="prev">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  });
});
</script> 
  


<meta name="citation_title" content="[15]{.chapter-number}&nbsp; [Social Network Analysis: A primer, a guide and a tutorial in R]{.chapter-title}">
<meta name="citation_abstract" content="This chapter introduces the concept and methods of social network analysis (SNA) with a detailed guide to analysis with real world data using the R programming language. The chapter first introduces the basic concepts and types of networks. Then the chapter goes through a detailed step by step analysis of networks, computation of graph level measures as well as centralities with a concise interpretation in a collaborative environment. The chapter concludes with a discussion of network analysis, next steps as well as a list of further readings.">
<meta name="citation_keywords" content="learning analytics, social network analysis, centrality measures, tutorial">
<meta name="citation_author" content="Mohammed Saqr">
<meta name="citation_author" content="Sonsoles López-Pernas">
<meta name="citation_author" content="Miguel Ángel Conde">
<meta name="citation_author" content="Ángel Hernández-García">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=The diffusion of microfinance;,citation_author=Abhijit Banerjee;,citation_author=Arun G. Chandrasekhar;,citation_author=Esther Duflo;,citation_author=Matthew O. Jackson;,citation_publication_date=2013-07;,citation_cover_date=2013-07;,citation_year=2013;,citation_fulltext_html_url=http://dx.doi.org/10.1126/science.1236498;,citation_issue=6144;,citation_doi=10.1126/science.1236498;,citation_issn=0036-8075;,citation_volume=341;,citation_journal_title=Science;">
<meta name="citation_reference" content="citation_title=Network science;,citation_author=Albert-László Barabási;,citation_publication_date=2013-03;,citation_cover_date=2013-03;,citation_year=2013;,citation_fulltext_html_url=http://dx.doi.org/10.1098/rsta.2012.0375;,citation_issue=1987;,citation_doi=10.1098/rsta.2012.0375;,citation_issn=1364-503X;,citation_volume=371;,citation_journal_title=Philosophical transactions. Series A, Mathematical, physical, and engineering sciences;">
<meta name="citation_reference" content="citation_title=Reciprocity, transitivity, and the mysterious three-cycle;,citation_author=Per Block;,citation_publication_date=2015-01;,citation_cover_date=2015-01;,citation_year=2015;,citation_fulltext_html_url=https://www.sciencedirect.com/science/article/pii/S0378873314000586;,citation_doi=10.1016/j.socnet.2014.10.005;,citation_issn=0378-8733;,citation_volume=40;,citation_journal_title=Social networks;">
<meta name="citation_reference" content="citation_title=Centrality: Concepts and measures;,citation_author=Stephen P. Borgatti;,citation_author=Daniel J. Brass;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_inbook_title=Social networks at work;">
<meta name="citation_reference" content="citation_title=Network analysis in the social sciences;,citation_author=Stephen P. Borgatti;,citation_author=Ajay Mahra;,citation_author=Daniel J. Brass;,citation_author=Guiseppe Labianca;,citation_publication_date=2009-02;,citation_cover_date=2009-02;,citation_year=2009;,citation_fulltext_html_url=http://www.sciencemag.org/cgi/doi/10.1126/science.1165821;,citation_issue=5916;,citation_doi=10.1126/science.1165821;,citation_issn=0036-8075;,citation_volume=323;,citation_journal_title=Science;">
<meta name="citation_reference" content="citation_title=Social networks and performance in distributed learning communities;,citation_author=Rita Cadima;,citation_author=Jordi Ojeda;,citation_author=Josep M. Monguet;,citation_publication_date=2012;,citation_cover_date=2012;,citation_year=2012;,citation_fulltext_html_url=https://pdfs.semanticscholar.org/45fd/589cc4732abbd95b3f1af7ac61640a52a222.pdf;,citation_issue=4;,citation_issn=1176-3647;,citation_volume=15;,citation_journal_title=Educational Technology &amp;amp;amp; Society;">
<meta name="citation_reference" content="citation_title=Social network analysis in e-learning environments: A preliminary systematic review;,citation_author=Karina L. Cela;,citation_author=Miguel Ángel Sicilia;,citation_author=Salvador Sánchez;,citation_publication_date=2015-03;,citation_cover_date=2015-03;,citation_year=2015;,citation_fulltext_html_url=http://link.springer.com/10.1007/s10648-014-9276-0;,citation_issue=1;,citation_doi=10.1007/s10648-014-9276-0;,citation_issn=1040-726X;,citation_volume=27;,citation_journal_title=Educational psychology review;,citation_publisher=Springer Science; Business Media LLC;">
<meta name="citation_reference" content="citation_title=Social networks, communication styles, and learning performance in a CSCL community;,citation_author=Hichang Cho;,citation_author=Geri Gay;,citation_author=Barry Davidson;,citation_author=Anthony Ingraffea;,citation_publication_date=2007-09;,citation_cover_date=2007-09;,citation_year=2007;,citation_fulltext_html_url=https://www.scopus.com/inward/record.uri?eid=2-s2.0-34248998867&amp;amp;amp;doi=10.1016%2Fj.compedu.2005.07.003&amp;partnerID=40&amp;md5=5c5cd85d1a8dd004346418aca61d0747;,citation_issue=2;,citation_doi=10.1016/j.compedu.2005.07.003;,citation_issn=0360-1315;,citation_volume=49;,citation_journal_title=Computers and Education;,citation_publisher=Pergamon;">
<meta name="citation_reference" content="citation_title=Statistical network analysis with igraph;,citation_author=Gábor Csárdi;,citation_author=Tamás Nepusz;,citation_author=Edoardo M. Airoldi;,citation_publication_date=2016;,citation_cover_date=2016;,citation_year=2016;,citation_publisher=Springer Berlin;">
<meta name="citation_reference" content="citation_title=The igraph software package for complex network research;,citation_author=Gabor Csardi;,citation_author=Tamas Nepusz;,citation_author=undefined Others;,citation_publication_date=2006;,citation_cover_date=2006;,citation_year=2006;,citation_fulltext_html_url=https://www.researchgate.net/profile/Gabor-Csardi/publication/221995787_The_Igraph_Software_Package_for_Complex_Network_Research/links/0c96051d301a30f265000000/The-Igraph-Software-Package-for-Complex-Network-Research.pdf;,citation_issue=5;,citation_volume=1695;,citation_journal_title=InterJournal, complex systems;">
<meta name="citation_reference" content="citation_title=A review of methodological applications of social network analysis in computer-supported collaborative learning;,citation_author=Marielle Dado;,citation_author=Daniel Bodemer;,citation_publication_date=2017;,citation_cover_date=2017;,citation_year=2017;,citation_fulltext_html_url=https://doi.org/10.1016/j.edurev.2017.08.005;,citation_doi=10.1016/j.edurev.2017.08.005;,citation_volume=22;,citation_journal_title=Educational Research Review;,citation_publisher=Elsevier Ltd;">
<meta name="citation_reference" content="citation_title=Social network analysis of a gamified e-learning course: Small-world phenomenon and network metrics as predictors of academic performance;,citation_author=Luis De-Marcos;,citation_author=Eva Garciá-López;,citation_author=Antonio Garciá-Cabot;,citation_author=J-A José Amelio Medina-Merodio;,citation_author=Adrián Domínguez;,citation_author=José Javier J-J Martínez-Herraíz;,citation_author=Teresa Diez-Folledo;,citation_publication_date=2016;,citation_cover_date=2016;,citation_year=2016;,citation_fulltext_html_url=http://dx.doi.org/10.1016/j.chb.2016.02.052;,citation_issue=PG-312-321;,citation_doi=10.1016/j.chb.2016.02.052;,citation_issn=0747-5632;,citation_volume=60;,citation_journal_title=Computers in human behavior;,citation_publisher=Elsevier Ltd;">
<meta name="citation_reference" content="citation_title=From social ties to network processes: Do tie definitions matter?;,citation_author=Ed Fincham;,citation_author=Dragan Gašević;,citation_author=Abelardo Pardo;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_fulltext_html_url=http://dx.doi.org/10.18608/jla.2018.52.2;,citation_issue=2;,citation_doi=10.18608/jla.2018.52.2;,citation_volume=5;,citation_journal_title=Journal of Learning Analytics;">
<meta name="citation_reference" content="citation_title=Centrality in social networks conceptual clarification;,citation_author=Linton C. Freeman;,citation_publication_date=1978-01;,citation_cover_date=1978-01;,citation_year=1978;,citation_fulltext_html_url=http://linkinghub.elsevier.com/retrieve/pii/0378873378900217;,citation_issue=3;,citation_doi=10.1016/0378-8733(78)90021-7;,citation_issn=0378-8733;,citation_volume=1;,citation_journal_title=Social networks;">
<meta name="citation_reference" content="citation_title=Data mining and social network analysis in the educational field: An application for non-expert users;,citation_author=D. García-Saiz;,citation_author=C. Palazuelos;,citation_author=M. Zorrilla;,citation_publication_date=2014;,citation_cover_date=2014;,citation_year=2014;,citation_fulltext_html_url=https://www.scopus.com/inward/record.uri?eid=2-s2.0-84958542823&amp;amp;amp;doi=10.1007%2F978-3-319-02738-8_15&amp;partnerID=40&amp;md5=ff793d454e0896d85526c5bdbc5e36d4 NS -;,citation_issue=PG-411-439;,citation_volume=524;,citation_journal_title=Stud. Comput. Intell.;,citation_publisher=Springer Verlag;">
<meta name="citation_reference" content="citation_title=SENS: Network analytics to combine social and cognitive perspectives of collaborative learning;,citation_author=Dragan Gašević;,citation_author=Srećko Joksimović;,citation_author=Brendan R. Eagan;,citation_author=David Williamson Shaffer;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_fulltext_html_url=https://doi.org/10.1016/j.chb.2018.07.003;,citation_issue=PG-562-577;,citation_doi=10.1016/j.chb.2018.07.003;,citation_issn=0747-5632;,citation_volume=92;,citation_journal_title=Computers in human behavior;,citation_publisher=Elsevier Ltd;">
<meta name="citation_reference" content="citation_title=Community detection in r;,citation_author=Ángel Hernández-García;,citation_author=Carlos Cuenca-Enrique;,citation_author=Adrienne Traxler;,citation_author=Sonsoles López-Pernas;,citation_author=Miguel Ángel Conde;,citation_author=Mohammed Saqr;,citation_editor=Mohammed Saqr;,citation_editor=Sonsoles López-Pernas;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_inbook_title=Learning analytics methods and tutorials: A practical guide using r;">
<meta name="citation_reference" content="citation_title=Applying social learning analytics to message boards in online distance learning: A case study;,citation_author=Ángel Hernández-García;,citation_author=Inés González-González;,citation_author=Ana Isabel Jiménez-Zarco;,citation_author=Julián Chaparro-Peláez;,citation_publication_date=2015-06;,citation_cover_date=2015-06;,citation_year=2015;,citation_fulltext_html_url=https://www.scopus.com/inward/record.uri?eid=2-s2.0-84924037151&amp;amp;amp;doi=10.1016%2Fj.chb.2014.10.038&amp;partnerID=40&amp;md5=0056f328a6c8670608784062443b5f62 NS -;,citation_issue=PG-68-80;,citation_doi=10.1016/j.chb.2014.10.038;,citation_issn=0747-5632;,citation_volume=47;,citation_journal_title=Computers in human behavior;,citation_publisher=Elsevier Ltd;">
<meta name="citation_reference" content="citation_title=CentiServer: A comprehensive resource, web-based application and r package for centrality analysis;,citation_author=Mahdi Jalili;,citation_author=Ali Salehzadeh-Yazdi;,citation_author=Yazdan Asgari;,citation_author=Seyed Shahriar Arab;,citation_author=Marjan Yaghmaie;,citation_author=Ardeshir Ghavamzadeh;,citation_author=Kamran Alimoghaddam;,citation_publication_date=2015-11;,citation_cover_date=2015-11;,citation_year=2015;,citation_fulltext_html_url=https://dx.plos.org/10.1371/journal.pone.0143111;,citation_issue=11;,citation_doi=10.1371/journal.pone.0143111;,citation_volume=10;,citation_journal_title=PloS one;">
<meta name="citation_reference" content="citation_title=Three interaction patterns on asynchronous online discussion behaviours: A methodological comparison;,citation_author=I. Jo;,citation_author=Y. Park;,citation_author=H. Lee;,citation_publication_date=2017;,citation_cover_date=2017;,citation_year=2017;,citation_fulltext_html_url=http://doi.wiley.com/10.1111/jcal.12168;,citation_issue=2;,citation_doi=10.1111/jcal.12168;,citation_issn=1365-2729;,citation_volume=33;,citation_journal_title=Journal of Computer Assisted Learning;,citation_publisher=Blackwell Publishing Ltd;">
<meta name="citation_reference" content="citation_title=Translating network position into performance: Importance of centrality in different network configurations;,citation_author=Srećko Joksimovic;,citation_author=Areti Manataki;,citation_author=Dragan Gaševic;,citation_author=Shane Dawson;,citation_author=Vitomir Kovanovic;,citation_author=Inés Friss De Kereki;,citation_publication_date=2016;,citation_cover_date=2016;,citation_year=2016;,citation_fulltext_html_url=http://dx.doi.org/10.1145/2883851.2883928;,citation_issue=PG-314-323;,citation_doi=10.1145/2883851.2883928;,citation_volume=25-29-Apri;,citation_journal_title=ACM International Conference Proceeding Series;,citation_publisher=Association for Computing Machinery;">
<meta name="citation_reference" content="citation_title=Diffusion centrality in social networks;,citation_author=Chanhyun Kang;,citation_author=Cristian Molinaro;,citation_author=Sarit Kraus;,citation_author=Yuval Shavitt;,citation_author=V. S. Subrahmanian;,citation_publication_date=2012-08;,citation_cover_date=2012-08;,citation_year=2012;,citation_fulltext_html_url=http://dx.doi.org/10.1109/ASONAM.2012.95;,citation_doi=10.1109/ASONAM.2012.95;,citation_conference_title=2012 IEEE/ACM international conference on advances in social networks analysis and mining;">
<meta name="citation_reference" content="citation_title=Identification of influential spreaders in complex networks;,citation_author=Maksim Kitsak;,citation_author=Lazaros K. Gallos;,citation_author=Shlomo Havlin;,citation_author=Fredrik Liljeros;,citation_author=Lev Muchnik;,citation_author=H. Eugene Stanley;,citation_author=Hernán A. Makse;,citation_publication_date=2010-08;,citation_cover_date=2010-08;,citation_year=2010;,citation_fulltext_html_url=https://www.nature.com/articles/nphys1746;,citation_issue=11;,citation_doi=10.1038/nphys1746;,citation_issn=1745-2473;,citation_volume=6;,citation_journal_title=Nature physics;,citation_publisher=Nature Publishing Group;">
<meta name="citation_reference" content="citation_title=Authoritative sources in a hyperlinked environment;,citation_author=Jon M. Kleinberg;,citation_publication_date=1999-09;,citation_cover_date=1999-09;,citation_year=1999;,citation_fulltext_html_url=https://doi.org/10.1145/324133.324140;,citation_issue=5;,citation_doi=10.1145/324133.324140;,citation_issn=0004-5411;,citation_volume=46;,citation_journal_title=Journal of the ACM;,citation_publisher=Association for Computing Machinery;">
<meta name="citation_reference" content="citation_title=Statistical analysis of network data with r;,citation_author=Eric D. Kolaczyk;,citation_author=Gábor Csárdi;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_fulltext_html_url=https://link.springer.com/book/10.1007/978-3-030-44129-6;,citation_doi=10.1007/978-3-030-44129-6;">
<meta name="citation_reference" content="citation_title=Ranking in evolving complex networks;,citation_author=Hao Liao;,citation_author=Manuel Sebastian Mariani;,citation_author=Matúš Medo;,citation_author=Yi-Cheng Zhang;,citation_author=Ming-Yang Zhou;,citation_publication_date=2017-05;,citation_cover_date=2017-05;,citation_year=2017;,citation_fulltext_html_url=http://www.sciencedirect.com/science/article/pii/S0370157317300935;,citation_doi=10.1016/j.physrep.2017.05.001;,citation_issn=0370-1573;,citation_volume=689;,citation_journal_title=Physics reports;">
<meta name="citation_reference" content="citation_title=Effects of proactive personality and social centrality on learning performance in SPOCs;,citation_author=Sannyuya Liu;,citation_author=Huanyou Chai;,citation_author=Zhi Liu;,citation_author=Niels Pinkwart;,citation_author=Xue Han;,citation_author=Tianhui Hu;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_fulltext_html_url=https://www.scopus.com/inward/record.uri?eid=2-s2.0-85067103958&amp;amp;amp;partnerID=40&amp;md5=6c51ff3a48be2a3c89bae517da9e521f NS -;,citation_issue=PG-481-487;,citation_doi=10.5220/0007756604810487;,citation_volume=2;,citation_journal_title=CSEDU 2019 - Proceedings of the 11th International Conference on Computer Supported Education;,citation_publisher=SciTePress;">
<meta name="citation_reference" content="citation_title=Social network characteristics of learners in a course forum and their relationship to learning outcomes;,citation_author=Zhi Liu;,citation_author=Lingyun Kang;,citation_author=Monika Domanska;,citation_author=Sannyuya Liu;,citation_author=Jianwen Sun;,citation_author=Changli Fang;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_fulltext_html_url=http://dx.doi.org/10.5220/0006647600150021;,citation_doi=10.5220/0006647600150021;,citation_isbn=9789897582912;,citation_volume=1;,citation_conference_title=CSEDU 2018 - proceedings of the 10th international conference on computer supported education;,citation_conference=SciTePress;">
<meta name="citation_reference" content="citation_title=Investigate the relationship between learners’ social characteristics and academic achievements;,citation_author=Zhi Liu;,citation_author=Lingyun Kang;,citation_author=Zhu Su;,citation_author=Sannyuya Liu;,citation_author=Jianwen Sun;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_fulltext_html_url=https://www.scopus.com/inward/record.uri?eid=2-s2.0-85059436199&amp;amp;amp;doi=10.1088%2F1742-6596%2F1113%2F1%2F012021&amp;partnerID=40&amp;md5=70314ea0433f7c57e1b24ffc42bf814d NS -;,citation_doi=10.1088/1742-6596/1113/1/012021;,citation_issn=1742-6596;,citation_volume=1113;,citation_conference_title=Journal of physics: Conference series;,citation_conference=Institute of Physics Publishing;">
<meta name="citation_reference" content="citation_title=Scientometrics: A concise introduction and a detailed methodology for mapping the scientific field of computing education research;,citation_author=Sonsoles López-Pernas;,citation_author=Mohammed Saqr;,citation_author=Mikko Apiola;,citation_editor=Mikko Apiola;,citation_editor=Sonsoles López-Pernas;,citation_editor=Mohammed Saqr;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://doi.org/10.1007/978-3-031-25336-2_5;,citation_doi=10.1007/978-3-031-25336-2_5;,citation_isbn=9783031253362;,citation_inbook_title=Past, present and future of computing education research : A global perspective;">
<meta name="citation_reference" content="citation_title=A broad collection of datasets for educational research training and application;,citation_author=Sonsoles López-Pernas;,citation_author=Mohammed Saqr;,citation_author=Laura Del Rio;,citation_editor=Mohammed Saqr;,citation_editor=Sonsoles López-Pernas;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_inbook_title=Learning analytics methods and tutorials: A practical guide using r;">
<meta name="citation_reference" content="citation_title=DESPRO: A method based on roles to provide collaboration analysis support adapted to the participants in CSCL situations;,citation_author=José-Antonio Marcos-García;,citation_author=Alejandra Martínez-Monés;,citation_author=Yannis Dimitriadis;,citation_publication_date=2015-03;,citation_cover_date=2015-03;,citation_year=2015;,citation_fulltext_html_url=https://www.sciencedirect.com/science/article/pii/S0360131514002474;,citation_doi=10.1016/j.compedu.2014.10.027;,citation_issn=0360-1315;,citation_volume=82;,citation_journal_title=Computers &amp;amp;amp; education;">
<meta name="citation_reference" content="citation_title=Static and dynamic network visualization with r;,citation_author=Katya Ognyanova;,citation_publication_date=2023-06;,citation_cover_date=2023-06;,citation_year=2023;,citation_fulltext_html_url=https://kateto.net/network-visualization;,citation_journal_title=Katya Ognyanova;">
<meta name="citation_reference" content="citation_title=Node centrality in weighted networks: Generalizing degree and shortest paths;,citation_author=Tore Opsahl;,citation_author=Filip Agneessens;,citation_author=John Skvoretz;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;,citation_fulltext_html_url=http://dx.doi.org/10.1016/j.socnet.2010.03.006;,citation_issue=3;,citation_doi=10.1016/j.socnet.2010.03.006;,citation_issn=0378-8733;,citation_volume=32;,citation_journal_title=Social networks;,citation_publisher=Elsevier B.V.;">
<meta name="citation_reference" content="citation_title=Twittermania: Understanding how social media technologies impact engagement and academic performance of a new generation of learners;,citation_author=Babajide James Osatuyi;,citation_author=Katia Passerini;,citation_publication_date=2016;,citation_cover_date=2016;,citation_year=2016;,citation_fulltext_html_url=https://www.scopus.com/inward/record.uri?eid=2-s2.0-85006816496&amp;amp;amp;partnerID=40&amp;md5=50481d9ea30ad0b5cb6116540e0b3c42;,citation_issue=1 PG-509–528;,citation_volume=39;,citation_journal_title=Commun. Assoc. Info. Syst.;,citation_publisher=Association for Information Systems;">
<meta name="citation_reference" content="citation_title=Recommendations for network research in learning analytics: To open a conversation;,citation_author=Oleksandra Poquet;,citation_author=Mohammed Saqr;,citation_author=Bodong Chen;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_conference_title=Proceedings of the NetSciLA21 workshop;">
<meta name="citation_reference" content="citation_title=Analysing the correlation between social network analysis measures and performance of students in social network-based engineering education;,citation_author=Goran Putnik;,citation_author=Eric Costa;,citation_author=Cátia Alves;,citation_author=Hélio Castro;,citation_author=Leonilde Varela;,citation_author=Vaibhav Shah;,citation_publication_date=2016-08;,citation_cover_date=2016-08;,citation_year=2016;,citation_fulltext_html_url=http://dx.doi.org/10.1007/s10798-015-9318-z;,citation_issue=3;,citation_doi=10.1007/s10798-015-9318-z;,citation_issn=0957-7572;,citation_volume=26;,citation_journal_title=International Journal of Technology and Design Education;,citation_publisher=Springer Netherlands;">
<meta name="citation_reference" content="citation_title=Centrality measures and academic achievement in computerized classroom social networks: An empirical investigation;,citation_author=Iris Reychav;,citation_author=Daphne Ruth Raban;,citation_author=Roger McHaney;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_fulltext_html_url=http://dx.doi.org/10.1177/0735633117715749;,citation_issue=4;,citation_doi=10.1177/0735633117715749;,citation_issn=1531-4278;,citation_volume=56;,citation_journal_title=ACM Journal on Educational Resources in Computing;,citation_publisher=SAGE Publications Inc.;">
<meta name="citation_reference" content="citation_title=Predicting students’ final performance from participation in on-line discussion forums;,citation_author=Cristóbal Romero;,citation_author=Manuel-Ignacio López;,citation_author=Jose-María Luna;,citation_author=Sebastián Ventura;,citation_publication_date=2013-10;,citation_cover_date=2013-10;,citation_year=2013;,citation_fulltext_html_url=http://dx.doi.org/10.1016/j.compedu.2013.06.009;,citation_doi=10.1016/j.compedu.2013.06.009;,citation_issn=0360-1315;,citation_volume=68;,citation_journal_title=Computers &amp;amp;amp; education;,citation_publisher=Elsevier Ltd;">
<meta name="citation_reference" content="citation_title=Temporal network analysis: Introduction, methods and detailed tutorial with r;,citation_author=Mohammed Saqr;,citation_publication_date=2023-07;,citation_cover_date=2023-07;,citation_year=2023;,citation_fulltext_html_url=http://arxiv.org/abs/2307.12339;,citation_journal_title=arXiv [cs.SI];">
<meta name="citation_reference" content="citation_title=The role of social network analysis as a learning analytics tool in online problem based learning;,citation_author=Mohammed Saqr;,citation_author=Ahmad Alamro;,citation_publication_date=2019-05;,citation_cover_date=2019-05;,citation_year=2019;,citation_fulltext_html_url=https://www.scopus.com/inward/record.uri?eid=2-s2.0-85066468649&amp;amp;amp;doi=10.1186%2Fs12909-019-1599-6&amp;partnerID=40&amp;md5=eddbabf9f09bd8f30518ec4e24523ce0 NS -;,citation_issue=1;,citation_doi=10.1186/s12909-019-1599-6;,citation_issn=1472-6920;,citation_volume=19;,citation_journal_title=BMC medical education;,citation_publisher=BMC Medical Education;">
<meta name="citation_reference" content="citation_title=Psychological networks;,citation_author=Mohammed Saqr;,citation_author=Emorie Beck;,citation_author=Sonsoles López-Pernas;,citation_editor=Mohammed Saqr;,citation_editor=Sonsoles López-Pernas;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_inbook_title=Learning analytics methods and tutorials: A practical guide using r;">
<meta name="citation_reference" content="citation_title=How well centrality measures capture student achievement in computer-supported collaborative learning? – a systematic review and meta-analysis;,citation_author=Mohammed Saqr;,citation_author=Ramy Elmoazen;,citation_author=Matti Tedre;,citation_author=Sonsoles López-Pernas;,citation_author=Laura Hirsto;,citation_publication_date=2022-02;,citation_cover_date=2022-02;,citation_year=2022;,citation_fulltext_html_url=https://www.sciencedirect.com/science/article/pii/S1747938X22000069;,citation_doi=10.1016/j.edurev.2022.100437;,citation_issn=1747-938X;,citation_volume=35;,citation_journal_title=Educational Research Review;">
<meta name="citation_reference" content="citation_title=Using social network analysis to understand online problem-based learning and predict performance;,citation_author=Mohammed Saqr;,citation_author=Uno Fors;,citation_author=Jalal Nouri;,citation_publication_date=2018-09;,citation_cover_date=2018-09;,citation_year=2018;,citation_fulltext_html_url=http://dx.doi.org/10.1371/journal.pone.0203590;,citation_issue=9;,citation_doi=10.1371/journal.pone.0203590;,citation_issn=1932-6203;,citation_volume=13;,citation_journal_title=PloS one;,citation_publisher=Public Library of Science;">
<meta name="citation_reference" content="citation_title=How the study of online collaborative learning can guide teachers and predict students’ performance in a medical course;,citation_author=Mohammed Saqr;,citation_author=Uno Fors;,citation_author=Matti Tedre;,citation_publication_date=2018-02;,citation_cover_date=2018-02;,citation_year=2018;,citation_fulltext_html_url=http://dx.doi.org/10.1186/s12909-018-1126-1;,citation_issue=1;,citation_doi=10.1186/s12909-018-1126-1;,citation_issn=1472-6920;,citation_volume=18;,citation_journal_title=BMC medical education;,citation_publisher=BMC Medical Education;">
<meta name="citation_reference" content="citation_title=Modelling diffusion in computer-supported collaborative learning: A large scale learning analytics study;,citation_author=Mohammed Saqr;,citation_author=Sonsoles López-Pernas;,citation_publication_date=2021-12;,citation_cover_date=2021-12;,citation_year=2021;,citation_fulltext_html_url=http://dx.doi.org/10.1007/s11412-021-09356-4;,citation_issue=4;,citation_doi=10.1007/s11412-021-09356-4;,citation_issn=1556-1607;,citation_volume=16;,citation_journal_title=International journal of computer-supported collaborative learning;,citation_publisher=Springer Science; Business Media LLC;">
<meta name="citation_reference" content="citation_title=Instant or distant: A temporal network tale of two interaction platforms and their influence on collaboration;,citation_author=Mohammed Saqr;,citation_author=Sonsoles López-Pernas;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=http://dx.doi.org/10.1007/978-3-031-16290-9_55;,citation_doi=10.1007/978-3-031-16290-9_55;,citation_conference_title=Educating for a new future: Making sense of technology-enhanced learning adoption;,citation_conference=Springer International Publishing;">
<meta name="citation_reference" content="citation_title=The why, the what and the how to model a dynamic relational learning process with temporal networks;,citation_author=Mohammed Saqr;,citation_author=Sonsoles López-Pernas;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://www.researchgate.net/profile/Mohammed-Saqr/publication/364997941_The_Why_the_What_and_the_How_to_Model_a_Dynamic_Relational_Learning_Process_with_Temporal_Networks/links/636271222f4bca7fd0270b74/The-Why-the-What-and-the-How-to-Model-a-Dynamic-Relational-Learning-Process-with-Temporal-Networks.pdf;,citation_conference_title=Proceedings of the NetSciLA22 workshop;">
<meta name="citation_reference" content="citation_title=The curious case of centrality measures: A large-scale empirical investigation;,citation_author=Mohammed Saqr;,citation_author=Sonsoles López-Pernas;,citation_publication_date=2022-03;,citation_cover_date=2022-03;,citation_year=2022;,citation_fulltext_html_url=http://dx.doi.org/10.18608/jla.2022.7415;,citation_issue=1;,citation_doi=10.18608/jla.2022.7415;,citation_issn=1929-7750;,citation_volume=9;,citation_journal_title=Journal of learning analytics;,citation_publisher=Society for Learning Analytics Research;">
<meta name="citation_reference" content="citation_title=How CSCL roles emerge, persist, transition, and evolve over time: A four-year longitudinal study;,citation_author=Mohammed Saqr;,citation_author=Sonsoles López-Pernas;,citation_publication_date=2022-11;,citation_cover_date=2022-11;,citation_year=2022;,citation_fulltext_html_url=http://dx.doi.org/10.1016/j.compedu.2022.104581;,citation_issue=104581;,citation_doi=10.1016/j.compedu.2022.104581;,citation_issn=0360-1315;,citation_volume=189;,citation_journal_title=Computers &amp;amp;amp; education;,citation_publisher=Elsevier BV;">
<meta name="citation_reference" content="citation_title=High resolution temporal network analysis to understand and improve collaborative learning;,citation_author=Mohammed Saqr;,citation_author=Jalal Nouri;,citation_publication_date=2020-03;,citation_cover_date=2020-03;,citation_year=2020;,citation_fulltext_html_url=https://dl.acm.org/doi/10.1145/3375462.3375501;,citation_doi=10.1145/3375462.3375501;,citation_isbn=9781450377126;,citation_conference_title=Proceedings of the tenth international conference on learning analytics &amp;amp;amp; knowledge;,citation_conference=ACM;">
<meta name="citation_reference" content="citation_title=How networking and social capital influence performance: The role of long-term ties;,citation_author=Mohammed Saqr;,citation_author=Jalal Nouri;,citation_author=Uno Fors;,citation_author=Olga Viberg;,citation_author=Marya Alsuhaibani;,citation_author=Amjad Alharbi;,citation_author=Mohammed Alharbi;,citation_author=Abdullah Alamer;,citation_editor=Artem Antonyuk;,citation_editor=Nikita Basov;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_fulltext_html_url=http://dx.doi.org/10.1007/978-3-030-64877-0_22;,citation_doi=10.1007/978-3-030-64877-0_22;,citation_isbn=9783030648763;,citation_volume=181;,citation_conference_title=Lecture notes in networks and systems;,citation_conference=Springer International Publishing;,citation_series_title=Lecture notes in networks and systems;">
<meta name="citation_reference" content="citation_title=Robustness and rich clubs in collaborative learning groups: A learning analytics study using network science;,citation_author=Mohammed Saqr;,citation_author=Jalal Nouri;,citation_author=Henriikka Vartiainen;,citation_author=Matti Tedre;,citation_publication_date=2020-12;,citation_cover_date=2020-12;,citation_year=2020;,citation_fulltext_html_url=https://doi.org/10.1038/s41598-020-71483-z;,citation_issue=1;,citation_doi=10.1038/s41598-020-71483-z;,citation_issn=2045-2322;,citation_volume=10;,citation_journal_title=Scientific reports;,citation_publisher=Nature Publishing Group UK;">
<meta name="citation_reference" content="citation_title=Networks in education: A travelogue through five decades;,citation_author=Mohammed Saqr;,citation_author=Oleksandra Poquet;,citation_author=Sonsoles Lopez-Pernas;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=http://dx.doi.org/10.1109/access.2022.3159674;,citation_doi=10.1109/access.2022.3159674;,citation_issn=2169-3536;,citation_journal_title=IEEE access: practical innovations, open solutions;,citation_publisher=Institute of Electrical; Electronics Engineers (IEEE);">
<meta name="citation_reference" content="citation_title=Using diffusion network analytics to examine and support knowledge construction in CSCL settings;,citation_author=Mohammed Saqr;,citation_author=Olga Viberg;,citation_editor=C. Alario-Hoyos;,citation_editor=M. J. Rodríguez-Triana;,citation_editor=l. M. Scheffe;,citation_editor=I. Arnedillo-Sánchez;,citation_editor=Dennerlein S.m.;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_fulltext_html_url=http://dx.doi.org/10.1007/978-3-030-57717-9_12;,citation_doi=10.1007/978-3-030-57717-9_12;,citation_isbn=9783030577162;,citation_issn=1611-3349;,citation_volume=12315;,citation_inbook_title=Addressing global challenges and quality education. EC-TEL 2020. Lecture notes in computer science;">
<meta name="citation_reference" content="citation_title=Capturing the participation and social dimensions of computer-supported collaborative learning through social network analysis: Which method and measures matter?;,citation_author=Mohammed Saqr;,citation_author=Olga Viberg;,citation_author=Henriikka Vartiainen;,citation_publication_date=2020-06;,citation_cover_date=2020-06;,citation_year=2020;,citation_fulltext_html_url=https://doi.org/10.1007/s11412-020-09322-6;,citation_issue=2;,citation_doi=10.1007/s11412-020-09322-6;,citation_issn=1556-1615;,citation_volume=15;,citation_journal_title=International Journal of Computer-Supported Collaborative Learning;,citation_publisher=Springer Science; Business Media LLC;">
<meta name="citation_reference" content="citation_title=Social network analysis for technology-enhanced learning: Review and future directions;,citation_author=Rory L. L. Sie;,citation_author=Daniel Thomas Ullmann;,citation_author=Kamakshi Rajagopal;,citation_author=Karina Cela;,citation_author=Marlies Bitter-Rijpkema B.;,citation_author=Peter B. Sloep;,citation_publication_date=2012;,citation_cover_date=2012;,citation_year=2012;,citation_fulltext_html_url=http://dspace.ou.nl/handle/1820/4747;,citation_issue=3/4;,citation_doi=10.1504/IJTEL.2012.051582;,citation_issn=1753-5255;,citation_volume=4;,citation_journal_title=International Journal of Technology Enhanced Learning;">
<meta name="citation_reference" content="citation_title=Unpacking the relationship between discussion forum participation and learning in MOOCs: Content is key;,citation_author=Alyssa Friend Wise;,citation_author=Yi Cui;,citation_publication_date=2018-03;,citation_cover_date=2018-03;,citation_year=2018;,citation_fulltext_html_url=https://www.scopus.com/inward/record.uri?eid=2-s2.0-85045559488&amp;amp;amp;doi=10.1145%2F3170358.3170403&amp;partnerID=40&amp;md5=f98522731ecda08d84b660ca21e43be0 NS -;,citation_doi=10.1145/3170358.3170403;,citation_isbn=9781450364003;,citation_conference_title=ACM international conference proceeding series;,citation_conference=Association for Computing Machinery;">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Social Network Analysis: A primer, a guide and a tutorial in R</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Learning analytics methods and tutorials</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../contributors.html" class="sidebar-item-text sidebar-link">Contributors</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch01-intro/intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Getting started</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch02-data/ch2-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch03-intro-r/ch3-intor.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Intro to R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch04-data-cleaning/ch4-datacleaning.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data cleaning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch05-basic-stats/ch5-stats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basic statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch06-data-visualization/ch6-viz.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data visualization</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Machine Learning</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch07-prediction/ch7-pred.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Predictive modeling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch08-clustering/ch8-clus.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Clustering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch09-model-based-clustering/ch9-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Model-based clustering</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Temporal methods</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch10-sequence-analysis/ch10-seq.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequence analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch11-vasstra/ch11-vasstra.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">VaSSTra</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch12-markov/ch12-markov.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Markov models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch13-multichannel/ch13-multi.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Multi-channel sequences</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch14-process-mining/ch14-process.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Process mining</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Network analysis</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch15-sna/ch15-sna.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Social Network Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch16-community/ch16-comm.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Community detection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch17-temporal-networks/ch17-tna.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Temporal Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch18-ena-ona/ch18-ena.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Epistemic Network Analysis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">Psychometrics</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch19-psychological-networks/ch19-psych.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Psychological networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch20-factor-analysis/ch20-factor.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Factor analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch21-sem/ch21-sem.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Structured Equation Modeling</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/ch22-conclusion/ch22-conclusion.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Conclusion</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="toc-section-number">1</span>  Introduction</a>
  <ul class="collapse">
  <li><a href="#what-are-networks" id="toc-what-are-networks" class="nav-link" data-scroll-target="#what-are-networks"><span class="toc-section-number">1.1</span>  What are networks?</a></li>
  </ul></li>
  <li><a href="#analysis-of-social-networks" id="toc-analysis-of-social-networks" class="nav-link" data-scroll-target="#analysis-of-social-networks"><span class="toc-section-number">2</span>  Analysis of social networks</a>
  <ul class="collapse">
  <li><a href="#mathematical-analysis" id="toc-mathematical-analysis" class="nav-link" data-scroll-target="#mathematical-analysis"><span class="toc-section-number">2.1</span>  Mathematical analysis</a></li>
  <li><a href="#network-visualization" id="toc-network-visualization" class="nav-link" data-scroll-target="#network-visualization"><span class="toc-section-number">2.2</span>  Network visualization</a></li>
  <li><a href="#network-analysis" id="toc-network-analysis" class="nav-link" data-scroll-target="#network-analysis"><span class="toc-section-number">2.3</span>  Network analysis</a></li>
  </ul></li>
  <li><a href="#network-analysis-in-r" id="toc-network-analysis-in-r" class="nav-link" data-scroll-target="#network-analysis-in-r"><span class="toc-section-number">3</span>  Network analysis in R</a>
  <ul class="collapse">
  <li><a href="#graph-level-analysis" id="toc-graph-level-analysis" class="nav-link" data-scroll-target="#graph-level-analysis"><span class="toc-section-number">3.1</span>  Graph level analysis</a></li>
  <li><a href="#network-connectivity" id="toc-network-connectivity" class="nav-link" data-scroll-target="#network-connectivity"><span class="toc-section-number">3.2</span>  Network connectivity</a></li>
  <li><a href="#network-operations" id="toc-network-operations" class="nav-link" data-scroll-target="#network-operations"><span class="toc-section-number">3.3</span>  Network operations</a></li>
  <li><a href="#individual-vertex-measures-centrality-measures" id="toc-individual-vertex-measures-centrality-measures" class="nav-link" data-scroll-target="#individual-vertex-measures-centrality-measures"><span class="toc-section-number">3.4</span>  Individual vertex measures (centrality measures)</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="toc-section-number">4</span>  Discussion</a></li>
  <li><a href="#more-reading-resources" id="toc-more-reading-resources" class="nav-link" data-scroll-target="#more-reading-resources"><span class="toc-section-number">5</span>  More reading resources</a></li>
  <li><a href="#acknowledgements" id="toc-acknowledgements" class="nav-link" data-scroll-target="#acknowledgements"><span class="toc-section-number">6</span>  Acknowledgements</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">References</a></li>
  </ul>
</nav>
    <div class="quarto-margin-footer"><div class="margin-footer-item">
<p><small>© 2023 The authors</small></p>
</div></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Social Network Analysis: A primer, a guide and a tutorial in R</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Mohammed Saqr </p>
             <p>Sonsoles López-Pernas </p>
             <p>Miguel Ángel Conde </p>
             <p>Ángel Hernández-García </p>
          </div>
  </div>
    
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="abstract-title">Abstract</div>
    This chapter introduces the concept and methods of social network analysis (SNA) with a detailed guide to analysis with real world data using the R programming language. The chapter first introduces the basic concepts and types of networks. Then the chapter goes through a detailed step by step analysis of networks, computation of graph level measures as well as centralities with a concise interpretation in a collaborative environment. The chapter concludes with a discussion of network analysis, next steps as well as a list of further readings.
  </div>
</div>

</header>

<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>Social Network Analysis (SNA) has emerged as a computational method for studying interactions, relationships, and connections among a vast array of different entities that include humans, animals, and cities, just to name a few. Two related and largely overlapping fields are also concerned with the network as a concept: network science and network analysis. Network science is concerned with the study of the structure of networks, finding patterns and universal laws that may explain or underpin such structure in a large variety of phenomena. Network analysis is a very closely related field that is concerned with the analysis of networks that are not necessarily “social”. In this chapter, we will simply use the terms social network analysis and network analysis interchangeably.</p>
<section id="what-are-networks" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="what-are-networks"><span class="header-section-number">1.1</span> What are networks?</h3>
<p>A quintessential concept in most analytical methods is that observations are —or should be — independent from each other whereas, in network analysis, observations can be related and interdependent and may interact with or influence each other Saqr_Poquet_Lopez-Pernas_2022. As such, network analysis offers a more realistic view of the interconnected world around us and allows us to paint an accurate picture of the relationships and interactions that underpin our world <span class="citation" data-cites="Barabási_2013 Borgatti_Mahra_Brass_Labianca_2009">[<a href="#ref-Barabási_2013" role="doc-biblioref">1</a>, <a href="#ref-Borgatti_Mahra_Brass_Labianca_2009" role="doc-biblioref">2</a>]</span>. For instance, when we study students’ engagement at a school, we may use a survey to measure each individual student’s engagement and compute statistics such as the correlation between engagement and grades. In doing so, we ignore that students interact with peers, teachers, and the environment around them <span class="citation" data-cites="Saqr_López-Pernas_2022d Saqr_Nouri_Fors_Viberg_Alsuhaibani_Alharbi_Alharbi_Alamer_2021">[<a href="#ref-Saqr_López-Pernas_2022d" role="doc-biblioref">3</a>, <a href="#ref-Saqr_Nouri_Fors_Viberg_Alsuhaibani_Alharbi_Alharbi_Alamer_2021" role="doc-biblioref">4</a>]</span>. We also ignore that students get influenced by an engaged student, get supported by their friends, or face a problematic social environment that may hinder their engagement <span class="citation" data-cites="Saqr_Nouri_Vartiainen_Tedre_2020 Saqr_Poquet_Lopez-Pernas_2022">[<a href="#ref-Saqr_Nouri_Vartiainen_Tedre_2020" role="doc-biblioref">5</a>, <a href="#ref-Saqr_Poquet_Lopez-Pernas_2022" role="doc-biblioref">6</a>]</span>. Network analysis offers a rich set of methods for modeling and addressing such issues <span class="citation" data-cites="Saqr_Alamro_2019">[<a href="#ref-Saqr_Alamro_2019" role="doc-biblioref">7</a>]</span>.</p>
<p>A network is simply a group of entities (often called <em>vertices</em>, nodes, or <em>actors</em>) connected through a relationship (often called <em>edges</em>, <em>links, or arcs</em>) <span class="citation" data-cites="Borgatti_Mahra_Brass_Labianca_2009">[<a href="#ref-Borgatti_Mahra_Brass_Labianca_2009" role="doc-biblioref">2</a>]</span>. In this chapter, we will use the terms vertices and edges for simplicity. Vertices can be humans (students, teachers, or families), ideas, keywords, behaviors, emotions, feelings, concepts, schools, countries, or any entity that can be hypothesized to have a relationship with other entities. Vertices may be connected through a vast array of relations. For instance, students may be connected to each other by being friends, teammates, classmates, group members, neighbors, sporting club fans, competitors, sharing a desk, or working together on an assignment. There is virtually no limit to how a researcher can hypothesize a network. Nevertheless, the interpretation of network analysis relies heavily on how the network was constructed <span class="citation" data-cites="Borgatti_Mahra_Brass_Labianca_2009 Dado_Bodemer_2017">[<a href="#ref-Borgatti_Mahra_Brass_Labianca_2009" role="doc-biblioref">2</a>, <a href="#ref-Dado_Bodemer_2017" role="doc-biblioref">8</a>]</span>.</p>
<p>In learning contexts, the most common type of networks comes from digital data, and in particular online communications, the most common of which are discussion forums, where the conversation occurs between forum participants (vertices). Each reply from one participant to another forms a relationship between the two vertices, creating an edge in the network. In such a situation, we are talking about a <em>directed</em> network, where the interaction has a source (the person who replies) and a target (the replied-to) <span class="citation" data-cites="Poquet_Saqr_Chen_2021">[<a href="#ref-Poquet_Saqr_Chen_2021" role="doc-biblioref">9</a>]</span>. Other examples of directed networks are citation networks (where documents cite other documents), or users that follow other users in social media <span class="citation" data-cites="López-Pernas_Saqr_Apiola_2023">[<a href="#ref-López-Pernas_Saqr_Apiola_2023" role="doc-biblioref">10</a>]</span>. In turn, an <em>undirected</em> network contains non-directional relationships such as a network of siblings, friends, teammates, husband and wife, or co-workers <span class="citation" data-cites="Borgatti_Mahra_Brass_Labianca_2009">[<a href="#ref-Borgatti_Mahra_Brass_Labianca_2009" role="doc-biblioref">2</a>.]</span> Representing interactions as a network equips the researchers with a rich toolset to harness the power of social network analysis methods. <em>Please note that the researcher can choose to model a directed network as undirected in case direction is deemed inappropriate according to theory, connect or research question.</em></p>
</section>
</section>
<section id="analysis-of-social-networks" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="analysis-of-social-networks"><span class="header-section-number">2</span> Analysis of social networks</h2>
<p>Two types of analysis methods are commonly used: network visualization and mathematical network analysis <span class="citation" data-cites="Borgatti_Mahra_Brass_Labianca_2009">[<a href="#ref-Borgatti_Mahra_Brass_Labianca_2009" role="doc-biblioref">2</a>.]</span> Visualization summarizes all the interactions in the network, giving the researcher a bird’s eye view of the structure of relationships, who is interacting with whom, who is leading the conversation, and who is isolated. Visualization is so powerful that it can summarize a whole semester of interactions in one visualization and still give meaningful information that can be used for intervention e.g., <span class="citation" data-cites="Saqr_Fors_Tedre_2018">[<a href="#ref-Saqr_Fors_Tedre_2018" role="doc-biblioref">11</a>]</span>. Mathematical network analysis offers quantification of all the network properties and the individual actors. The network properties are commonly known as graph-level measures. The mathematical measures of individual nodes are known node-level measures (often referred to as centrality measures) <span class="citation" data-cites="Borgatti_Brass_2019 Borgatti_Mahra_Brass_Labianca_2009 Dado_Bodemer_2017">[<a href="#ref-Borgatti_Mahra_Brass_Labianca_2009" role="doc-biblioref">2</a>, <a href="#ref-Dado_Bodemer_2017" role="doc-biblioref">8</a>, <a href="#ref-Borgatti_Brass_2019" role="doc-biblioref">12</a>]</span> Visualization is not discussed in details in this chapter, but interested readers are encouraged to see the excellent visualization tutorial maintained by Kateto Ognyanova <span class="citation" data-cites="Ognyanova_2023">[<a href="#ref-Ognyanova_2023" role="doc-biblioref">13</a>]</span>.</p>
<section id="mathematical-analysis" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="mathematical-analysis"><span class="header-section-number">2.1</span> Mathematical analysis</h3>
<p>Three types of mathematical analysis can be obtained with SNA: graph-level measures, node-level measures (centrality measures) and edge-level measures. Graph level measures describe the network as a whole in terms of size, interactivity and components. <em>Centrality measures</em> quantify the connectivity and importance of individual actors such as the degree of involvement in interactions, the distance to others, or the importance of position among other interacting actors <span class="citation" data-cites="Borgatti_Brass_2019 Liao_Mariani_Medo_Zhang_Zhou_2017 Saqr_López-Pernas_2022c">[<a href="#ref-Borgatti_Brass_2019" role="doc-biblioref">12</a>, <a href="#ref-Liao_Mariani_Medo_Zhang_Zhou_2017" role="doc-biblioref">14</a>, <a href="#ref-Saqr_López-Pernas_2022c" role="doc-biblioref">15</a>]</span>. However, each of these “importance” examples can be measured in different ways. For example, students can be considered central if they frequently contribute to discussions, reply to multiple unique threads of discussions, their contributions receive multiple replies, or their contributions trigger several threads of discussions. As such, there are several centralities with diverse methods that allow us to quantify the degree of connectedness. The website centiserver.org counts more than 400 centrality measures to this date and counting. In this book chapter, we will review and learn the most commonly used centralities in education. We rely on the recent meta-analysis 2022 for listing the used centrality measures, their classification, and operationalization in the literature. Edge measures describe the edge strength, edge weights or edges or edge centralities.</p>
<section id="graph-level-measures" class="level4" data-number="2.1.1">
<h4 data-number="2.1.1" class="anchored" data-anchor-id="graph-level-measures"><span class="header-section-number">2.1.1</span> Graph-level measures</h4>
<p>Graph-level measures are a type of analysis used in social network analysis that describes the overall structure and characteristics of a network. They can be used to compare different networks or track changes in a network over time.</p>
<p><strong>Size</strong> or <strong>vertex count</strong> is the number of vertices (individuals or groups) in the network.</p>
<p><strong>Edge count</strong> is the number of edges (interactions) between vertices in the network.</p>
<p><strong>Density</strong> represents the number of edges that are present in the network divided by the number of all possible connections. High density indicates that many vertices in the network are connected to one another.</p>
<p><strong>Reciprocity</strong> is another important graph-level measure that also reflects group cohesion. A reciprocated edge is an edge where two vertices have a reciprocal relationship (e.g., they are simultaneously source and target) <span class="citation" data-cites="Block_2015">[<a href="#ref-Block_2015" role="doc-biblioref">16</a>]</span>. The higher the ratio of the reciprocated edges, the more collaborative the network is, less centralized (dominated by few) and more participatory.</p>
<p><strong>Transitivity</strong> (or global clustering coefficient) measures the tendency of the vertices to cluster together or form tightly knit cliques. There is a large volume of research that associates the ratio of cliques with cohesion in collaborative groups, strong ties and productive knowledge construction <span class="citation" data-cites="Block_2015">[<a href="#ref-Block_2015" role="doc-biblioref">16</a>]</span></p>
<p>Other graph-level measures are aggregations of vertex-level or edge-level measures. For example, the <strong>mean degree</strong> is the mean number of edges of all the vertices in the network. In a collaborative group, the higher the mean degree, the more interactive the group is.</p>
</section>
<section id="local-centrality-measures" class="level4" data-number="2.1.2">
<h4 data-number="2.1.2" class="anchored" data-anchor-id="local-centrality-measures"><span class="header-section-number">2.1.2</span> Local centrality measures</h4>
<p>Local centrality measures are centralities that map the direct or immediate connections of an actor. Put another way, the local centralities quantify the neighbors of a certain vertex where each of these neighbors is directly connected to the target vertex without any intermediates (<a href="#fig-vertex-in-degree">Figure&nbsp;<span>15.1</span></a>).</p>
<p><strong>In-degree centrality</strong> represents the total number of incoming interactions or relationships of a vertex <span class="citation" data-cites="Borgatti_Brass_2019 Liao_Mariani_Medo_Zhang_Zhou_2017">[<a href="#ref-Borgatti_Brass_2019" role="doc-biblioref">12</a>, <a href="#ref-Liao_Mariani_Medo_Zhang_Zhou_2017" role="doc-biblioref">14</a>]</span>. Several examples exist in the literature with different operationalization and interpretations. In the case of collaborative learning, in-degree centrality has been interpreted as the worthiness of a participant’s contributions to receive replies, popularity, or influence <span class="citation" data-cites="Jo_Park_Lee_2017 Romero_López_Luna_Ventura_2013 Saqr_López-Pernas_2021">[<a href="#ref-Jo_Park_Lee_2017" role="doc-biblioref">17</a>–<a href="#ref-Saqr_López-Pernas_2021" role="doc-biblioref">19</a>]</span>.</p>
<p><strong>Out-degree centrality</strong> represents the total number of outgoing interactions or links from an actor to other actors in the network <span class="citation" data-cites="Borgatti_Brass_2019 Liao_Mariani_Medo_Zhang_Zhou_2017 Saqr_López-Pernas_2022a">[<a href="#ref-Borgatti_Brass_2019" role="doc-biblioref">12</a>, <a href="#ref-Liao_Mariani_Medo_Zhang_Zhou_2017" role="doc-biblioref">14</a>, <a href="#ref-Saqr_López-Pernas_2022a" role="doc-biblioref">20</a>]</span>. Out-degree has been commonly interpreted as an indicator of participation, effort, and activity <span class="citation" data-cites="Marcos-García_Martínez-Monés_Dimitriadis_2015 Saqr_Viberg_Vartiainen_2020">[<a href="#ref-Marcos-García_Martínez-Monés_Dimitriadis_2015" role="doc-biblioref">21</a>, <a href="#ref-Saqr_Viberg_Vartiainen_2020" role="doc-biblioref">22</a>]</span>.</p>
<p><strong>Degree centrality</strong> refers to the total number of connections or interactions (incoming or outgoing) a vertex has. In undirected networks, it is simply the number of all connections of the vertex. Degree centrality can be interpreted in a similar way to the previous similar centralities as an indication of interactivity, communication, and social role in the collaborative process <span class="citation" data-cites="Hernández-García_González-González_Jiménez-Zarco_Chaparro-Peláez_2015 Joksimovic_Manataki_Gaševic_Dawson_Kovanovic_De_Kereki_2016 Reychav_Raban_McHaney_2018">[<a href="#ref-Hernández-García_González-González_Jiménez-Zarco_Chaparro-Peláez_2015" role="doc-biblioref">23</a>–<a href="#ref-Reychav_Raban_McHaney_2018" role="doc-biblioref">25</a>]</span>.</p>
<div id="fig-vertex-in-degree" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="image1.png" style="width:6.5in;height:2.38468in" class="figure-img"></p>
<p></p><figcaption class="figure-caption"><strong>Figure</strong>&nbsp;1<strong>.</strong> Representation of a vertex in-degree (left), out-degree (middle), and degree (right)</figcaption><p></p>
</figure>
</div>
</section>
<section id="measures-based-on-shortest-paths" class="level4" data-number="2.1.3">
<h4 data-number="2.1.3" class="anchored" data-anchor-id="measures-based-on-shortest-paths"><span class="header-section-number">2.1.3</span> Measures based on shortest paths</h4>
<p>Other relevant measures in assessing social network graphs are the shortest paths. These are based on the shortest distance between a pair of points (vertex) in the graph and represent how easy it is for a vertex to access others’ resources <span class="citation" data-cites="Borgatti_Brass_2019 Freeman_1978 Liao_Mariani_Medo_Zhang_Zhou_2017">[<a href="#ref-Borgatti_Brass_2019" role="doc-biblioref">12</a>, <a href="#ref-Liao_Mariani_Medo_Zhang_Zhou_2017" role="doc-biblioref">14</a>, <a href="#ref-Freeman_1978" role="doc-biblioref">26</a>]</span>. Shortest paths can be used to better measure and understand centrality, as it is based on the distribution and distance of different points in a network which can help understand other educational insights <span class="citation" data-cites="Cela_Sicilia_Sánchez_2015 Dado_Bodemer_2017">[<a href="#ref-Dado_Bodemer_2017" role="doc-biblioref">8</a>., <a href="#ref-Cela_Sicilia_Sánchez_2015" role="doc-biblioref">27</a>]</span> The most relevant measures in this sense are represented in <a href="#fig-examples">Figure&nbsp;<span>15.2</span></a> and described below.</p>
<p><strong>Closeness centrality</strong> is a measure based on the farness between the vertices of a network; more specifically between a specific vertex and the rest of the network <span class="citation" data-cites="Borgatti_Brass_2019 Liao_Mariani_Medo_Zhang_Zhou_2017">[<a href="#ref-Borgatti_Brass_2019" role="doc-biblioref">12</a>, <a href="#ref-Liao_Mariani_Medo_Zhang_Zhou_2017" role="doc-biblioref">14</a>]</span>. Small closeness values indicate greater proximity to other vertices, whereas larger values indicate greater distances from other vertices. In the field of education, it can be seen as a way to measure: 1) closure in interaction <span class="citation" data-cites="Cadima_Ojeda_Monguet_2012 Cho_Gay_Davidson_Ingraffea_2007 Liu_Kang_Domanska_Liu_Sun_Fang_2018 Osatuyi_Passerini_2016 Putnik_Costa_Alves_Castro_Varela_Shah_2016 Saqr_Fors_Tedre_2018">[<a href="#ref-Saqr_Fors_Tedre_2018" role="doc-biblioref">11</a>, <a href="#ref-Cadima_Ojeda_Monguet_2012" role="doc-biblioref">28</a>–<a href="#ref-Putnik_Costa_Alves_Castro_Varela_Shah_2016" role="doc-biblioref">32</a>]</span>, 2) ease of interaction <span class="citation" data-cites="Cho_Gay_Davidson_Ingraffea_2007 Gašević_Joksimović_Eagan_Shaffer_2019 Joksimovic_Manataki_Gaševic_Dawson_Kovanovic_De_Kereki_2016 Saqr_Fors_Nouri_2018 Saqr_Fors_Tedre_2018">[<a href="#ref-Saqr_Fors_Tedre_2018" role="doc-biblioref">11</a>, <a href="#ref-Joksimovic_Manataki_Gaševic_Dawson_Kovanovic_De_Kereki_2016" role="doc-biblioref">24</a>, <a href="#ref-Cho_Gay_Davidson_Ingraffea_2007" role="doc-biblioref">29</a>, <a href="#ref-Gašević_Joksimović_Eagan_Shaffer_2019" role="doc-biblioref">33</a>, <a href="#ref-Saqr_Fors_Nouri_2018" role="doc-biblioref">34</a>]</span>, 3) time for accessing information <span class="citation" data-cites="Hernández-García_González-González_Jiménez-Zarco_Chaparro-Peláez_2015 Liu_Chai_Liu_Pinkwart_Han_Hu_2019 Osatuyi_Passerini_2016">[<a href="#ref-Hernández-García_González-González_Jiménez-Zarco_Chaparro-Peláez_2015" role="doc-biblioref">23</a>, <a href="#ref-Osatuyi_Passerini_2016" role="doc-biblioref">31</a>, <a href="#ref-Liu_Chai_Liu_Pinkwart_Han_Hu_2019" role="doc-biblioref">35</a>]</span>, 4) dependencies <span class="citation" data-cites="Liu_Kang_Domanska_Liu_Sun_Fang_2018">[<a href="#ref-Liu_Kang_Domanska_Liu_Sun_Fang_2018" role="doc-biblioref">30</a>]</span>, 5) control over resources <span class="citation" data-cites="Cadima_Ojeda_Monguet_2012 Gašević_Joksimović_Eagan_Shaffer_2019 Reychav_Raban_McHaney_2018">[<a href="#ref-Reychav_Raban_McHaney_2018" role="doc-biblioref">25</a>, <a href="#ref-Cadima_Ojeda_Monguet_2012" role="doc-biblioref">28</a>, <a href="#ref-Gašević_Joksimović_Eagan_Shaffer_2019" role="doc-biblioref">33</a>]</span>, and 6) awareness of opportunities <span class="citation" data-cites="Cadima_Ojeda_Monguet_2012">[<a href="#ref-Cadima_Ojeda_Monguet_2012" role="doc-biblioref">28</a>]</span>.</p>
<p><strong>Betweenness centrality</strong> is a measure to show the frequency of a vertex lying on the shortest path between two other vertices. In the field of education, it indicates how actors mediate communication among themselves <span class="citation" data-cites="Cela_Sicilia_Sánchez_2015 Dado_Bodemer_2017">[<a href="#ref-Dado_Bodemer_2017" role="doc-biblioref">8</a>, <a href="#ref-Cela_Sicilia_Sánchez_2015" role="doc-biblioref">27</a>]</span>. It can be a way to understand who are the leaders of the interactions, that is, those who can moderate interactions, reach unconnected groups (inter-group connection) , influence the information flow (information brokering) and manage that information to solve problems effectively <span class="citation" data-cites="Cadima_Ojeda_Monguet_2012 Cho_Gay_Davidson_Ingraffea_2007 De-Marcos_Garciá-López_Garciá-Cabot_Medina-Merodio_Domínguez_Martínez-Herraíz_Diez-Folledo_2016">[<a href="#ref-Cadima_Ojeda_Monguet_2012" role="doc-biblioref">28</a>, <a href="#ref-Cho_Gay_Davidson_Ingraffea_2007" role="doc-biblioref">29</a>, <a href="#ref-De-Marcos_Garciá-López_Garciá-Cabot_Medina-Merodio_Domínguez_Martínez-Herraíz_Diez-Folledo_2016" role="doc-biblioref">36</a>]</span>.</p>
<p><strong>Eccentricity</strong> can help to see the vertices not involved in the interactions. It is calculated as the distance to the farthest other vertices in the network. It can be used in the educational field to understand which are the students at risk of dropout or those that are not participating in the activities <span class="citation" data-cites="De-Marcos_Garciá-López_Garciá-Cabot_Medina-Merodio_Domínguez_Martínez-Herraíz_Diez-Folledo_2016 Saqr_Fors_Nouri_2018 Saqr_Fors_Tedre_2018">[<a href="#ref-Saqr_Fors_Tedre_2018" role="doc-biblioref">11</a>, <a href="#ref-Saqr_Fors_Nouri_2018" role="doc-biblioref">34</a>, <a href="#ref-De-Marcos_Garciá-López_Garciá-Cabot_Medina-Merodio_Domínguez_Martínez-Herraíz_Diez-Folledo_2016" role="doc-biblioref">36</a>]</span>.</p>
<div id="fig-examples" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="image2.png" style="width:6.5in;height:2.37284in" class="figure-img"></p>
<p></p><figcaption class="figure-caption"><strong>Figure</strong>&nbsp;2<strong>.</strong> Examples of networks where the highlighted vertex has a high value of betweenness (left), closeness (middle), and eccentricity (right)</figcaption><p></p>
</figure>
</div>
</section>
<section id="eigenvector-based-centralities" class="level4" data-number="2.1.4">
<h4 data-number="2.1.4" class="anchored" data-anchor-id="eigenvector-based-centralities"><span class="header-section-number">2.1.4</span> Eigenvector-Based centralities</h4>
<p>Other useful metrics in social network graphs are those based on eigenvector centralities, i.e., those related to the value of a connection between vertices. It is based on the idea that it is preferable to have fewer connections to strong well-connected vertices than to have many connections to weak isolated vertices. There are several measures based on this principle:</p>
<p><strong>Eigenvector centrality</strong> assesses the importance of a vertex based on the centralities of the vertex to which it is connected, that is, how many connections it has to influential vertices. It has been used to understand social capital, ego, and connection strength <span class="citation" data-cites="Hernández-García_González-González_Jiménez-Zarco_Chaparro-Peláez_2015 Marcos-García_Martínez-Monés_Dimitriadis_2015 Saqr_Fors_Nouri_2018 Wise_Cui_2018">[<a href="#ref-Marcos-García_Martínez-Monés_Dimitriadis_2015" role="doc-biblioref">21</a>, <a href="#ref-Hernández-García_González-González_Jiménez-Zarco_Chaparro-Peláez_2015" role="doc-biblioref">23</a>, <a href="#ref-Saqr_Fors_Nouri_2018" role="doc-biblioref">34</a>, <a href="#ref-Wise_Cui_2018" role="doc-biblioref">37</a>]</span>.</p>
<p><strong>Pagerank</strong> is based on link analysis and allows for defining the popularity of an individual in a network. It can be used in education to understand the reputation or influence upon a group of stakeholders based on his/her contacts <span class="citation" data-cites="De-Marcos_Garciá-López_Garciá-Cabot_Medina-Merodio_Domínguez_Martínez-Herraíz_Diez-Folledo_2016 Liu_Kang_Su_Liu_Sun_2018">[<a href="#ref-De-Marcos_Garciá-López_Garciá-Cabot_Medina-Merodio_Domínguez_Martínez-Herraíz_Diez-Folledo_2016" role="doc-biblioref">36</a>, <a href="#ref-Liu_Kang_Su_Liu_Sun_2018" role="doc-biblioref">38</a>]</span>.</p>
<p><strong>Hub centrality</strong> is based on Kleinberg’s HITS algorithm <span class="citation" data-cites="Kleinberg_1999">[<a href="#ref-Kleinberg_1999" role="doc-biblioref">39</a>]</span> that measures who interacts more with the most influential vertices in a network. In the educational field, it could help to understand the type of students’ interaction <span class="citation" data-cites="García-Saiz_Palazuelos_Zorrilla_2014 Hernández-García_González-González_Jiménez-Zarco_Chaparro-Peláez_2015 Liu_Kang_Su_Liu_Sun_2018">[<a href="#ref-Hernández-García_González-González_Jiménez-Zarco_Chaparro-Peláez_2015" role="doc-biblioref">23</a>, <a href="#ref-Liu_Kang_Su_Liu_Sun_2018" role="doc-biblioref">38</a>, <a href="#ref-García-Saiz_Palazuelos_Zorrilla_2014" role="doc-biblioref">40</a>]</span>.</p>
<p><strong>Authority</strong> is also based on Kleinberg’s HITS algorithm but it is used to identify which vertices might be considered an authority on a specific topic score. It is calculated taking into account if its incoming links connect the vertex to others that have an important number of outgoing links <span class="citation" data-cites="Hernández-García_González-González_Jiménez-Zarco_Chaparro-Peláez_2015 Liu_Kang_Su_Liu_Sun_2018">[<a href="#ref-Hernández-García_González-González_Jiménez-Zarco_Chaparro-Peláez_2015" role="doc-biblioref">23</a>, <a href="#ref-Liu_Kang_Su_Liu_Sun_2018" role="doc-biblioref">38</a>]</span>.</p>
</section>
<section id="other-measures" class="level4" data-number="2.1.5">
<h4 data-number="2.1.5" class="anchored" data-anchor-id="other-measures"><span class="header-section-number">2.1.5</span> Other measures</h4>
<p>There are other possible metrics to be applied in social network graphs:</p>
<p><strong>Clustering coefficient</strong> is a measure of how individuals, represented as vertices, are embedded in their neighborhood <span class="citation" data-cites="De-Marcos_Garciá-López_Garciá-Cabot_Medina-Merodio_Domínguez_Martínez-Herraíz_Diez-Folledo_2016">[<a href="#ref-De-Marcos_Garciá-López_Garciá-Cabot_Medina-Merodio_Domínguez_Martínez-Herraíz_Diez-Folledo_2016" role="doc-biblioref">36</a>]</span>, with interactions with other individuals forming triangles. In the educational field, it shows how an individual works with peers in groups or clusters, which shows network cohesion <span class="citation" data-cites="Liu_Kang_Su_Liu_Sun_2018 Reychav_Raban_McHaney_2018 Saqr_Fors_Nouri_2018 Saqr_Fors_Tedre_2018">[<a href="#ref-Saqr_Fors_Tedre_2018" role="doc-biblioref">11</a>, <a href="#ref-Reychav_Raban_McHaney_2018" role="doc-biblioref">25</a>, <a href="#ref-Saqr_Fors_Nouri_2018" role="doc-biblioref">34</a>, <a href="#ref-Liu_Kang_Su_Liu_Sun_2018" role="doc-biblioref">38</a>]</span>.</p>
<p><strong>Diffusion Centrality</strong> belongs to the diffusion measures that explore the structural properties that facilitate the diffusion and uptake process; that is, the diffusion resulting from the interaction. It tries to measure how well a vertex can diffuse a property given the semantics and structure of a social network and a model of diffusion <span class="citation" data-cites="Banerjee_Chandrasekhar_Duflo_Jackson_2013 Kang_Molinaro_Kraus_Shavitt_Subrahmanian_2012">[<a href="#ref-Banerjee_Chandrasekhar_Duflo_Jackson_2013" role="doc-biblioref">41</a>, <a href="#ref-Kang_Molinaro_Kraus_Shavitt_Subrahmanian_2012" role="doc-biblioref">42</a>]</span>. In education, it can be used to show the possibility of an interaction to generate replies and these other replies <span class="citation" data-cites="Saqr_López-Pernas_2021">[<a href="#ref-Saqr_López-Pernas_2021" role="doc-biblioref">19</a>]</span>.</p>
<p><strong>Cross Clique Centrality</strong> assesses the number of cliques or triangles a vertex belongs to. It is related to the degree of embeddedness, connectivity with other vertices, and strength of ties among vertices. In education, it allows understanding, for example, whether a post is going to be replied to and spread throughout the network <span class="citation" data-cites="Saqr_López-Pernas_2021">[<a href="#ref-Saqr_López-Pernas_2021" role="doc-biblioref">19</a>]</span>.</p>
<p><strong>Coreness (k-core or linkage)</strong> is similar to h-index metrics for publications, and is based on networks where all vertices have at least a k degree <span class="citation" data-cites="Kitsak_Gallos_Havlin_Liljeros_Muchnik_Stanley_Makse_2010">[<a href="#ref-Kitsak_Gallos_Havlin_Liljeros_Muchnik_Stanley_Makse_2010" role="doc-biblioref">43</a>]</span>. It is interesting because if an individual may produce promising contributions, he or she is going to attract others with similar contributions and establish strong connections. In the field of education, those students involved in active interactions/discussions will attract other active users, which will enrich the discussion and therefore the interaction, collaboration, the quality of content, etc. <span class="citation" data-cites="Saqr_López-Pernas_2021">[<a href="#ref-Saqr_López-Pernas_2021" role="doc-biblioref">19</a>]</span>.</p>
</section>
</section>
<section id="network-visualization" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="network-visualization"><span class="header-section-number">2.2</span> Network visualization</h3>
<p>As we discussed earlier, networks represent the relationships (edges) between actors (vertices). A vertex is commonly represented as a circle —although other shapes are also used— and the edge as an arrow (in the case of a directed network) from the source of interaction to the target of the interaction (<a href="#fig-directed-edge">Figure&nbsp;<span>15.3</span></a>). For example, a phone call from the caller to the call receiver is represented by an arrow from the caller to the receiver. In the case of an undirected network, the edge is represented by a line connecting both vertices, for instance, two siblings, where the relationship is mutual.</p>
<div id="fig-directed-edge" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="image3.png" style="width:1.96109in;height:1.77542in" class="figure-img"></p>
<p></p><figcaption class="figure-caption"><strong>Figure</strong>&nbsp;3<strong>.</strong> Left: a directed edge where an interaction happens from A-&gt;B. Right: an undirected edge where A-B are connected</figcaption><p></p>
</figure>
</div>
</section>
<section id="network-analysis" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="network-analysis"><span class="header-section-number">2.3</span> Network analysis</h3>
<p>Let us start with a simple example that uses a common analysis scenario. Our example is a fictional discussion among students where we model interactions between students as a network. Building a network from interactions in discussion forums has been commonly performed by building a post-reply network where an edge is constructed from the author (source of the reply) to the replied-to (target of the reply). For instance, in <a href="#fig-conv">Figure&nbsp;<span>15.4</span></a>, <strong>B</strong> replies to <strong>A</strong> by saying <em>“I agree, this could slow the progression of the disease but does it prevent the spread completely or terminate the pandemic?”</em>. This can be represented as an edge from B to A. In the same token, <strong>C</strong> replies to <strong>B</strong> which represents another edge C to B. We can compile all of these interactions in a list of edges as shown in <a href="#tbl-table1">Table&nbsp;<span>15.1</span></a> which is often referred to as an <em>edge list</em>. An edge list is a simple way —among many others— to represent the network and therefore we will use it in this chapter. Constructing the network can be performed by aggregating all edges as a network as <a href="#fig-conv">Figure&nbsp;<span>15.4</span></a>.</p>
<div id="fig-conv" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="image4.png" style="width:6.55497in;height:2.65828in" class="figure-img"></p>
<p></p><figcaption class="figure-caption"><strong>Figure</strong>&nbsp;4<strong>.</strong> A conversation between students in a discussion forum</figcaption><p></p>
</figure>
</div>
<div id="tbl-table1" class="anchored">
<table class="table">
<caption>Table&nbsp;1<strong>.</strong> Edge list of students’ interactions in the discussion forum</caption>
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Source</strong></th>
<th style="text-align: center;"><strong>Target</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">B</td>
<td style="text-align: center;">A</td>
</tr>
<tr class="even">
<td style="text-align: center;">C</td>
<td style="text-align: center;">B</td>
</tr>
<tr class="odd">
<td style="text-align: center;">D</td>
<td style="text-align: center;">C</td>
</tr>
<tr class="even">
<td style="text-align: center;">E</td>
<td style="text-align: center;">D</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F</td>
<td style="text-align: center;">E</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">D</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">A</td>
</tr>
<tr class="even">
<td style="text-align: center;">A</td>
<td style="text-align: center;">C</td>
</tr>
<tr class="odd">
<td style="text-align: center;">D</td>
<td style="text-align: center;">A</td>
</tr>
</tbody>
</table>
</div>
<p>There are other ways to construct the network that depend on the researcher’s conceptualization, context, and research question. For instance, researchers may consider all students present in a discussion (co-present) and therefore linked together, which means that all vertices will have connections to each other <span class="citation" data-cites="Fincham_Gašević_Pardo_2018 Poquet_Saqr_Chen_2021 Saqr_Viberg_Vartiainen_2020">[<a href="#ref-Poquet_Saqr_Chen_2021" role="doc-biblioref">9</a>, <a href="#ref-Saqr_Viberg_Vartiainen_2020" role="doc-biblioref">22</a>, <a href="#ref-Fincham_Gašević_Pardo_2018" role="doc-biblioref">44</a>]</span>. Similarly, several ways exist to aggregate the network. Figure 5 shows three identical networks where we have duplicate ties (i.e., repeated interactions between the same pair of vertices). In <a href="#fig-construct">Figure&nbsp;<span>15.5</span></a> A, all interactions are represented. We can see, for instance, that there are six edges between A and F vertices. We can also see that there is a “loop” or “self-loop” around C and E. A loop exists when an interaction occurs between the vertex and itself, as is the case when one replies to their own post. This type of network configuration where multiple edges and self-loops are allowed is often referred to as <em>multigraph</em>. Another possible way to aggregate the network is to create a weight for each edge which represents the frequency of interactions between each pair of vertices (<a href="#fig-construct">Figure&nbsp;<span>15.5</span></a> B). For instance, the edge between A and F will have a weight of 6 which is the number of edges between A and F, whereas the weight of the edge between H and B is 1 since this interaction only happened once. The network in Figure 5B has an edge with a thickness that corresponds to the weight of 6, i.e., six times as thick as the edge between H and B. In other instances, we may disregard these repeated edges when they do not make a difference to our conceptualization of the network (<a href="#fig-construct">Figure&nbsp;<span>15.5</span></a> C). Such a type of network is often referred to as a simplified network. For a discussion about network configurations and how they influence research results see <span class="citation" data-cites="Saqr_Viberg_Vartiainen_2020">[<a href="#ref-Saqr_Viberg_Vartiainen_2020" role="doc-biblioref">22</a>]</span>.</p>
<div id="fig-construct" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="image5.png" style="width:6.5in;height:2.29093in" class="figure-img"></p>
<p></p><figcaption class="figure-caption"><strong>Figure</strong>&nbsp;5<strong>.</strong> Several ways of constructing a network: A. Multigraph, B. Weighted, C. Simplified.</figcaption><p></p>
</figure>
</div>
</section>
</section>
<section id="network-analysis-in-r" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="network-analysis-in-r"><span class="header-section-number">3</span> Network analysis in R</h2>
<p>The R language has a large number of libraries for the analysis of networks. The <code>igraph</code> package —the one used in our chapter— seems to be the preferred package by the R community given the number of dependencies, i.e., the number of other packages that rely on <code>igraph</code> or work with the <code>igraph</code> format <span class="citation" data-cites="Csárdi_Nepusz_Airoldi_2016 Csardi_Nepusz_Others_2006 Kolaczyk_Csárdi_2020">[<a href="#ref-Csárdi_Nepusz_Airoldi_2016" role="doc-biblioref">45</a>–<a href="#ref-Kolaczyk_Csárdi_2020" role="doc-biblioref">47</a>]</span>. The <code>igraph</code> package is fast, efficient, and well-respected within the academic community. The <code>igraph</code> package is also well maintained, continuously updated, has a large community, and has been released for other platforms besides R, e.g., Python. Other packages, such as sna and network, have a large user base, especially among those who are interested in statistical network modeling. Any of these packages —<code>sna</code>, <code>network</code> or <code>igraph</code>— can effectively perform the analysis described in this chapter. However, we will use <code>igraph</code> based on its relative ease of use and convenience for the chapter objectives.</p>
<p><strong>Example 1</strong></p>
<p>Let us start with a simple example where we analyze the network created for Figure 6. Before doing anything else, we need to import the necessary packages. We will use <code>igraph</code> to construct and represent networks, and we will use rio to download and import the data files that we need to use as an input for <code>igraph</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can now use the import function from rio to download the data for the example (the data shown in Table 1), and assign it to a variable named SNA_example1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>SNA_example1 <span class="ot">&lt;-</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">import</span>(<span class="st">"https://github.com/lamethods/data/raw/main/8_examples/SNA_example1.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The function <code>graph_from_data_frame</code> from <code>igraph</code> converts the edge list in <a href="#tbl-table1">Table&nbsp;<span>15.1</span></a> into a network. R expects a dataframe where the first two columns are used as edges (the first column is used as source column, and the second is used as source column). Please also note that the two columns can have any name. Also, all extra columns —if they are there— will be used as edge attributes. We can print it to see if it has been created correctly. The print function is commonly used to test if the graph creation has been successful. In other words, does the created network have the expected number of vertices, edges, and attributes?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Net <span class="ot">&lt;-</span> <span class="fu">graph_from_data_frame</span>(SNA_example1)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Net)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>IGRAPH 4dcb64e DN-- 6 9 -- 
+ attr: name (v/c)
+ edges from 4dcb64e (vertex names):
[1] B-&gt;A C-&gt;B D-&gt;C E-&gt;D F-&gt;E B-&gt;D C-&gt;A A-&gt;C D-&gt;A</code></pre>
</div>
</div>
<p>The output of the print function gives a glimpse of the network properties. First, <code>igraph</code> states that the object is an <code>igraph</code> object (a network). Then, <code>igraph</code> gives a unique seven-letter identifier for the network (not usually needed for analysis). Next, <code>igraph</code> tells us that the network was directed (D) and named (N), i.e., vertices have a name attribute. Then, <code>igraph</code> lists the attributes and the edges of the network. We can also visualize the created network (<a href="#fig-plot-net">Figure&nbsp;<span>15.6</span></a>) by using the function <code>plot.</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Net)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot-net" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ch15-sna_files/figure-html/fig-plot-net-1.png" class="img-fluid figure-img" style="width:5in"></p>
<p></p><figcaption class="figure-caption"><strong>Figure</strong>&nbsp;6<strong>.</strong> Example of a simple network plotted with <code>igraph</code></figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We have seen here the most basic functions we can use in a graph with no arguments. As shown, networks work with little effort with R. In the next section, we will take a deeper look into these functions and others using another network from a published paper.</p>
<p><strong>Example 2</strong></p>
<p>The next example is a larger network that comes from the interactions of a group of teachers in a Massive Open Online Course (MOOC). The MOOC included 445 participants from different places in the United States. The dataset has an edges file where the first two columns are the sender (<code>source</code>) and receiver (<code>target</code>). There is also a file for the vertices that contains demographic and other relevant information about each vertex: gender, location, and their role, etc. For more information about this dataset, please refer to the data chapter <span class="citation" data-cites="López-Pernas_Saqr_Del_Rio_2024">[<a href="#ref-López-Pernas_Saqr_Del_Rio_2024" role="doc-biblioref">48</a>]</span>. To get the data into R, we first need to read the data, store it in a dataframe and then build a network with the appropriate arguments.</p>
<p>The first line of the code reads the edges list data with their attributes into a dataframe with the name <code>net_edges.</code> The second line imports the vertex data with their attributes into a dataframe with the name net_nodes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>net_edges <span class="ot">&lt;-</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">import</span>(<span class="st">"https://github.com/lamethods/data/raw/main/6_snaMOOC/DLT1%20Edgelist.csv"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>net_nodes <span class="ot">&lt;-</span> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">import</span>(<span class="st">"https://github.com/lamethods/data/raw/main/6_snaMOOC/DLT1%20Nodes.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To create the network, we again use the function <code>graph_from_data_frame</code>. This time we have to specify the edges dataframe using the argument d=net_edges. The second argument (optional) tells <code>igraph</code> that the network should be directed, if not provided, the network is created directed by default. The third argument which is also optional vertices = net_nodes tells <code>igraph</code> to use the dataframe net_nodes for vertex attributes. If the vertices argument is not provided, <code>igraph</code> will extract vertex names from the edges data. In case there are important vertex attributes for the analysis, providing the vertices data can be useful. Building the network and explicitly setting all arguments —as we did— helps avoid the problems that could happen from the default settings of the function. For instance, the network could be created as directed where we aim at creating an undirected network. Note that <code>igraph</code> generates a multigraph network by default (see <a href="#fig-dlt1">Figure&nbsp;<span>15.7</span></a>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>DLT1 <span class="ot">&lt;-</span> <span class="fu">graph_from_data_frame</span>(<span class="at">d=</span>net_edges, <span class="at">directed =</span> <span class="cn">TRUE</span>, <span class="at">vertices =</span> net_nodes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let us now explore the network and see if it was built correctly using the function print. The print function output shows that the network is an <code>igraph</code> object, directed and named (<em>DN</em>) has 445 vertices, 2529 edges and then <code>igraph</code> lists the attributes of the vertices and the edges. Vertex attributes are listed along with their type. For instance, name (v/c) means the name attribute is a (v)ertex attribute and a (<u>c</u>)haracter. Edge attributes are listed in the same way. For instance, timestamp (e/c) means that it is an (e<u>)</u>dge and a (c)haracter.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(DLT1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>IGRAPH 572bc57 DN-- 445 2529 -- 
+ attr: name (v/c), Facilitator (v/n), role1 (v/c), experience (v/n),
| experience2 (v/c), grades (v/c), location (v/c), region (v/c),
| country (v/c), group (v/c), gender (v/c), expert (v/c), connect
| (v/c), Timestamp (e/c), Discussion Title (e/c), Discussion Category
| (e/c), Parent Category (e/c), Category Text (e/c), Discussion
| Identifier (e/c), Comment ID (e/n), Discussion ID (e/n)
+ edges from 572bc57 (vertex names):
 [1] 360-&gt;444 356-&gt;444 356-&gt;444 344-&gt;444 392-&gt;444 219-&gt;444 318-&gt;444 4  -&gt;444
 [9] 355-&gt;356 355-&gt;444 4  -&gt;444 310-&gt;444 248-&gt;444 150-&gt;444 19 -&gt;310 216-&gt;19 
[17] 19 -&gt;444 19 -&gt;4   217-&gt;310 385-&gt;444 217-&gt;444 393-&gt;444 217-&gt;19  256-&gt;219
+ ... omitted several edges</code></pre>
</div>
</div>
<p>A network can also be plotted with the function <code>plot()</code> (<a href="#fig-dlt1">Figure&nbsp;<span>15.7</span></a>). However, plotting with R is a vast field and will not be discussed in detail here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(DLT1,  <span class="at">layout =</span> layout.fruchterman.reingold, </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.size =</span> <span class="dv">5</span>, <span class="at">vertex.label.cex =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dlt1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ch15-sna_files/figure-html/fig-dlt1-1.png" class="img-fluid figure-img" width="1920"></p>
<p></p><figcaption class="figure-caption"><strong>Figure</strong>&nbsp;7<strong>.</strong> Example of a complex network plotted with <code>igraph</code></figcaption><p></p>
</figure>
</div>
</div>
</div>
<section id="graph-level-analysis" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="graph-level-analysis"><span class="header-section-number">3.1</span> Graph level analysis</h3>
<p>Now that we have seen how to build a network from edge and vertex data, we are ready to understand some of the most commonly performed analyses in learning settings. The first type of analysis will look at the network level, or the whole group of collaborators. Analyzing the network level can tell us how interactive the group is, how cohesive, and how distributed the interactions are. We will go through each of these graph-level measures with a brief explanation of what they actually mean. We will use the data from example 1 (<code>DLT1</code>).</p>
<p>Let us first start by calculating the basic measures of the network. The number of vertices can be queried using the function <code>vcount</code>, which adds up to 445, and the number of edges can be queried using the function <code>ecount</code>, which is 2,529. We can get the average number of interactions by a participant by dividing the number edges by the number of vertices which is 5.68.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vcount</span>(DLT1) <span class="do">## 445</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ecount</span>(DLT1) <span class="do">## 2529</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ecount</span>(DLT1) <span class="sc">/</span> <span class="fu">vcount</span>(DLT1) <span class="do">## 5.683146</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The density of a graph is an important parameter of a collaborative network that refers to the ratio of existing edges to the maximum possible among all participants. Density is maximum (1) when every vertex has interacted with every other vertex in the network. Graph density can be measured using the function <code>graph.density</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">graph.density</span>(DLT1) <span class="do">## 0.01279988</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>However, the <code>graph.density</code> function may result in erratic results if the network is multigraph; this is because the <code>igraph</code> algorithm will count the repeated edges and loops. Thus, we need to <em>simplify</em> the network (delete all repeated edges and loops) before computing the density and use the simplified network to compute the graph density. The results of the density of the graph of 0.0097 which is rather a low value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">graph.density</span>(<span class="fu">simplify</span>(DLT1)) <span class="do">## 0.009798563</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Reciprocity is another important graph-level measure that also reflects group cohesion. A reciprocated edge is an edge where two vertices have a reciprocal relationship (e.g., they are simultaneously source and target) <span class="citation" data-cites="Block_2015">[<a href="#ref-Block_2015" role="doc-biblioref">16</a>]</span>. The higher the ratio of the reciprocated edges, the more collaborative the network is, less centralized (dominated by few) and more participatory. Reciprocity can be computed using the function <code>reciprocity</code>, which automatically removes the loops (i.e., does not consider when a person replies to oneself). The reciprocity by <code>igraph</code> definition is the fraction of reciprocated edges in a directed graph. The value here is 0.1997544 which means that only 20% of all edges were reciprocated.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">reciprocity</span>(DLT1) <span class="do">## 0.1997544</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can also compute the dyad.census which returns the number of mutual interactions (reciprocated between a pair of vertices), the number of asymmetric interactions (interactions that are not reciprocated), and the number of non-connected pairs. The number of mutual interactions in our network is 212, which is relatively small given the asymmetric (1512) and non-connected pairs (97066).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dyad.census</span>(DLT1) <span class="do">## $mut [1] 212     $asym [1] 1512     $null [1] 97066</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Transitivity (or global clustering coefficient) measures the tendency of the vertices to cluster together or form tightly knit cliques. In <code>igraph</code>, transitivity is measured as the probability that the neighboring vertices of a vertex are also connected to each other or, more accurately, the ratio of triangles in the network to the total count of triplets (all occurrences of three vertices connected by two edges). There is a large volume of research that associates the ratio of cliques with cohesion in collaborative groups, strong ties and productive knowledge construction Block_2015. There are several methods for the estimation of transitivity. Here, we are going to focus on global transitivity (i.e., at the network-level) using the <code>igraph</code> method. The transitivity can be calculated by the function <code>transitivity</code>; the default function returns the global transitivity measure by default. The transitivity of our network here is 0.08880774.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">transitivity</span>(DLT1) <span class="do">## 0.08880774</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Another possible way is to use the related function <code>triad_census</code> which reports the numbers of triangles and their different types. The reader may need to refer to the package manual to dig deeper in the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">triad_census</span>(DLT1) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 13901588   486626   124805     4227    35745    11186    15929     3668
 [9]      932       81     1857      376      223      334      345       68</code></pre>
</div>
</div>
<p>Group productivity or intensity of interactivity can be explored using the <em>degree</em> measures and its variants. The average <em>degree</em> of the network measures how much on average each group member has contributed and received interactions. To compute the <em>average degree</em>, we first have to compute the <em>degree</em> for each member and then compute the <em>mean</em>.</p>
<p>In directed networks (like the one in this example), we can also compute the average in-degree and out-degree. For the same set of vertices, the network average in-degree should be equal to out-degree and both combined should be equal to the total degree. However, if we, for instance, compute a subset of vertices (only students excluding the teachers), in-degree and out-degree may be different. The code below computes the mean and median of the three measures, using the function <em>degree</em> with the argument <code>mode="total"</code> for the total degree, <code>mode="in"</code> for the <em>in-degree</em>, and mode=“out” for <em>out-degree</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>Mean_degree <span class="ot">&lt;-</span>  <span class="fu">mean</span>(<span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"total"</span>)) <span class="do">## 11.36629</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>Mean_in_degree <span class="ot">&lt;-</span>  <span class="fu">mean</span>(<span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"in"</span>)) <span class="do">## 5.683146</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>Mean_out_degree <span class="ot">&lt;-</span>  <span class="fu">mean</span>(<span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"out"</span>)) <span class="do">## 5.683146 </span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>Median_degree <span class="ot">&lt;-</span>  <span class="fu">median</span>(<span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"total"</span>)) <span class="do">## 4</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>Median_in_degree <span class="ot">&lt;-</span>  <span class="fu">median</span>(<span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"in"</span>)) <span class="do">## 1</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>Median_out_degree <span class="ot">&lt;-</span>  <span class="fu">median</span>(<span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"out"</span>)) <span class="do">## 2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The mean degree is 11.36629 and the mean in-degree and out-degree are 5.683146. The median degree is 4, the median in-degree is 1, and the median out-degree is 2. The median differs significantly from the mean and may be more relevant here in this large network, where participation may not be well-distributed (see next section).</p>
<p>Collaboration is participatory by design but, oftentimes, some students may dominate and contribute disproportionately more than others. In the same vein, some may prefer to be isolated and thus rarely participate. Several measures allow us to measure the distribution of interactions across the network and how skewed the network contribution patterns are. An obvious method that comes straight from statistics is the standard deviation (SD) of the degree centrality. We can compute the SD like we calculated the mean and median in the previous step. The SD of <em>degree</em> centrality in our case is 34.2, SD for in-degree centrality is 26.7, and SD for <em>out-degree</em> centrality is 9.8. The SD is higher than the mean which suggests that calculation and inspection of the median was justified. We can also see that the SD of the <em>in-degree</em> centrality is much higher than the SD of the <em>out-degree,</em> which means that the variability in receiving replies is higher than that of contributions. This variability is rather common since students are selective about whom they respond to and choose the reply-worthy contributions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>SD_degree <span class="ot">&lt;-</span>  <span class="fu">sd</span>(<span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"total"</span>)) <span class="do">## 34.20511</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>SD_in_degree <span class="ot">&lt;-</span>  <span class="fu">sd</span>(<span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"in"</span>)) <span class="do">## 26.73596</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>SD_out_degree <span class="ot">&lt;-</span>  <span class="fu">sd</span>(<span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"out"</span>)) <span class="do">## 9.84249</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>SNA has dedicated indices for measuring dominance in networks, known as centralization indices. Centralization indices are 0 when every vertex contributes equally and reaches the maximum of 1 when a single vertex dominates. A centralization index exists for many centralities —e.g., degree, closeness, and betweenness. Nevertheless, most of the literature has reported degree centralization, which we will demonstrate here.</p>
<p>The code below computes the degree, in-degree and out-degree centralization. Please note that we use a simplified network to avoid the loops and repeated edges. The results of degree centralization confirm the previous results. The degree centralization is 0.38, out-degree centralization is 0.16, and in-degree centralization is 0.60. In our network, we see that the in-degree centralization is the highest index (0.60), which means that only a few students received replies.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>Centralization_degree <span class="ot">&lt;-</span> <span class="fu">centralization.degree</span>(<span class="fu">simplify</span>(DLT1), </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="at">mode =</span>  <span class="st">"all"</span>, <span class="at">loops =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>centralization  <span class="do">## 0.3826871 </span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>Centralization_in_degree <span class="ot">&lt;-</span>  <span class="fu">centralization.degree</span>(<span class="fu">simplify</span>(DLT1), </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="at">mode =</span> <span class="st">"in"</span>, <span class="at">loops =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>centralization    <span class="do">## 0.6064291</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>Centralization_out_degree <span class="ot">&lt;-</span> <span class="fu">centralization.degree</span>(<span class="fu">simplify</span>(DLT1), </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="at">mode =</span>  <span class="st">"out"</span>, <span class="at">loops =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>centralization  <span class="do">## 0.1572214</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Another way to see how the interactions are distributed is to plot the degree distribution using the hist function, as demonstrated in <a href="#fig-hist">Figure&nbsp;<span>15.8</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"in"</span>), <span class="at">breaks =</span> <span class="dv">100</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"out"</span>), <span class="at">breaks =</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-hist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="ch15-sna_files/figure-html/fig-hist-1.png" class="img-fluid figure-img" width="864"></p>
<p></p><figcaption class="figure-caption"><strong>Figure</strong>&nbsp;8<strong>.</strong> Distribution of degree. Left: In-degree. Right: Out-degree</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="network-connectivity" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="network-connectivity"><span class="header-section-number">3.2</span> Network connectivity</h3>
<p>We can also examine how connected the whole group is; this can be performed using the function is.connected which returns <code>FALSE</code> in our case, meaning that the graph has some disconnected components or subgroups of vertices that are isolated. We can check these subgroups by the function components which tells us that there are four components:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.connected</span>(DLT1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>Components <span class="ot">&lt;-</span> <span class="fu">components</span>(DLT1)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Components)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$membership
  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440 
  1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1 
441 442 443 444 445 
  2   3   4   1   1 

$csize
[1] 442   1   1   1

$no
[1] 4</code></pre>
</div>
</div>
<p>Using the function decompose, we can look at each of the components. The largest component has 442 vertices, and three others have one vertex. These isolated vertices are simply students who did not contribute at all and do not represent a real subgroup.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>Decomposed <span class="ot">&lt;-</span> <span class="fu">decompose</span>(DLT1)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>Decomposed[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>IGRAPH e8cd1d2 DN-- 442 2529 -- 
+ attr: name (v/c), Facilitator (v/n), role1 (v/c), experience (v/n),
| experience2 (v/c), grades (v/c), location (v/c), region (v/c),
| country (v/c), group (v/c), gender (v/c), expert (v/c), connect
| (v/c), Timestamp (e/c), Discussion Title (e/c), Discussion Category
| (e/c), Parent Category (e/c), Category Text (e/c), Discussion
| Identifier (e/c), Comment ID (e/n), Discussion ID (e/n)
+ edges from e8cd1d2 (vertex names):
 [1] 360-&gt;444 356-&gt;444 356-&gt;444 344-&gt;444 392-&gt;444 219-&gt;444 318-&gt;444 4  -&gt;444
 [9] 355-&gt;356 355-&gt;444 4  -&gt;444 310-&gt;444 248-&gt;444 150-&gt;444 19 -&gt;310 216-&gt;19 
[17] 19 -&gt;444 19 -&gt;4   217-&gt;310 385-&gt;444 217-&gt;444 393-&gt;444 217-&gt;19  256-&gt;219
+ ... omitted several edges</code></pre>
</div>
</div>
<p>We can also look at the network diameter or largest number of steps between vertices to see how far distant vertices are (using the distance function). A more representative variable would be the average distance between vertices, which we can obtain from the <code>mean_distance</code> function. The network diameter is 8 and the mean distance is 3. Both numbers are relatively high. Global efficiency is another network-level measure that examines how effective is the network structure as a conduit for information exchange using the distances between vertices. When all vertices are <em>close</em> to each other, reachable with a few number of steps, the network is said to be efficient. The value of efficiency is high in well connected groups, and low otherwise. We can examine the efficiency using the function <code>global_efficiency.</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">diameter</span>(DLT1) <span class="do">## 8</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean_distance</span>(DLT1) <span class="do">## 3.030694</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.030694</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">global_efficiency</span>(DLT1) <span class="do">## 0.1961034</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1961034</code></pre>
</div>
</div>
</section>
<section id="network-operations" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="network-operations"><span class="header-section-number">3.3</span> Network operations</h3>
<p>There are many functions and tools to manipulate networks in <code>igraph</code>, which makes a comprehensive discussion of all of them beyond the scope of this introductory chapter. Nonetheless, we will discuss the most important functions. Oftentimes, we need to set an attribute to the vertices —e.g., setting the gender attribute for vertices— to be used in the analysis. Setting an attribute can be performed by using the V function followed by the $ character and the attribute that we want to set. Similarly, setting edge attributes can be done using the function E. In the next example, we define an attribute called <code>weight</code> for the vertices and we do the same for the edges. Using the skills we learnt, we can use them to create a simplified weighted network. We do so by concatenating all repeated edges into a single edge with the weight as the frequency. For that, we start by first assigning weights of 1 to each node and edge. Lastly, we use the function <code>simplify</code> to remove the duplicated edges and aggregate the weights (<code>edge.attr.comb = list(weight = "sum", "ignore")</code>) while all other edge attributes will be <em>ignored</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(DLT1)<span class="sc">$</span>weight <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">E</span>(DLT1)<span class="sc">$</span>weight <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>simple.DLT1 <span class="ot">&lt;-</span> <span class="fu">simplify</span>(DLT1, <span class="at">remove.multiple =</span> <span class="cn">TRUE</span>, <span class="at">remove.loops =</span> <span class="cn">TRUE</span>, </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">edge.attr.comb =</span> <span class="fu">list</span>(<span class="at">weight =</span> <span class="st">"sum"</span>, <span class="st">"ignore"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are two important functions that we may need if we want to divide or create a subnet of the network. The function <code>subgraph.edges</code> allows us to create a subset of a network based on edge characteristics. In the following example, we create a subgraph with the discussions involving <em>Curriculum &amp; Instruction</em> by using the argument <code>E(DLT1)$'Discussion Category'== 'Curriculum &amp; Instruction'</code>. In the same way, the induced_subgraph function allows us to specify a subgraph based on the vertex characteristics. In the next example, we create a network for North Carolina teachers using <code>V(DLT1)$location== "NC"</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">subgraph.edges</span>(DLT1, </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">eids =</span> <span class="fu">which</span>(<span class="fu">E</span>(DLT1)<span class="sc">$</span><span class="st">'Discussion Category'</span> <span class="sc">==</span> <span class="st">'Curriculum &amp; Instruction'</span>))</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>NC_network <span class="ot">&lt;-</span> <span class="fu">induced_subgraph</span>(DLT1, <span class="at">vids =</span> <span class="fu">which</span>(<span class="fu">V</span>(DLT1)<span class="sc">$</span>location <span class="sc">==</span> <span class="st">"NC"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="individual-vertex-measures-centrality-measures" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="individual-vertex-measures-centrality-measures"><span class="header-section-number">3.4</span> Individual vertex measures (centrality measures)</h3>
<p>We have discussed the centrality measures in the introductory section and how they can be used in an educational context. Centrality measures may serve many functions, —e.g., indicators of performance in collaborative environments <span class="citation" data-cites="Saqr_Elmoazen_Tedre_López-Pernas_Hirsto_2022">[<a href="#ref-Saqr_Elmoazen_Tedre_López-Pernas_Hirsto_2022" role="doc-biblioref">49</a>]</span> or indicators for roles in collaboration <span class="citation" data-cites="Marcos-García_Martínez-Monés_Dimitriadis_2015">[<a href="#ref-Marcos-García_Martínez-Monés_Dimitriadis_2015" role="doc-biblioref">21</a>]</span>. The <code>igraph</code> package allows the calculation of several centrality measures, many of which have been used in educational research and some of which may not be relevant. Other packages, such as <code>centiserve</code>, allow an even larger number of centrality measures <span class="citation" data-cites="Jalili_Salehzadeh-Yazdi_Asgari_Arab_Yaghmaie_Ghavamzadeh_Alimoghaddam_2015">[<a href="#ref-Jalili_Salehzadeh-Yazdi_Asgari_Arab_Yaghmaie_Ghavamzadeh_Alimoghaddam_2015" role="doc-biblioref">50</a>]</span>. In this section, we will focus on the common centrality measures according to the recent meta-analysis by <span class="citation" data-cites="Saqr_Elmoazen_Tedre_López-Pernas_Hirsto_2022">[<a href="#ref-Saqr_Elmoazen_Tedre_López-Pernas_Hirsto_2022" role="doc-biblioref">49</a>]</span> and other recently used measures, such as diffusion centrality measures.</p>
<p>Degree centrality measures can be computed using the function <em>degree</em> and the argument <em>mode</em> specifies the type of <em>degree</em> where <code>mode="in"</code> returns <em>in-degree</em>, <code>mode="out"</code> returns <em>out-degree</em>, <code>mode="total"</code> returns total <em>degree</em> centrality. In case of undirected networks, the <em>mode</em> argument is ignored and the function returns only the <em>degree</em> centrality, since there is no direction. We can combine all the centralities that we calculate together in a dataframe using the tibble function from the tibble package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>InDegree  <span class="ot">&lt;-</span> <span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"in"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>OutDegree <span class="ot">&lt;-</span> <span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"out"</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>Degree    <span class="ot">&lt;-</span> <span class="fu">degree</span>(DLT1, <span class="at">mode =</span> <span class="st">"total"</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>Degree_df <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(<span class="at">name =</span> <span class="fu">V</span>(DLT1)<span class="sc">$</span>name, InDegree, OutDegree, Degree)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Degree_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 445 × 4
   name  InDegree OutDegree Degree
   &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
 1 1           20        33     53
 2 2            2         5      7
 3 3            2         4      6
 4 4            2        14     16
 5 5           16        17     33
 6 6            9        24     33
 7 7           32        26     58
 8 8           13        18     31
 9 9            2        12     14
10 10           8        12     20
# ℹ 435 more rows</code></pre>
</div>
</div>
<p>Note that <code>igraph</code> has another function called graph.strength that computes the <em>degree</em> centrality and takes the edge weight attribute into account. In multigraph networks —like ours— <em>degree</em> centrality and <code>graph.strength</code> should return the same result. However, in networks where the edges have a <code>weight</code> attribute both functions (<code>degree</code> and <code>graph.strength</code>) return different results. In such weighted networks —like the simplified network we created in the previous example— the <code>degree</code> function will return the unique connections of every vertex or the size of the vertex direct collaborators —known as the size of the ego network. The <code>graph.strength</code> function will return the number of interactions a vertex has made. See the next example and compare the results. For more information about the different calculation methods of degree centrality of weighted networks, readers are advised to refer to the seminal article by <span class="citation" data-cites="Opsahl_Agneessens_Skvoretz_2010">[<a href="#ref-Opsahl_Agneessens_Skvoretz_2010" role="doc-biblioref">51</a>]</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>InStrength  <span class="ot">&lt;-</span> <span class="fu">graph.strength</span>(DLT1, <span class="at">mode =</span> <span class="st">"in"</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>OutStrength <span class="ot">&lt;-</span> <span class="fu">graph.strength</span>(DLT1,<span class="at">mode =</span> <span class="st">"out"</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>Strength    <span class="ot">&lt;-</span> <span class="fu">graph.strength</span>(DLT1, <span class="at">mode =</span> <span class="st">"total"</span>)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>Strength_df <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(<span class="at">name=</span><span class="fu">V</span>(DLT1)<span class="sc">$</span>name,InStrength,OutStrength,Strength)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Strength_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 445 × 4
   name  InStrength OutStrength Strength
   &lt;chr&gt;      &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;
 1 1             20          33       53
 2 2              2           5        7
 3 3              2           4        6
 4 4              2          14       16
 5 5             16          17       33
 6 6              9          24       33
 7 7             32          26       58
 8 8             13          18       31
 9 9              2          12       14
10 10             8          12       20
# ℹ 435 more rows</code></pre>
</div>
</div>
<p><em>Closeness</em> and <em>betweenness</em> centralities are the most commonly used centrality measures according to <span class="citation" data-cites="Saqr_Elmoazen_Tedre_López-Pernas_Hirsto_2022">[<a href="#ref-Saqr_Elmoazen_Tedre_López-Pernas_Hirsto_2022" role="doc-biblioref">49</a>]</span> and both rely on the position of the vertex on the shortest paths between others. <em>Closeness</em> centrality can be calculated using the function closeness, which is directional; this means that we can compute <em>in-closeness</em>, <em>out-closeness</em> and total <em>closeness</em> centrality. <em>Betweenness</em> centrality can be computed using the function <em>betweenness</em> and the function is directional: the argument <code>directed=TRUE</code> computes the directional version, and vice versa. Another commonly used centrality measure is eigenvector centrality, which can be computed using the function <code>eigen_centrality.</code> The <code>eigen_centrality</code> function default is <code>directed=FALSE</code>, since it is less suited for directed networks <span class="citation" data-cites="Liao_Mariani_Medo_Zhang_Zhou_2017">[<a href="#ref-Liao_Mariani_Medo_Zhang_Zhou_2017" role="doc-biblioref">14</a>]</span>. <em>Pagerank</em> is another closely related centrality measure that uses a similar algorithm and is more suitable for directed networks. The <em>Pagerank</em> centrality can be calculated using the function <code>pagerank.</code> Please note that to obtain the value of the centrality, you need to use <code>$vector</code> at the end as demonstrated in the code.</p>
<p>An important question here is whether to compute these centralities with a simplified network, weighted network or a multigraph network. The answer depends on the context, the network structure and the research question. However, evidence suggests that multigraph configuration may render the most accurate results when centralities are used as indicators for performance <span class="citation" data-cites="Saqr_Viberg_Vartiainen_2020">[<a href="#ref-Saqr_Viberg_Vartiainen_2020" role="doc-biblioref">22</a>]</span>. The code below computes the aforementioned centralities, you may need to read the help of each centrality function for more options and arguments for customization:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>Closeness_In <span class="ot">&lt;-</span> <span class="fu">closeness</span>(DLT1, <span class="at">mode =</span> <span class="fu">c</span>(<span class="st">"in"</span>))</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>Closeness_Out <span class="ot">&lt;-</span> <span class="fu">closeness</span>(DLT1, <span class="at">mode =</span> <span class="fu">c</span>(<span class="st">"out"</span>))</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>Closeness_total <span class="ot">&lt;-</span> <span class="fu">closeness</span>(DLT1, <span class="at">mode =</span> <span class="fu">c</span>(<span class="st">"total"</span>))</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>Betweenness <span class="ot">&lt;-</span> <span class="fu">betweenness</span>(simple.DLT1, <span class="at">directed =</span> <span class="cn">FALSE</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>Eigen <span class="ot">&lt;-</span> <span class="fu">eigen_centrality</span>(simple.DLT1, <span class="at">directed =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>vector</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>Pagerank <span class="ot">&lt;-</span> <span class="fu">page.rank</span>(DLT1, <span class="at">directed =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>vector</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Diffusion</em> centralities have been introduced recently in several studies and seem to offer a more robust estimation of a vertex role in spreading information <span class="citation" data-cites="Saqr_López-Pernas_2021 Saqr_Viberg_2020">[<a href="#ref-Saqr_López-Pernas_2021" role="doc-biblioref">19</a>, <a href="#ref-Saqr_Viberg_2020" role="doc-biblioref">52</a>]</span>. <em>Diffusion</em> centrality can be computed in the same way as degree centrality. However, there is no function in the <code>igraph</code> package to calculate this centrality, so we rely on the <code>diffusion.degree</code> function from the <code>centiserve</code> package. The function <code>diffusion.degree</code> accepts the mode argument to compute different variants, i.e., <code>"in"</code>, <code>"out"</code> and <code>"total"</code> diffusion degrees.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(centiserve)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>Diffusion.degree_in  <span class="ot">&lt;-</span> <span class="fu">diffusion.degree</span>(DLT1, <span class="at">mode =</span> <span class="fu">c</span>(<span class="st">"in"</span>))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>Diffusion.degree_out  <span class="ot">&lt;-</span> <span class="fu">diffusion.degree</span>(DLT1, <span class="at">mode =</span> <span class="fu">c</span>(<span class="st">"out"</span>))</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>Diffusion.degree  <span class="ot">&lt;-</span> <span class="fu">diffusion.degree</span>(DLT1, <span class="at">mode =</span> <span class="fu">c</span>(<span class="st">"all"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Coreness</em> and <em>cross-clique connectivity</em> are related centralities that estimate the embeddedness of the vertex in the network can be calculated using the functions <code>coreness</code> and <code>crossclique.</code> Both <code>coreness</code> and <code>crossclique</code> centralities have been shown to better correlate with performance as well as with productive and reply-worthy content <span class="citation" data-cites="Saqr_López-Pernas_2021">[<a href="#ref-Saqr_López-Pernas_2021" role="doc-biblioref">19</a>]</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>Coreness <span class="ot">&lt;-</span> <span class="fu">coreness</span>(DLT1)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>Cross_clique_connectivity <span class="ot">&lt;-</span> <span class="fu">crossclique</span>(DLT1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cliques(graph): At core/cliques/cliquer_wrapper.c:57 : Edge
directions are ignored for clique calculations.</code></pre>
</div>
</div>
<p>We can also combine the rest of the centralities together in a single dataframe:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>Centdf  <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(<span class="at">name=</span><span class="fu">V</span>(DLT1)<span class="sc">$</span>name,Closeness_total,Betweenness,</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>Eigen,Pagerank,Diffusion.degree,Coreness,Cross_clique_connectivity)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Centdf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 445 × 8
   name  Closeness_total Betweenness   Eigen Pagerank Diffusion.degree Coreness
   &lt;chr&gt;           &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;            &lt;dbl&gt;    &lt;dbl&gt;
 1 1            0.00110       1258.  0.206    0.00840             1865       18
 2 2            0.000808        26.5 0.0107   0.00140              218        6
 3 3            0.000799        30.6 0.00862  0.00130              191        6
 4 4            0.00102         72.5 0.0803   0.00273              965       13
 5 5            0.00106        309.  0.162    0.00525             1508       18
 6 6            0.00108        250.  0.155    0.00539             1607       18
 7 7            0.00111       1935.  0.230    0.00931             2088       21
 8 8            0.00106        164.  0.136    0.00503             1483       18
 9 9            0.00104         69.5 0.119    0.00251             1216       13
10 10           0.00106        716.  0.0875   0.00343             1432       17
# ℹ 435 more rows
# ℹ 1 more variable: Cross_clique_connectivity &lt;int&gt;</code></pre>
</div>
</div>
<p>The calculation of graph level measures and centrality measures are usually a step in the analysis to answer a research question. For instance, density can tell how distributed the interactions between students are and therefore, how it is collaborative <span class="citation" data-cites="Saqr_Nouri_Vartiainen_Tedre_2020">[<a href="#ref-Saqr_Nouri_Vartiainen_Tedre_2020" role="doc-biblioref">5</a>]</span>. Centrality may be calculated to identify who are the most important students in the discussions or used to infer the roles e.g., who are the leaders who drive the discussion <span class="citation" data-cites="Hernández-García_González-González_Jiménez-Zarco_Chaparro-Peláez_2015 Marcos-García_Martínez-Monés_Dimitriadis_2015">[<a href="#ref-Marcos-García_Martínez-Monés_Dimitriadis_2015" role="doc-biblioref">21</a>, <a href="#ref-Hernández-García_González-González_Jiménez-Zarco_Chaparro-Peláez_2015" role="doc-biblioref">23</a>]</span>. Several studies have calculated centrality measures to investigate their relationship with performance <span class="citation" data-cites="Romero_López_Luna_Ventura_2013">[<a href="#ref-Romero_López_Luna_Ventura_2013" role="doc-biblioref">18</a>]</span>. All of such types of analysis can be performed using the analysis we have demonstrated. Of course, there are no limits to the potentials of SNA and researchers have a wide range of possibilities and potentials that they can achieve by building on the aforementioned tutorials.</p>
</section>
</section>
<section id="discussion" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="discussion"><span class="header-section-number">4</span> Discussion</h2>
<p>The present chapter offered a primer on social network analysis as well as a tutorial on the most common types of SNA analysis. SNA is a vast field with diverse applications that are far beyond a chapter or even a whole book. Readers who are interested in expanding their knowledge about SNA are advised to read the literature cited in this chapter. Furthermore, several systematic reviews have tried to offer a synthesis of the extant literature and can help the readers get an idea about the status of SNA research in education. Two systematic reviews, <span class="citation" data-cites="Cela_Sicilia_Sánchez_2015 Sie_Ullmann_Rajagopal_Cela_B._Sloep_2012">[<a href="#ref-Cela_Sicilia_Sánchez_2015" role="doc-biblioref">27</a>, <a href="#ref-Sie_Ullmann_Rajagopal_Cela_B._Sloep_2012" role="doc-biblioref">53</a>]</span>. – despite being relatively old– they give a useful review on the uses and applications of SNA in learning settings. For instance, the methods used by SNA researchers have been addressed in a dedicated systematic review by <span class="citation" data-cites="Dado_Bodemer_2017">[<a href="#ref-Dado_Bodemer_2017" role="doc-biblioref">8</a>]</span>, where the authors offered a detailed review of methodological approaches used in SNA research. Centrality measures were the topic of a recent systematic review and meta-analysis that synthesized the literature and offered evidence of the association of centrality measures with academic achievement <span class="citation" data-cites="Saqr_Elmoazen_Tedre_López-Pernas_Hirsto_2022">[<a href="#ref-Saqr_Elmoazen_Tedre_López-Pernas_Hirsto_2022" role="doc-biblioref">49</a>]</span>.</p>
<p>A more recent scientometric study by <span class="citation" data-cites="Saqr_Poquet_Lopez-Pernas_2022">[<a href="#ref-Saqr_Poquet_Lopez-Pernas_2022" role="doc-biblioref">6</a>]</span> offers a comprehensive review of all research on network analysis and network science across the past five decades. The study also offers a review of authors, countries, research themes and research foundations. Whereas not a traditional systematic review, the recent paper by <span class="citation" data-cites="Poquet_Saqr_Chen_2021">[<a href="#ref-Poquet_Saqr_Chen_2021" role="doc-biblioref">9</a>]</span> offers a review of the seminal papers of SNA with a methodological approach. The paper also offers recommendations for a reporting scheme for research using SNA. It is also important to mention that our chapter covered only static networks. Readers who are interested in the more advanced time varying networks, the temporal network chapter offers a great starting point <span class="citation" data-cites="Saqr_2023">[<a href="#ref-Saqr_2023" role="doc-biblioref">54</a>]</span>. Also several guides and empirical papers demonstrate examples of temporal network analysis <span class="citation" data-cites="Saqr_López-Pernas_2022a Saqr_López-Pernas_2022b Saqr_Nouri_2020">[<a href="#ref-Saqr_López-Pernas_2022a" role="doc-biblioref">20</a>, <a href="#ref-Saqr_López-Pernas_2022b" role="doc-biblioref">55</a>, <a href="#ref-Saqr_Nouri_2020" role="doc-biblioref">56</a>]</span>. Readers who want to go deeper in analysis of learning communities, the community detection chapter can be a good place <span class="citation" data-cites="Hernández-García_Cuenca-Enrique_Traxler_López-Pernas_Conde_Saqr_2024">[<a href="#ref-Hernández-García_Cuenca-Enrique_Traxler_López-Pernas_Conde_Saqr_2024" role="doc-biblioref">57</a>]</span>. Also, for readers interested in the novel methods of psychological networks, they are encouraged to read the psychological network chapter <span class="citation" data-cites="Saqr_Beck_López-Pernas_2024">[<a href="#ref-Saqr_Beck_López-Pernas_2024" role="doc-biblioref">58</a>]</span>.</p>
</section>
<section id="more-reading-resources" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="more-reading-resources"><span class="header-section-number">5</span> More reading resources</h2>
<p>Books related to SNA that the readers can consult are:</p>
<ul>
<li><p>Kolaczyk, E. D., &amp; Csárdi, G. (2014). <em>Statistical analysis of network data with R</em> (Vol. 65). New York: Springer.</p></li>
<li><p>Luke, D. A. (2015). <em>A user’s guide to network analysis in R</em> (Vol. 72, No.&nbsp;10.1007, pp.&nbsp;978-3). New York: Springer.</p></li>
<li><p>Newman, Mark. <em>Networks</em>. Oxford university press, 2018.</p></li>
<li><p>Hanneman, R. A., &amp; Riddle, M. (2005). Introduction to social network methods. (<a href="http://faculty.ucr.edu/~hanneman/nettext/"><u>Link</u></a>)</p></li>
<li><p>Carolan, B. V. (2013). <em>Social network analysis and education: Theory, methods &amp; applications</em>. Sage Publications.</p></li>
<li><p>Network Science by Albert-László Barabási (<a href="http://networksciencebook.com/"><u>Link</u></a>)</p></li>
</ul>
</section>
<section id="acknowledgements" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="acknowledgements"><span class="header-section-number">6</span> Acknowledgements</h2>
<p>This paper is co-funded by the Academy of Finland the project Towards precision education: Idiographic learning analytics (TOPEILA), Decision Number 350560</p>


</section>
<section id="bibliography" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body" role="doc-bibliography">
<div id="ref-Barabási_2013" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Barabási A-L (2013) Network science. Philosophical transactions Series A, Mathematical, physical, and engineering sciences 371:20120375. https://doi.org/<a href="https://doi.org/10.1098/rsta.2012.0375">10.1098/rsta.2012.0375</a></div>
</div>
<div id="ref-Borgatti_Mahra_Brass_Labianca_2009" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Borgatti SP, Mahra A, Brass DJ, Labianca G (2009) Network analysis in the social sciences. Science 323:892–895. https://doi.org/<a href="https://doi.org/10.1126/science.1165821">10.1126/science.1165821</a></div>
</div>
<div id="ref-Saqr_López-Pernas_2022d" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Saqr M, López-Pernas S (2022) How CSCL roles emerge, persist, transition, and evolve over time: A four-year longitudinal study. Computers &amp; education 189:104581. https://doi.org/<a href="https://doi.org/10.1016/j.compedu.2022.104581">10.1016/j.compedu.2022.104581</a></div>
</div>
<div id="ref-Saqr_Nouri_Fors_Viberg_Alsuhaibani_Alharbi_Alharbi_Alamer_2021" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">Saqr M, Nouri J, Fors U, Viberg O, Alsuhaibani M, Alharbi A, Alharbi M, Alamer A (2021) <a href="https://doi.org/10.1007/978-3-030-64877-0_22">How networking and social capital influence performance: The role of long-term ties</a>. In: Antonyuk A, Basov N (eds) Lecture notes in networks and systems. Springer International Publishing, Cham, pp 335–346</div>
</div>
<div id="ref-Saqr_Nouri_Vartiainen_Tedre_2020" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">Saqr M, Nouri J, Vartiainen H, Tedre M (2020) Robustness and rich clubs in collaborative learning groups: A learning analytics study using network science. Scientific reports 10:14445–14461. https://doi.org/<a href="https://doi.org/10.1038/s41598-020-71483-z">10.1038/s41598-020-71483-z</a></div>
</div>
<div id="ref-Saqr_Poquet_Lopez-Pernas_2022" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Saqr M, Poquet O, Lopez-Pernas S (2022) Networks in education: A travelogue through five decades. IEEE access: practical innovations, open solutions 1–1. https://doi.org/<a href="https://doi.org/10.1109/access.2022.3159674">10.1109/access.2022.3159674</a></div>
</div>
<div id="ref-Saqr_Alamro_2019" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">7. </div><div class="csl-right-inline">Saqr M, Alamro A (2019) The role of social network analysis as a learning analytics tool in online problem based learning. BMC medical education 19:1–11. https://doi.org/<a href="https://doi.org/10.1186/s12909-019-1599-6">10.1186/s12909-019-1599-6</a></div>
</div>
<div id="ref-Dado_Bodemer_2017" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">8. </div><div class="csl-right-inline">Dado M, Bodemer D (2017) A review of methodological applications of social network analysis in computer-supported collaborative learning. Educational Research Review 22:159–180. https://doi.org/<a href="https://doi.org/10.1016/j.edurev.2017.08.005">10.1016/j.edurev.2017.08.005</a></div>
</div>
<div id="ref-Poquet_Saqr_Chen_2021" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">9. </div><div class="csl-right-inline">Poquet O, Saqr M, Chen B (2021) Recommendations for network research in learning analytics: To open a conversation. In: Proceedings of the NetSciLA21 workshop</div>
</div>
<div id="ref-López-Pernas_Saqr_Apiola_2023" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">10. </div><div class="csl-right-inline">López-Pernas S, Saqr M, Apiola M (2023) <a href="https://doi.org/10.1007/978-3-031-25336-2_5">Scientometrics: A concise introduction and a detailed methodology for mapping the scientific field of computing education research</a>. In: Apiola M, López-Pernas S, Saqr M (eds) Past, present and future of computing education research : A global perspective. Springer International Publishing, Cham, pp 79–99</div>
</div>
<div id="ref-Saqr_Fors_Tedre_2018" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">11. </div><div class="csl-right-inline">Saqr M, Fors U, Tedre M (2018) How the study of online collaborative learning can guide teachers and predict students’ performance in a medical course. BMC medical education 18:24. https://doi.org/<a href="https://doi.org/10.1186/s12909-018-1126-1">10.1186/s12909-018-1126-1</a></div>
</div>
<div id="ref-Borgatti_Brass_2019" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">12. </div><div class="csl-right-inline">Borgatti SP, Brass DJ (2019) Centrality: Concepts and measures. In: Social networks at work. pp 9–22</div>
</div>
<div id="ref-Ognyanova_2023" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">13. </div><div class="csl-right-inline">Ognyanova K (2023) <a href="https://kateto.net/network-visualization">Static and dynamic network visualization with r</a>. Katya Ognyanova</div>
</div>
<div id="ref-Liao_Mariani_Medo_Zhang_Zhou_2017" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">14. </div><div class="csl-right-inline">Liao H, Mariani MS, Medo M, Zhang Y-C, Zhou M-Y (2017) Ranking in evolving complex networks. Physics reports 689:1–54. https://doi.org/<a href="https://doi.org/10.1016/j.physrep.2017.05.001">10.1016/j.physrep.2017.05.001</a></div>
</div>
<div id="ref-Saqr_López-Pernas_2022c" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">15. </div><div class="csl-right-inline">Saqr M, López-Pernas S (2022) The curious case of centrality measures: A large-scale empirical investigation. Journal of learning analytics 9:13–31. https://doi.org/<a href="https://doi.org/10.18608/jla.2022.7415">10.18608/jla.2022.7415</a></div>
</div>
<div id="ref-Block_2015" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">16. </div><div class="csl-right-inline">Block P (2015) Reciprocity, transitivity, and the mysterious three-cycle. Social networks 40:163–173. https://doi.org/<a href="https://doi.org/10.1016/j.socnet.2014.10.005">10.1016/j.socnet.2014.10.005</a></div>
</div>
<div id="ref-Jo_Park_Lee_2017" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">17. </div><div class="csl-right-inline">Jo I, Park Y, Lee H (2017) Three interaction patterns on asynchronous online discussion behaviours: A methodological comparison. Journal of Computer Assisted Learning 33:106–122. https://doi.org/<a href="https://doi.org/10.1111/jcal.12168">10.1111/jcal.12168</a></div>
</div>
<div id="ref-Romero_López_Luna_Ventura_2013" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">18. </div><div class="csl-right-inline">Romero C, López M-I, Luna J-M, Ventura S (2013) Predicting students’ final performance from participation in on-line discussion forums. Computers &amp; education 68:458–472. https://doi.org/<a href="https://doi.org/10.1016/j.compedu.2013.06.009">10.1016/j.compedu.2013.06.009</a></div>
</div>
<div id="ref-Saqr_López-Pernas_2021" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">19. </div><div class="csl-right-inline">Saqr M, López-Pernas S (2021) Modelling diffusion in computer-supported collaborative learning: A large scale learning analytics study. International journal of computer-supported collaborative learning 16:441–483. https://doi.org/<a href="https://doi.org/10.1007/s11412-021-09356-4">10.1007/s11412-021-09356-4</a></div>
</div>
<div id="ref-Saqr_López-Pernas_2022a" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">20. </div><div class="csl-right-inline">Saqr M, López-Pernas S (2022) <a href="https://doi.org/10.1007/978-3-031-16290-9_55">Instant or distant: A temporal network tale of two interaction platforms and their influence on collaboration</a>. In: Educating for a new future: Making sense of technology-enhanced learning adoption. Springer International Publishing, pp 594–600</div>
</div>
<div id="ref-Marcos-García_Martínez-Monés_Dimitriadis_2015" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">21. </div><div class="csl-right-inline">Marcos-García J-A, Martínez-Monés A, Dimitriadis Y (2015) DESPRO: A method based on roles to provide collaboration analysis support adapted to the participants in CSCL situations. Computers &amp; education 82:335–353. https://doi.org/<a href="https://doi.org/10.1016/j.compedu.2014.10.027">10.1016/j.compedu.2014.10.027</a></div>
</div>
<div id="ref-Saqr_Viberg_Vartiainen_2020" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">22. </div><div class="csl-right-inline">Saqr M, Viberg O, Vartiainen H (2020) Capturing the participation and social dimensions of computer-supported collaborative learning through social network analysis: Which method and measures matter? International Journal of Computer-Supported Collaborative Learning 15:227–248. https://doi.org/<a href="https://doi.org/10.1007/s11412-020-09322-6">10.1007/s11412-020-09322-6</a></div>
</div>
<div id="ref-Hernández-García_González-González_Jiménez-Zarco_Chaparro-Peláez_2015" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">23. </div><div class="csl-right-inline">Hernández-García Á, González-González I, Jiménez-Zarco AI, Chaparro-Peláez J (2015) Applying social learning analytics to message boards in online distance learning: A case study. Computers in human behavior 47:68–80. https://doi.org/<a href="https://doi.org/10.1016/j.chb.2014.10.038">10.1016/j.chb.2014.10.038</a></div>
</div>
<div id="ref-Joksimovic_Manataki_Gaševic_Dawson_Kovanovic_De_Kereki_2016" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">24. </div><div class="csl-right-inline">Joksimovic S, Manataki A, Gaševic D, Dawson S, Kovanovic V, De Kereki IF (2016) Translating network position into performance: Importance of centrality in different network configurations. ACM International Conference Proceeding Series 25-29-Apri:314–323. https://doi.org/<a href="https://doi.org/10.1145/2883851.2883928">10.1145/2883851.2883928</a></div>
</div>
<div id="ref-Reychav_Raban_McHaney_2018" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">25. </div><div class="csl-right-inline">Reychav I, Raban DR, McHaney R (2018) Centrality measures and academic achievement in computerized classroom social networks: An empirical investigation. ACM Journal on Educational Resources in Computing 56:589–618. https://doi.org/<a href="https://doi.org/10.1177/0735633117715749">10.1177/0735633117715749</a></div>
</div>
<div id="ref-Freeman_1978" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">26. </div><div class="csl-right-inline">Freeman LC (1978) Centrality in social networks conceptual clarification. Social networks 1:215–239. https://doi.org/<a href="https://doi.org/10.1016/0378-8733(78)90021-7">10.1016/0378-8733(78)90021-7</a></div>
</div>
<div id="ref-Cela_Sicilia_Sánchez_2015" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">27. </div><div class="csl-right-inline">Cela KL, Sicilia MÁ, Sánchez S (2015) Social network analysis in e-learning environments: A preliminary systematic review. Educational psychology review 27:219–246. https://doi.org/<a href="https://doi.org/10.1007/s10648-014-9276-0">10.1007/s10648-014-9276-0</a></div>
</div>
<div id="ref-Cadima_Ojeda_Monguet_2012" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">28. </div><div class="csl-right-inline">Cadima R, Ojeda J, Monguet JM (2012) <a href="https://pdfs.semanticscholar.org/45fd/589cc4732abbd95b3f1af7ac61640a52a222.pdf">Social networks and performance in distributed learning communities</a>. Educational Technology &amp; Society 15:296–304</div>
</div>
<div id="ref-Cho_Gay_Davidson_Ingraffea_2007" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">29. </div><div class="csl-right-inline">Cho H, Gay G, Davidson B, Ingraffea A (2007) Social networks, communication styles, and learning performance in a CSCL community. Computers and Education 49:309–329. https://doi.org/<a href="https://doi.org/10.1016/j.compedu.2005.07.003">10.1016/j.compedu.2005.07.003</a></div>
</div>
<div id="ref-Liu_Kang_Domanska_Liu_Sun_Fang_2018" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">30. </div><div class="csl-right-inline">Liu Z, Kang L, Domanska M, Liu S, Sun J, Fang C (2018) <a href="https://doi.org/10.5220/0006647600150021">Social network characteristics of learners in a course forum and their relationship to learning outcomes</a>. In: CSEDU 2018 - proceedings of the 10th international conference on computer supported education. SciTePress, [National Engineering Research Center for E-Learning, Central China Normal University, Luoyu Road 152, Wuhan, 430079, China, Department of Computer Science, Humboldt University of Berlin, Rudower Chaussee 25, Berlin, 12489, Germany], pp 15–21</div>
</div>
<div id="ref-Osatuyi_Passerini_2016" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">31. </div><div class="csl-right-inline">Osatuyi BJ, Passerini K (2016) <a href="https://www.scopus.com/inward/record.uri?eid=2-s2.0-85006816496&amp;partnerID=40&amp;md5=50481d9ea30ad0b5cb6116540e0b3c42">Twittermania: Understanding how social media technologies impact engagement and academic performance of a new generation of learners</a>. Commun Assoc Info Syst 39:509–528</div>
</div>
<div id="ref-Putnik_Costa_Alves_Castro_Varela_Shah_2016" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">32. </div><div class="csl-right-inline">Putnik G, Costa E, Alves C, Castro H, Varela L, Shah V (2016) Analysing the correlation between social network analysis measures and performance of students in social network-based engineering education. International Journal of Technology and Design Education 26:413–437. https://doi.org/<a href="https://doi.org/10.1007/s10798-015-9318-z">10.1007/s10798-015-9318-z</a></div>
</div>
<div id="ref-Gašević_Joksimović_Eagan_Shaffer_2019" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">33. </div><div class="csl-right-inline">Gašević D, Joksimović S, Eagan BR, Shaffer DW (2019) SENS: Network analytics to combine social and cognitive perspectives of collaborative learning. Computers in human behavior 92:562–577. https://doi.org/<a href="https://doi.org/10.1016/j.chb.2018.07.003">10.1016/j.chb.2018.07.003</a></div>
</div>
<div id="ref-Saqr_Fors_Nouri_2018" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">34. </div><div class="csl-right-inline">Saqr M, Fors U, Nouri J (2018) Using social network analysis to understand online problem-based learning and predict performance. PloS one 13:e0203590. https://doi.org/<a href="https://doi.org/10.1371/journal.pone.0203590">10.1371/journal.pone.0203590</a></div>
</div>
<div id="ref-Liu_Chai_Liu_Pinkwart_Han_Hu_2019" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">35. </div><div class="csl-right-inline">Liu S, Chai H, Liu Z, Pinkwart N, Han X, Hu T (2019) Effects of proactive personality and social centrality on learning performance in SPOCs. CSEDU 2019 - Proceedings of the 11th International Conference on Computer Supported Education 2:481–487. https://doi.org/<a href="https://doi.org/10.5220/0007756604810487">10.5220/0007756604810487</a></div>
</div>
<div id="ref-De-Marcos_Garciá-López_Garciá-Cabot_Medina-Merodio_Domínguez_Martínez-Herraíz_Diez-Folledo_2016" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">36. </div><div class="csl-right-inline">De-Marcos L, Garciá-López E, Garciá-Cabot A, Medina-Merodio J-AJA, Domínguez A, Martínez-Herraíz JJJ-J, Diez-Folledo T (2016) Social network analysis of a gamified e-learning course: Small-world phenomenon and network metrics as predictors of academic performance. Computers in human behavior 60:312–321. https://doi.org/<a href="https://doi.org/10.1016/j.chb.2016.02.052">10.1016/j.chb.2016.02.052</a></div>
</div>
<div id="ref-Wise_Cui_2018" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">37. </div><div class="csl-right-inline">Wise AF, Cui Y (2018) <a href="https://doi.org/10.1145/3170358.3170403">Unpacking the relationship between discussion forum participation and learning in MOOCs: Content is key</a>. In: ACM international conference proceeding series. Association for Computing Machinery, Learning Analytics Research Network, New York University, 239 Greene Street, 2nd Floor, New York, NY 10003, United States, pp 330–339</div>
</div>
<div id="ref-Liu_Kang_Su_Liu_Sun_2018" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">38. </div><div class="csl-right-inline">Liu Z, Kang L, Su Z, Liu S, Sun J (2018) <a href="https://doi.org/10.1088/1742-6596/1113/1/012021">Investigate the relationship between learners’ social characteristics and academic achievements</a>. In: Journal of physics: Conference series. Institute of Physics Publishing, ["National Engineering Research Center for E-Learning, Central China Normal University, Wuhan, China", <span>“National Engineering Laboratory for Technology of Big Data Applications in Education, Central China Normal University, Wuhan, China”</span>]</div>
</div>
<div id="ref-Kleinberg_1999" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">39. </div><div class="csl-right-inline">Kleinberg JM (1999) Authoritative sources in a hyperlinked environment. Journal of the ACM 46:604–632. https://doi.org/<a href="https://doi.org/10.1145/324133.324140">10.1145/324133.324140</a></div>
</div>
<div id="ref-García-Saiz_Palazuelos_Zorrilla_2014" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">40. </div><div class="csl-right-inline">García-Saiz D, Palazuelos C, Zorrilla M (2014) <a href="https://www.scopus.com/inward/record.uri?eid=2-s2.0-84958542823&amp;doi=10.1007%2F978-3-319-02738-8_15&amp;partnerID=40&amp;md5=ff793d454e0896d85526c5bdbc5e36d4 NS -">Data mining and social network analysis in the educational field: An application for non-expert users</a>. Stud Comput Intell 524:411–439</div>
</div>
<div id="ref-Banerjee_Chandrasekhar_Duflo_Jackson_2013" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">41. </div><div class="csl-right-inline">Banerjee A, Chandrasekhar AG, Duflo E, Jackson MO (2013) The diffusion of microfinance. Science 341:1236498. https://doi.org/<a href="https://doi.org/10.1126/science.1236498">10.1126/science.1236498</a></div>
</div>
<div id="ref-Kang_Molinaro_Kraus_Shavitt_Subrahmanian_2012" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">42. </div><div class="csl-right-inline">Kang C, Molinaro C, Kraus S, Shavitt Y, Subrahmanian VS (2012) <a href="https://doi.org/10.1109/ASONAM.2012.95">Diffusion centrality in social networks</a>. In: 2012 IEEE/ACM international conference on advances in social networks analysis and mining. pp 558–564</div>
</div>
<div id="ref-Kitsak_Gallos_Havlin_Liljeros_Muchnik_Stanley_Makse_2010" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">43. </div><div class="csl-right-inline">Kitsak M, Gallos LK, Havlin S, Liljeros F, Muchnik L, Stanley HE, Makse HA (2010) Identification of influential spreaders in complex networks. Nature physics 6:888–893. https://doi.org/<a href="https://doi.org/10.1038/nphys1746">10.1038/nphys1746</a></div>
</div>
<div id="ref-Fincham_Gašević_Pardo_2018" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">44. </div><div class="csl-right-inline">Fincham E, Gašević D, Pardo A (2018) From social ties to network processes: Do tie definitions matter? Journal of Learning Analytics 5:9–28. https://doi.org/<a href="https://doi.org/10.18608/jla.2018.52.2">10.18608/jla.2018.52.2</a></div>
</div>
<div id="ref-Csárdi_Nepusz_Airoldi_2016" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">45. </div><div class="csl-right-inline">Csárdi G, Nepusz T, Airoldi EM (2016) Statistical network analysis with igraph</div>
</div>
<div id="ref-Csardi_Nepusz_Others_2006" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">46. </div><div class="csl-right-inline">Csardi G, Nepusz T, Others (2006) <a href="https://www.researchgate.net/profile/Gabor-Csardi/publication/221995787_The_Igraph_Software_Package_for_Complex_Network_Research/links/0c96051d301a30f265000000/The-Igraph-Software-Package-for-Complex-Network-Research.pdf">The igraph software package for complex network research</a>. InterJournal, complex systems 1695:1–9</div>
</div>
<div id="ref-Kolaczyk_Csárdi_2020" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">47. </div><div class="csl-right-inline">Kolaczyk ED, Csárdi G (2020) <a href="https://doi.org/10.1007/978-3-030-44129-6">Statistical analysis of network data with r</a>. Springer International Publishing</div>
</div>
<div id="ref-López-Pernas_Saqr_Del_Rio_2024" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">48. </div><div class="csl-right-inline">López-Pernas S, Saqr M, Del Rio L (2024) A broad collection of datasets for educational research training and application. In: Saqr M, López-Pernas S (eds) Learning analytics methods and tutorials: A practical guide using r. Springer, pp in–press</div>
</div>
<div id="ref-Saqr_Elmoazen_Tedre_López-Pernas_Hirsto_2022" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">49. </div><div class="csl-right-inline">Saqr M, Elmoazen R, Tedre M, López-Pernas S, Hirsto L (2022) How well centrality measures capture student achievement in computer-supported collaborative learning? – a systematic review and meta-analysis. Educational Research Review 35:100437. https://doi.org/<a href="https://doi.org/10.1016/j.edurev.2022.100437">10.1016/j.edurev.2022.100437</a></div>
</div>
<div id="ref-Jalili_Salehzadeh-Yazdi_Asgari_Arab_Yaghmaie_Ghavamzadeh_Alimoghaddam_2015" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">50. </div><div class="csl-right-inline">Jalili M, Salehzadeh-Yazdi A, Asgari Y, Arab SS, Yaghmaie M, Ghavamzadeh A, Alimoghaddam K (2015) CentiServer: A comprehensive resource, web-based application and r package for centrality analysis. PloS one 10:e0143111–e0143111. https://doi.org/<a href="https://doi.org/10.1371/journal.pone.0143111">10.1371/journal.pone.0143111</a></div>
</div>
<div id="ref-Opsahl_Agneessens_Skvoretz_2010" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">51. </div><div class="csl-right-inline">Opsahl T, Agneessens F, Skvoretz J (2010) Node centrality in weighted networks: Generalizing degree and shortest paths. Social networks 32:245–251. https://doi.org/<a href="https://doi.org/10.1016/j.socnet.2010.03.006">10.1016/j.socnet.2010.03.006</a></div>
</div>
<div id="ref-Saqr_Viberg_2020" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">52. </div><div class="csl-right-inline">Saqr M, Viberg O (2020) <a href="https://doi.org/10.1007/978-3-030-57717-9_12">Using diffusion network analytics to examine and support knowledge construction in CSCL settings</a>. In: Alario-Hoyos C, Rodríguez-Triana MJ, Scheffe lM, Arnedillo-Sánchez I, S.m. D (eds) Addressing global challenges and quality education. EC-TEL 2020. Lecture notes in computer science. Springer, C, pp 158–172</div>
</div>
<div id="ref-Sie_Ullmann_Rajagopal_Cela_B._Sloep_2012" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">53. </div><div class="csl-right-inline">Sie RLL, Ullmann DT, Rajagopal K, Cela K, B. MB-R, Sloep PB (2012) Social network analysis for technology-enhanced learning: Review and future directions. International Journal of Technology Enhanced Learning 4:172–190. https://doi.org/<a href="https://doi.org/10.1504/IJTEL.2012.051582">10.1504/IJTEL.2012.051582</a></div>
</div>
<div id="ref-Saqr_2023" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">54. </div><div class="csl-right-inline">Saqr M (2023) <a href="http://arxiv.org/abs/2307.12339">Temporal network analysis: Introduction, methods and detailed tutorial with r</a>. arXiv [cs.SI]</div>
</div>
<div id="ref-Saqr_López-Pernas_2022b" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">55. </div><div class="csl-right-inline">Saqr M, López-Pernas S (2022) <a href="https://www.researchgate.net/profile/Mohammed-Saqr/publication/364997941_The_Why_the_What_and_the_How_to_Model_a_Dynamic_Relational_Learning_Process_with_Temporal_Networks/links/636271222f4bca7fd0270b74/The-Why-the-What-and-the-How-to-Model-a-Dynamic-Relational-Learning-Process-with-Temporal-Networks.pdf">The why, the what and the how to model a dynamic relational learning process with temporal networks</a>. In: Proceedings of the NetSciLA22 workshop</div>
</div>
<div id="ref-Saqr_Nouri_2020" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">56. </div><div class="csl-right-inline">Saqr M, Nouri J (2020) <a href="https://doi.org/10.1145/3375462.3375501">High resolution temporal network analysis to understand and improve collaborative learning</a>. In: Proceedings of the tenth international conference on learning analytics &amp; knowledge. ACM, New York, NY, USA, pp 314–319</div>
</div>
<div id="ref-Hernández-García_Cuenca-Enrique_Traxler_López-Pernas_Conde_Saqr_2024" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">57. </div><div class="csl-right-inline">Hernández-García Á, Cuenca-Enrique C, Traxler A, López-Pernas S, Conde MÁ, Saqr M (2024) Community detection in r. In: Saqr M, López-Pernas S (eds) Learning analytics methods and tutorials: A practical guide using r. Springer, pp in–press</div>
</div>
<div id="ref-Saqr_Beck_López-Pernas_2024" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">58. </div><div class="csl-right-inline">Saqr M, Beck E, López-Pernas S (2024) Psychological networks. In: Saqr M, López-Pernas S (eds) Learning analytics methods and tutorials: A practical guide using r. Springer, pp in–press</div>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/ch14-process-mining/ch14-process.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Process mining</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/ch16-community/ch16-comm.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Community detection</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
      <div class="nav-footer-center"><div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
  </div>
</footer>
<script>
  document.querySelector(".quarto-title").innerHTML =  '<div class="badge bs-warning bg-warning text-dark" style="float:right;">Pre-print</div>' +  document.querySelector(".quarto-title").innerHTML
  var keywords = document.querySelector('meta[name="keywords"]')
  if (keywords && keywords.content) {
    document.getElementById("title-block-header").innerHTML = document.getElementById("title-block-header").innerHTML + 
      '<div class="abstract"><div class="abstract-title">Keywords</div><div class="quarto-title-meta-contents"><p>'+
      keywords.content +
      '</p></div></div>'
  }
</script>



</body></html>