{
  "hash": "68af0fbf258f1c549cad9234359e5622",
  "result": {
    "markdown": "---\ntitle: \"Artificial Intelligence: Using Machine Learning to Predict Students' Performance\"\nformat: html\nexecute:\n  message: FALSE\nauthor: \n   - name: \"Mohammed Saqr\"\n   - name: \"Kamila Misiejuk\"\n   - name: \"Santtu Tikka\"\n   - name: \"Sonsoles López-Pernas\"\ncrossref:\n  fig-title: '**Figure**'\n  fig-labels: arabic\n  title-delim: \"**.**\"\nabstract-title: \"Abstract\"\nabstract: \"Being able to predict students' performance has been a primary driver for the adoption of learning analytics and has attracted many scientists to the field. Predictive modeling focuses on using students' data to forecast outcomes such as student grades, enabling teachers and administrators to offer just-in-time support to students at risk. This chapter uses advanced predictive methods, namely machine learning, where the goal is to predict continuous variables like grades. The chapter uses advanced and popular AI/machine learning algorithms like Random Forest, K-Nearest Neighbor, Linear Regression, Neural Networks, and Support Vector Machines. The chapter provides a practical guide to building and evaluating predictive models with R using two approaches: one is the classic approach for predictive modeling with R, and the other more modern approach using the `tidymodels` suite.\"\nkeywords: \"learning analytics, predictive modeling, artificial intelligence, regression\"\ndpi: 900\neditor: source\nbibliography: ../references.bib\nkeep-tex: true\nextract-media: \"img\"\n---\n\n\n## Introduction\n\nPredicting student performance is one of the most common tasks in learning analytics [@LABOOK2_Chapter_2]. Typically, student grades are used as an outcome variable of such modeling. Predicting a continuous variable like grades is called a regression problem, in contrast with classification that deals with nominal outcomes such as high and low achievers [@LABOOK2_Chapter_4]. When we do predictive modeling, we assume that historical data can be used to build a model to predict the future using new data. In doing so, prediction goes beyond reporting what has happened but attempts to explain why an event happened, monitor what is currently happening and also attempts to foresee future developments [@eckerson2007predictive]. As such, it provides a basis for actionable insights based on data or what we call data-informed decision making. This is particularly relevant for scaling up learning analytics applications. As such prediction has become a core step within the learning analytics process that aims to improve teaching or learning [@pardo2014designing].\n\nThere are six main steps in predictive analytics [@brooks2017predictive]. First, the problem needs to be specified (e.g., improving student performance). Second, an outcome variable is defined (e.g., student grades), and data that can potentially predict the outcome variable is collected. Several types of data can be collected: prior academic data (e.g., student admission information), demographic data (e.g., student's socio-economic status), academic data (e.g., results of formative assessment), behavioral data (e.g., student log data), and psychological data (e.g., a survey on student motivation) [@sghir2023recent]. Third, raw data needs to be pre-processed to become suitable for modeling. This can include formatting the data or deriving features from raw data (e.g., calculating time spent in an online system by subtracting log-out time from log-in time) (see [@kopra2024r] for more details on data cleaning and wrangling). In order to choose the appropriate predictors for the predictive model, an exploratory analysis is conducted (see [@tikka2024introductory] for a tutorial in exploratory methods). Once the relevant indicators are selected, a predictive model can be built using one or more algorithms. The selection of an appropriate algorithm is determined by “the problem type, the nature of the outcome to be predicted, and the variables employed in the prediction” [@sghir2023recent]. Typically, several algorithms would be compared to choose the method that models the data most accurately. The results from a predictive analysis can be used to develop preventive measures and interventions. Depending on the timing of the analysis, these interventions can be implemented on the current cohort of students, or the insights from the analytics can be used to shape future teaching and learning. Finally, it is important to build explainable prediction models ---i.e., that provide an explanation for how a prediction was calculated--- in order to increase the trust of the stakeholders in the model and increase awareness of what the model is actually predicting. In addition, explainable models can help validate model accuracy [@dabhade2021educational]. An example of an explainable predictive model is [@pardo2016generating], who used data from formative assessment activities (e.g., the number of correct or incorrect answers to a question) to generate two predictions: of a grade in the midterm exam (on a scale of 0--20) and of a final grade (on a scale 0--40). The predictive model used the decision tree (DT) algorithm that supports the instructor’s sense-making and helps identify student groups in need of additional support.\n\nThe goal of this chapter is to explore advanced techniques of predictive analytics to model regression problems (see [@jovanovic2024predictive] for an introductory tutorial in predictive analytics). It is assumed that the reader is familiar with the R programming language. If that is not the case, it is recommended to refer to previous tutorials on the basics of R [@Tikka2024-ph], data cleaning [@Kopra2024-fx], basic statistics [@Tikka2024-wl], and visualization [@Lopez-Pernas2024-ge]. The following section presents an overview of learning analytics research concerned with regression. Next, a synthetic dataset used in this tutorial is presented based on data of this study [@saqr2022]. The tutorial section starts with an exploratory data analysis, including visualizing variable distribution and calculating correlations. It is followed by a description of the steps needed to create a predictive model. This tutorial explores the following predictive methods: Random Forest (RF), K-Nearest Neighbor (KNN), Linear Regression (LR), Neural Networks (NN), and Support Vector Machine (SVM). In addition, techniques to determine predictive model performance, such as Mean Absolute Error (MAE), Root-mean-square deviation (RMSE), and R-squared (RSQ), are presented and explained. The final part of this chapter shows how to create workflows to use multiple predictive algorithms.\n\n## Previous research on student performance prediction\n\n[@tomasevic2020overview] described three categories of regression techniques: 1) similarity-based approaches that are built upon identifying similar patterns in a dataset (e.g., KNN), 2) model-based approaches are developed by estimating implicit correlation among data samples and predictors (e.g., SVM, NN, DT, LR), 3) probabilistic approaches focus on examining probability distributions in the input dataset (e.g., Bayesian LR). Regression is the most commonly applied method in predictive analysis, while predicting student performance is one of the main regression problems prevalent in learning analytics research [@du2021systematic]. The vast majority of learning analytics papers focus on predicting student final grades [@du2021systematic]. Predictions in learning analytics are conducted in two main ways: 1) formative prediction examines student features at several points in the duration of the learning activity to provide several predictions over time, and 2) summative prediction aggregates data from the whole learning activity to predict the final outcome [@namoun2020predicting; @saqr2017learning; @Saqr2024-ie]. In addition, different levels of learning activity can be specified, e.g., degree, year, course, or exam level [@alyahyan2020predicting]. Log activity data is typically combined with other data sources, such as demographic or self-reported data [@du2021systematic]. Current evidence suggests that engagement level expressed through participation frequencies has a positive effect on performance [@du2021systematic]. Prior academic data, such as grades achieved in previous courses, was found to be the most influential factor in predicting student performance. An interesting meta-analytics study conducted by [@saqr2022] to examine the reliability of predictors across courses found that overall engagement with online tasks and collaborative learning activities (measured by total activity and forum indicators) showed the highest prediction ranges, indicating their reliability as metrics. Lecture reading frequency had insignificant prediction ranges, suggesting limited applicability across courses.\n\nPredictive modeling can be challenging sometimes, specially when using low quality data for analysis or having a shallow understanding of the nature of the data and therefore can lead to untrustworthy findings. As learning processes are dynamic, using results from historical data to model current learners can be inaccurate and lead to the over-fitting or under-fitting of statistical models [@mathrani2021perspectives]. These issues can be mitigated by applying methods such as cross-validation or bootstrapping [@pardo2014designing; @mathrani2021perspectives; @winne2020construct]. Another problem in predictive analytics is imbalanced datasets, where specific important values are not sufficiently represented in a dataset. This issue can be mitigated by over- or undersampling (for more details, see [@avelino2024resampling]). In addition, it is crucial to approach the findings from a point-in-time perspective that takes into consideration the temporality aspect of the findings’ accuracy [@winne2020construct; @saqr2020]. Also, it is important to consider the ethical implications of implementing predictive learning analytics so as not to cause harm to students or contribute to perpetuating social injustices [@rets2023six;@saqr2017big]. [@tomasevic2020overview] identified three main issues with implementing predictive learning analytics. First, the issue of a cold start relates to the lack of data at the early stages of learning analytics deployment. This challenge can be mitigated by including demographic data or previous academic data. Second, the issue of scalability is connected to the increasing number of students, the complexity of algorithms used, and the computational requirements necessary to perform analytics. To address this issue, time constraints on the analysis or algorithm optimization need to be performed. Third, the issue of data sparsity refers to the lack of sufficient data about student activities, which can be caused by offline learning activities or passive interactions with available online learning systems. In order to increase available data, online learning activities can be made mandatory and embedded into a course design.\n\nDecisions regarding which data to collect, which features to select, which algorithm to use to build a predictive model, or how to evaluate model performance depend on the available data, dataset size, and study context [@saqr2022]. A substantial body of research compares the performance of different predictive algorithms. For example, [@alshehri2017student] collected student demographic and socio-economic data, self-reported motivation level, and assessment data from two evaluations during a semester. The authors predicted the student’s final grade (on a scale of 0--20) using the KNN and SVM algorithms. The performance of both algorithms was evaluated using 10-fold cross-validation and direct partition in the ratio methods, and it was found that SVM outperformed KNN. In another example, [@nguyen2024applying] collected student log data from a learning management system, such as the number of system logins the number of posts, or quiz grades, to model final exam grades using SVM and LR algorithms. The predictions were made multiple times during a semester and shown to the teacher. In this study, LR performed better than SVM, and the goodness-of-fit measure, R-squared, increased with each prediction in the semester. In addition, feature selection decreased model performance. [@tomasevic2020overview] predicted student scores on the final exam (on a scale of 0--110) using KNN, SVM, Artificial NN, DT, Bayesian Regression, and LR. The dataset includes demographic data (e.g., gender, age), engagement data (sum of clicks), and performance data (e.g., scores per assessment). Artificial NN using engagement data and performance data had the highest precision out of all models. Including demographic data did not improve model precision significantly.\n\nOther papers focused on determining the most important features that predict the outcome variable. For example, [@jo2015relations] collected LMS activity data, such as login frequency or number of student posts, and student assignment and assessment grades to predict student final grades using multiple linear regression. The results showed that total login frequency in LMS, regularity of learning interval in LMS, and total assignments and assessment composites predicted the final grades. [@cavazos2018learning] collected two datasets: 1) where historical academic grades were available and limited demographic data was used; 2) where historical academic grades were not available, while demographic and socioeconomic data were extensively used. The SVM algorithm was applied to predict students’ high school final grades using both datasets. The authors reported greater errors in the case of the dataset without historical academic grades than in the dataset with historical academic grades.\n\nFinally, the issue of transferring predictive models within the same learning context and across different learning contexts was explored in the learning analytics research [@saqr2022; @Jovanovic2021-et; @conijn2017]. For example, [@gavsevic2016learning] examined the relationship between LMS log data and final grade (on a scale of 0--100%) after adjusting to student characteristics. In addition, separate multiple linear regression models were developed to compare different courses. The study found that the impact of LMS features varied significantly on student performance across courses. The work by [@Jovanovic2021-et] applied mixed effect linear regression models to analyze a sample of data from log data from 15 courses that were homogeneous regarding the institutional settings, discipline, nominal learning design, and course size. The results highlighted that the same pedagogical model and study setting did not guarantee the same predictive power among courses, as there may be differences in the practical implementation of specific pedagogical models. In addition, it was found that the overall time spent in an LMS, regular discussion forum posts, and accessing course materials regularly were significant predictors of student final course grades across all courses.\n\n## Performance prediction with R\n\nIn this section we present two approaches to implement performance prediction in R: one following a more classic procedure, and the second one following a more updated procedure based on `tidymodels`. Broadly, the workflow followed is depicted in @fig-workflow, aligned with the common steps that are performed in any ML pipeline. First, we explore the data to gain an idea of the magnitude, format and content of the data, explore the relationships between the different variables, etc. This step is called exploratory data analysis. Next, we prepare the data (B) for subsequent steps. This might include removing or fixing incomplete records, converting data to different types, unifying values that are close to one another, or rescaling the data. The transformations that we need to do are commonly dictated by the type of data and the ML models that we will be using in subsequent steps. After data preparation, the next step is data splitting (C). Here, the dataset is divided into training and testing sets. The training set is used to fit the model, while the testing set is reserved for evaluating its performance. It is crucial to ensure that the testing set remains untouched until the evaluation stage to provide an unbiased estimate of the model's generalization ability. Once the data is split, the process moves to model fitting (D). During this stage, the training data is used to train the selected machine learning models. This involves finding the optimal parameters that minimize error or maximize predictive accuracy for the given task. Depending on the algorithm, the model may identify different patterns, such as decision boundaries or relationships between features and the target variable. Finally, in the model evaluation step (E), the trained model is tested on the unseen testing data. Performance metrics that quantify  the degree of error in the numeric predictions are computed to determine how well the model performs on new data. This step ensures that the model is not overfitting the training data and can generalize well to other datasets. We can repeat this process for several models with different underlying ML algorithms, or using only a subset of features of the data and compare the performance metrics among different models to select the one with the best fit.\n\n![ML workflow implemented in the tutorial](workflow.png){#fig-workflow}\n\n### The dataset used in this chapter\n\nThe dataset we are using to illustrate the methods in this tutorial is a synthetic dataset based on the study by Jovanović et al. [@Jovanovic2021-et] and consists mostly of behavioral engagement indicators that can be obtained from learning management system (LMS) trace-log data. These variables capture both the engagement behavior of students (e.g., frequency and regularity of course and forum activities) and their participatory and time investment in the course (e.g., total duration, active days, session count) as well as the regularity of participation. Both time and regularity may be considered proxy indicators of cognitive engagement. We can also consider forum contributions as indicators of cognitive engagement since the context is problem-based learning, and student contributions require students to read, synthesize, critique, and formulate arguments @Saqr2023-vs.\n\nThe dataset has the following variables:\n\n-   **Frequency Variables**\n    -   **Freq_Course_View**: The frequency of course page views by the student.\n    -   **Freq_Forum_Consume**: The frequency with which the student consumes content in the forum (i.e., reads forum posts).\n    -   **Freq_Forum_Contribute**: The frequency with which the student contributes to the forum (i.e., posts in the forum).\n    -   **Freq_Lecture_View**: The frequency of lecture video views by the student.\n-   **Regularity Variables**\n    -   **Regularity_Course_View**: The consistency of the student's course page views.\n    -   **Regularity_Lecture_View**: The consistency of the student's lecture video views.\n    -   **Regularity_Forum_Consume**: The consistency of the student's forum content consumption.\n    -   **Regularity_Forum_Contribute**: The consistency of the student's forum contributions.\n-   **Time Variables**\n    -   **Session_Count**: The total number of sessions the student has participated in.\n    -   **Total_Duration**: The total duration (in seconds) of all sessions participated by the student.\n    -   **Active_Days**: The number of days the student was active in the course.\n-   **Outcome Variables**\n    -   **Final_Grade**: The final grade of the student in the course.\n\n#### Exploratory Data Analysis\n\nExploratory data analysis (EDA) is usually performed before doing the actual machine learning tasks (@fig-workflow–A). EDA includes examining the characteristics of the dataset to understand the distribution of the variables, and identify patterns and inconsistencies, if they may arise. Exploring the distribution and variance of each variable helps us identify any skewness, outliers, or anomalies in the data. Furthermore, EDA also allows us to examine the presence of missing values ---or lack thereof---, handle distribution inconsistencies, and transform variables to balance their characteristics if needed. For instance, if we find that our variables have different measurement scales (one is measured in large numbers with vast variance and another in proportions and ranges between 0 and 1), we may need to transform or normalize the data to ensure that the two variables are not largely different. This process is particularly needed in some algorithms that are sensitive to discrepancies between variables. Additionally, we may have variables that are highly correlated (e.g., each is more or less a copy of the other), we may need to discard one of these similar variables as they do not offer any added information to the model and may bias the estimates. It should be mentioned that standardization will often result in less (direct) interpretability of the model, for example, when predicting final grade, there will be negative grades (below average) which might be hard to interpret, and also regression coefficients may be tricky to interpret. If standardization is carried out, the results may be presented on the original scales for better interpretation.\n\n\n\n\n\nThe first step in EDA is to load the R packages and use them to explore the data. We will need several R packages. Firstly, we will need `tidyverse`: a set of R packages designed to make it easy to read, edit, manipulate and visualize data through a large collection of functions for filtering, selecting and modifying the data [@tidyverse]. As a collection of packages, `tidyverse` includes packages such as `dplyr` and `tidyr` for data manipulation and `ggplot2` for data visualization, among others. The `skimr` package provides an easy, yet comprehensive, summary of a dataset with more detail than most R built-in summary functions [@skimr]. The `skimr` package offers central tendency statistics like mean and median as well as the number and proportion of missing values for each variable, making it easy to get an overview of the data and detect any anomalies or patterns quickly. Besides, `skimr` calculates variance measures, maximum, minimum and displays a miniature histogram for each variable. The `correlation` package is an easy-to-use package for estimating and visualizing several types of correlations. We will need the package `correlation` to visualize the correlation between variables. In particular, it will be used to create a heatmap to understand relationships between variables [@correlation]. We will also use the package `rio` to import the data into our code [@rio]. Lastly, we will use the `performance` package to evaluate our predictive models [@Ludecke2021-li].\n\nThe next code starts by loading the R packages and reading the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required libraries\nlibrary(tidyverse)\nlibrary(correlation)\nlibrary(skimr)\nlibrary(rio)\nlibrary(performance)\n\nstudent_data <- import(\"https://github.com/lamethods/data2/raw/main/lms/lms.csv\")\n```\n:::\n\n\nThe previous R code imports student data from a CSV file. Next, the following EDA tasks will be performed: 1) provide a detailed summary of the data using `skimr`, 2) create histograms for all variables to examine their distribution, 3) calculate and visualize correlations between variables, and 4) extract and display correlations with the final grade of the course (`Final_Grade`). \n\nIn our EDA, first, we get a quick and comprehensive overview of the dataset using the `skim` function from the `skimr` package. The function provides detailed information such as the number of rows, number of columns, type of variables, and most importantly, the number of missing values (`n_missing`). `skimr` also provides basic statistics for each variable like mean, standard deviation (sd), minimum (p0) and maximum (p100), first quartile (p25), median (p50), third quartile (p75), and a small histogram of the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. A detailed summary using skimr\nskim(student_data)\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |             |\n|:------------------------|:------------|\n|Name                     |student_data |\n|Number of rows           |285          |\n|Number of columns        |12           |\n|_______________________  |             |\n|Column type frequency:   |             |\n|numeric                  |12           |\n|________________________ |             |\n|Group variables          |None         |\n\n\n**Variable type: numeric**\n\n|skim_variable               | n_missing| complete_rate|     mean|       sd|       p0|      p25|      p50|      p75|      p100|hist  |\n|:---------------------------|---------:|-------------:|--------:|--------:|--------:|--------:|--------:|--------:|---------:|:-----|\n|Freq_Course_View            |         0|             1|   223.79|    59.33|    51.00|   187.00|   222.00|   264.00|    356.00|▁▃▇▇▂ |\n|Freq_Forum_Consume          |         0|             1|   582.55|   175.55|    84.00|   465.00|   589.00|   703.00|    991.00|▁▅▇▇▂ |\n|Freq_Forum_Contribute       |         0|             1|   178.07|    55.57|    17.00|   144.00|   175.00|   213.00|    347.00|▁▅▇▃▁ |\n|Freq_Lecture_View           |         0|             1|   201.87|    56.68|    32.00|   162.00|   202.00|   247.00|    346.00|▁▃▇▆▁ |\n|Regularity_Course_View      |         0|             1|     0.51|     0.14|     0.15|     0.42|     0.52|     0.61|      0.90|▂▅▇▅▁ |\n|Regularity_Lecture_View     |         0|             1|     0.48|     0.15|     0.07|     0.38|     0.49|     0.57|      0.80|▁▅▇▇▃ |\n|Regularity_Forum_Consume    |         0|             1|     0.49|     0.14|     0.13|     0.41|     0.50|     0.58|      0.95|▁▅▇▂▁ |\n|Regularity_Forum_Contribute |         0|             1|     0.48|     0.16|     0.03|     0.38|     0.47|     0.59|      0.90|▁▃▇▅▂ |\n|Session_Count               |         0|             1|   189.54|    52.83|    53.00|   151.00|   191.00|   229.00|    306.00|▂▅▇▇▂ |\n|Total_Duration              |         0|             1| 83150.98| 23818.16| 25055.00| 68632.00| 83667.00| 98373.00| 147827.00|▂▆▇▅▁ |\n|Active_Days                 |         0|             1|    16.06|     4.15|     5.00|    14.00|    16.00|    19.00|     31.00|▂▆▇▂▁ |\n|Final_Grade                 |         0|             1|    68.62|     8.86|    44.73|    62.42|    68.66|    75.26|     90.89|▁▆▇▇▁ |\n:::\n:::\n\n\n\nThe results of the `skim(student_data)` command show that the data has 285 observations and no missing data in any variable. However, the variables have large differences in variance. For instance, the frequency variables are different from the regularity variables which are all below 1 and even more different if we compared them to the duration which has a mean of 83150.98 (SD = 23818.16). This information tells us that data may need to be normalized if the algorithm that we choose is sensitive to differences in variance.\n\nThe second step is to inspect the distribution of all variables (@fig-histall) using the following code, which starts by using `pivot_longer(everything())` to reshape our data, putting all variables into a single column. This makes it easier to create a faceted plot (multiple plots). We use `ggplot2` to create histograms for each variable. The `facet_wrap(~ name, scales = \"free\")` line creates a separate plot for each variable, and `scales = \"free\"` allows each plot to have its own horizontal and vertical scales, which is often necessary when dealing with variables of different types or ranges and scales of measurement. For a tutorial about data visualization with R, refer to @Lopez-Pernas2024-ge.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2. Histograms of all variables\nstudent_data |>\n  pivot_longer(everything()) |>\n  ggplot(aes(x = value)) +\n  geom_histogram(bins = 25, fill = \"skyblue\", color = \"black\") +\n  facet_wrap(~ name, scales = \"free\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Histograms of all variables](ch03-prediction_files/figure-html/fig-histall-1.png){#fig-histall width=960}\n:::\n:::\n\n\nThe third step is to look at the correlations between variables (@fig-corr). This allows us to see if there are any variables that are highly correlated to each other. If there are variables that are perfectly or almost perfectly correlated, they might be redundant or linear combinations of one another and therefore, do not add much to the model. The heatmap shows that most variables have correlations below the 0.8 level, and only a few cross this level. We may also examine the correlation with the final grade (our outcome variable that we want to predict) to explore variable importance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 3. Relationship between Variables and `Final_Grade`\n# Calculate correlations with `Final_Grade`\ncorrelations <- correlation(student_data, method = \"pearson\")\ncorrelations |> summary() |> plot() + \n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))\n```\n\n::: {.cell-output-display}\n![Correlations between Variables and `Final_Grade`](ch03-prediction_files/figure-html/fig-corr-1.png){#fig-corr width=864}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract and display correlations with `Final_Grade`\nfinal_grade_correlations <- correlations |>\n  as.data.frame() |>\n  filter(Parameter2 == \"Final_Grade\") |>\n  arrange(desc(r))\n\n# Print the correlations with `Final_Grade`\nfinal_grade_correlations\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Parameter1\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Parameter2\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"r\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"CI\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"CI_low\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"CI_high\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"t\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"df_error\"],\"name\":[8],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"p\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Method\"],\"name\":[10],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"n_Obs\"],\"name\":[11],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Freq_Forum_Contribute\",\"2\":\"Final_Grade\",\"3\":\"0.58\",\"4\":\"0.95\",\"5\":\"0.50\",\"6\":\"0.65\",\"7\":\"12.0\",\"8\":\"283\",\"9\":\"0.00000000000000000000000019\",\"10\":\"Pearson correlation\",\"11\":\"285\"},{\"1\":\"Freq_Forum_Consume\",\"2\":\"Final_Grade\",\"3\":\"0.51\",\"4\":\"0.95\",\"5\":\"0.42\",\"6\":\"0.59\",\"7\":\"10.0\",\"8\":\"283\",\"9\":\"0.00000000000000000066613921\",\"10\":\"Pearson correlation\",\"11\":\"285\"},{\"1\":\"Session_Count\",\"2\":\"Final_Grade\",\"3\":\"0.51\",\"4\":\"0.95\",\"5\":\"0.42\",\"6\":\"0.59\",\"7\":\"10.0\",\"8\":\"283\",\"9\":\"0.00000000000000000086312557\",\"10\":\"Pearson correlation\",\"11\":\"285\"},{\"1\":\"Total_Duration\",\"2\":\"Final_Grade\",\"3\":\"0.47\",\"4\":\"0.95\",\"5\":\"0.38\",\"6\":\"0.56\",\"7\":\"9.1\",\"8\":\"283\",\"9\":\"0.00000000000000063999009220\",\"10\":\"Pearson correlation\",\"11\":\"285\"},{\"1\":\"Regularity_Course_View\",\"2\":\"Final_Grade\",\"3\":\"0.45\",\"4\":\"0.95\",\"5\":\"0.35\",\"6\":\"0.54\",\"7\":\"8.5\",\"8\":\"283\",\"9\":\"0.00000000000004001787832721\",\"10\":\"Pearson correlation\",\"11\":\"285\"},{\"1\":\"Active_Days\",\"2\":\"Final_Grade\",\"3\":\"0.42\",\"4\":\"0.95\",\"5\":\"0.32\",\"6\":\"0.51\",\"7\":\"7.8\",\"8\":\"283\",\"9\":\"0.00000000000324249753863009\",\"10\":\"Pearson correlation\",\"11\":\"285\"},{\"1\":\"Freq_Course_View\",\"2\":\"Final_Grade\",\"3\":\"0.40\",\"4\":\"0.95\",\"5\":\"0.30\",\"6\":\"0.50\",\"7\":\"7.4\",\"8\":\"283\",\"9\":\"0.00000000002385564255088207\",\"10\":\"Pearson correlation\",\"11\":\"285\"},{\"1\":\"Regularity_Lecture_View\",\"2\":\"Final_Grade\",\"3\":\"0.39\",\"4\":\"0.95\",\"5\":\"0.29\",\"6\":\"0.48\",\"7\":\"7.1\",\"8\":\"283\",\"9\":\"0.00000000011395287939365397\",\"10\":\"Pearson correlation\",\"11\":\"285\"},{\"1\":\"Regularity_Forum_Consume\",\"2\":\"Final_Grade\",\"3\":\"0.38\",\"4\":\"0.95\",\"5\":\"0.28\",\"6\":\"0.48\",\"7\":\"7.0\",\"8\":\"283\",\"9\":\"0.00000000024412682323026614\",\"10\":\"Pearson correlation\",\"11\":\"285\"},{\"1\":\"Regularity_Forum_Contribute\",\"2\":\"Final_Grade\",\"3\":\"0.36\",\"4\":\"0.95\",\"5\":\"0.25\",\"6\":\"0.45\",\"7\":\"6.4\",\"8\":\"283\",\"9\":\"0.00000000524931925887681388\",\"10\":\"Pearson correlation\",\"11\":\"285\"},{\"1\":\"Freq_Lecture_View\",\"2\":\"Final_Grade\",\"3\":\"0.26\",\"4\":\"0.95\",\"5\":\"0.15\",\"6\":\"0.37\",\"7\":\"4.5\",\"8\":\"283\",\"9\":\"0.00004128706419879164097285\",\"10\":\"Pearson correlation\",\"11\":\"285\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n#### Data preparation\n\nThe next stage in our workflow is data preparation (@fig-workflow–B), where we clean and transform our data to fix any problems and inconsistencies and to get it ready for subsequent steps. We can see two potential issues with our data: data with large differences in variance (e.g., duration and regularity) as well as potential high collinearity in some variables. We may need to standardize the data (subtract the mean and divide by the standard deviation) to make all variables have a comparable scale. The code in the next chunk does exactly that: it simply scales all numeric variables. You may need to re-run the EDA code again to verify:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Standardize numeric columns in the student_data data frame\nstudent_data_standardized <- student_data |>\n  mutate(across(\n    where(is.numeric),  # Select all numeric columns\n    ~scale(.) |> # Standardize each column (M=0, SD=1) \n      as.vector() # Convert to vector\n  ))\n\n# Use skimr package to get a summary of the standardized data\nskim(student_data_standardized)  \n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |                          |\n|:------------------------|:-------------------------|\n|Name                     |student_data_standardized |\n|Number of rows           |285                       |\n|Number of columns        |12                        |\n|_______________________  |                          |\n|Column type frequency:   |                          |\n|numeric                  |12                        |\n|________________________ |                          |\n|Group variables          |None                      |\n\n\n**Variable type: numeric**\n\n|skim_variable               | n_missing| complete_rate| mean| sd|   p0|   p25|   p50|  p75| p100|hist  |\n|:---------------------------|---------:|-------------:|----:|--:|----:|-----:|-----:|----:|----:|:-----|\n|Freq_Course_View            |         0|             1|    0|  1| -2.9| -0.62| -0.03| 0.68|  2.2|▁▃▇▆▂ |\n|Freq_Forum_Consume          |         0|             1|    0|  1| -2.8| -0.67|  0.04| 0.69|  2.3|▁▅▇▇▂ |\n|Freq_Forum_Contribute       |         0|             1|    0|  1| -2.9| -0.61| -0.06| 0.63|  3.0|▁▅▇▃▁ |\n|Freq_Lecture_View           |         0|             1|    0|  1| -3.0| -0.70|  0.00| 0.80|  2.5|▁▃▇▆▁ |\n|Regularity_Course_View      |         0|             1|    0|  1| -2.5| -0.62|  0.09| 0.73|  2.8|▂▅▇▅▁ |\n|Regularity_Lecture_View     |         0|             1|    0|  1| -2.8| -0.66|  0.09| 0.63|  2.2|▁▅▇▇▃ |\n|Regularity_Forum_Consume    |         0|             1|    0|  1| -2.6| -0.60|  0.05| 0.62|  3.3|▁▅▇▂▁ |\n|Regularity_Forum_Contribute |         0|             1|    0|  1| -2.8| -0.64| -0.08| 0.66|  2.6|▁▃▇▅▂ |\n|Session_Count               |         0|             1|    0|  1| -2.6| -0.73|  0.03| 0.75|  2.2|▂▅▇▇▂ |\n|Total_Duration              |         0|             1|    0|  1| -2.4| -0.61|  0.02| 0.64|  2.7|▂▆▇▅▁ |\n|Active_Days                 |         0|             1|    0|  1| -2.7| -0.50| -0.02| 0.71|  3.6|▂▆▇▂▁ |\n|Final_Grade                 |         0|             1|    0|  1| -2.7| -0.70|  0.00| 0.75|  2.5|▁▆▇▇▁ |\n:::\n:::\n\n \nWe may also need to investigate the multicollinearity issue further. While multicollinearity is not a commonly discussed problem in machine learning, it is particularly important in explainable AI. If present, multicollinearity can lead to unstable estimates of model coefficients and inflated standard errors. One way to detect multicollinearity is by calculating the variance inflation factor (VIF). VIF measures the amount of inflation in the variance of a coefficient due to its correlation with other predictors. A high VIF value indicates that a variable is highly correlated with one or more other variables, suggesting multicollinearity. While there is no consensus about the VIF cutoff, in practice, a VIF value greater than 5 or 10 is often used as a cutoff to indicate multicollinearity. VIF is commonly computed in regression models, so we fit a regression model in the following code and then estimate the VIF from it. The code fits a linear regression model to predict the outcome variable (`Final_Grade`) using student LMS indicators as predictors. After fitting the model, it pipes the result into the `check_collinearity()` function from the `performance` package. The results of the VIF show that we have only four variables with moderate VIF values, so we can proceed with the analysis with no exclusion of any variable, given that we do not have a considerable collinearity problem.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit a linear regression model and check for multicollinearity\nlm(Final_Grade ~ Freq_Course_View + Freq_Lecture_View + Freq_Forum_Consume +\n                 Freq_Forum_Contribute + Regularity_Course_View + \n                 Regularity_Lecture_View + Regularity_Forum_Consume +\n                 Regularity_Forum_Contribute + Session_Count + \n                 Total_Duration + Active_Days,\n   data = student_data_standardized) |>  # Use standardized data for the model\ncheck_collinearity()    # Check for multicollinearity among predictors\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Term\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"VIF\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"VIF_CI_low\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"VIF_CI_high\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SE_factor\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Tolerance\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Tolerance_CI_low\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Tolerance_CI_high\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Freq_Course_View\",\"2\":\"4.6\",\"3\":\"3.8\",\"4\":\"5.6\",\"5\":\"2.1\",\"6\":\"0.22\",\"7\":\"0.18\",\"8\":\"0.26\"},{\"1\":\"Freq_Lecture_View\",\"2\":\"2.0\",\"3\":\"1.7\",\"4\":\"2.3\",\"5\":\"1.4\",\"6\":\"0.51\",\"7\":\"0.43\",\"8\":\"0.59\"},{\"1\":\"Freq_Forum_Consume\",\"2\":\"6.6\",\"3\":\"5.4\",\"4\":\"8.1\",\"5\":\"2.6\",\"6\":\"0.15\",\"7\":\"0.12\",\"8\":\"0.19\"},{\"1\":\"Freq_Forum_Contribute\",\"2\":\"3.7\",\"3\":\"3.1\",\"4\":\"4.6\",\"5\":\"1.9\",\"6\":\"0.27\",\"7\":\"0.22\",\"8\":\"0.32\"},{\"1\":\"Regularity_Course_View\",\"2\":\"5.2\",\"3\":\"4.3\",\"4\":\"6.3\",\"5\":\"2.3\",\"6\":\"0.19\",\"7\":\"0.16\",\"8\":\"0.23\"},{\"1\":\"Regularity_Lecture_View\",\"2\":\"3.1\",\"3\":\"2.6\",\"4\":\"3.8\",\"5\":\"1.8\",\"6\":\"0.32\",\"7\":\"0.27\",\"8\":\"0.39\"},{\"1\":\"Regularity_Forum_Consume\",\"2\":\"2.1\",\"3\":\"1.8\",\"4\":\"2.5\",\"5\":\"1.4\",\"6\":\"0.49\",\"7\":\"0.41\",\"8\":\"0.57\"},{\"1\":\"Regularity_Forum_Contribute\",\"2\":\"1.4\",\"3\":\"1.3\",\"4\":\"1.7\",\"5\":\"1.2\",\"6\":\"0.70\",\"7\":\"0.59\",\"8\":\"0.79\"},{\"1\":\"Session_Count\",\"2\":\"7.3\",\"3\":\"6.0\",\"4\":\"9.0\",\"5\":\"2.7\",\"6\":\"0.14\",\"7\":\"0.11\",\"8\":\"0.17\"},{\"1\":\"Total_Duration\",\"2\":\"4.7\",\"3\":\"3.9\",\"4\":\"5.8\",\"5\":\"2.2\",\"6\":\"0.21\",\"7\":\"0.17\",\"8\":\"0.26\"},{\"1\":\"Active_Days\",\"2\":\"5.8\",\"3\":\"4.8\",\"4\":\"7.1\",\"5\":\"2.4\",\"6\":\"0.17\",\"7\":\"0.14\",\"8\":\"0.21\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n## Tutorial 1: A Classic Approach to Predictive Modeling\n\nHaving explored and prepared the data, we now proceed to the next step of predicting students' performance using machine learning. We will predict the final grades using the variables that represent the students’ engagement. The steps include loading the necessary R packages, splitting the data, fitting the model, and evaluating the model's performance. First, we load the required R packages: the `randomForest` package, which is used to build the random forest model, the `rsample` package, which will be used to split the data into training and testing sets, and the `yardstick` package to facilitate model evaluation by calculating performance metrics.\n\nSecond, we split the dataset into two parts: a **training** set, which is used to train the machine learning model (perform the prediction), and a **testing** set (a holdout set for evaluation). The main rationale for data splitting is to use it to assess the performance of the estimated machine learning model on new, unseen data (the testing dataset). When keeping a testing dataset aside, we can evaluate how well the trained model generalizes to new data instances and estimate its accuracy. After all, we are creating the model with the hope that the same results will be obtainable in the future with new data. Furthermore, if we perform the prediction on all of the data, the model may ---and most probably will--- overfit. Overfitting occurs when a model learns the training data too well, including noise or irrelevant features, resulting in poor performance on new data. By having a separate testing set held out, we are increasing the likelihood that the model is learning the relevant patterns within the data not the noise. In practice, if a good model performs well on both the training and testing datasets, it is a good indication that the model is not overfitting and is likely to perform well in other situations with new data. Lastly, having a separate testing data set is rather valuable when our goal is to compare multiple machine learning algorithms to determine which model performs better on new data.\n\nThe code below uses the function `initial_split` function from the `rsample` package to perform an 80/20 split, where 80% of the data is used to train the model (perform the prediction), and the remaining 20% is kept aside as a testing set. While there is no consensus on the split ratio with many others using 70/30 and closer values, 80/20 is a reasonable starting point as it provides sufficient data for training while reserving a reasonable amount for evaluation.\n\nThird, we build the random forest model using the `randomForest` function from the `randomForest` package. The random forest algorithm is an ensemble learning method that creates multiple decision trees and combines their predictions to improve accuracy and control overfitting. This combination of multiple models helps reduce overfitting by averaging out the errors, resulting in an ---arguably--- more robust and generalizable model. More importantly, the random forest algorithm is an explainable model and provides feature importance scores, which can be used to identify the most relevant features for the problem at hand. In our case, it can help explain which variables help predict students’ performance. In this model, we predict the final grade (`Final_Grade`) based on the engagement variables such as the frequency and regularity of course views, lecture views, forum consumption and contributions, session count, total duration of activities, and the number of active days. We specify the number of trees (`ntree`) to be 1000, a parameter that controls the complexity and performance of the model.\n\nAfter fitting the model, we print the model summary using the functions `print` and `importance` (which shows the explanatory variables). The summary provides the model call, insights into the model's performance, including error rates and the proportion of variance explained. Variable importance shows how much each predictor has contributed to the prediction accuracy of students’ performance. In doing so, it allows us to understand which features are more associated with higher grades. More accurately, which features the random forest algorithm associated with higher grades. Learning the important variables allows us to gain insights of what can help in improving teaching and learning based on the results of our model.\n\nFourth, we use the trained model with new unseen data instances that we held out (the testing dataset) to perform predictions. In other words, the already trained model will estimate the final grades in the testing data. In this step, we use the `predict` function to apply the model to the test dataset to generate predictions of final grades. These predictions will be compared against the actual grades to evaluate how close or far the algorithm was able to predict the grades and by that we evaluate the model's performance. The closer the predictions are to the actual grade values, the better the performance of the algorithm. If the predicted grades differ considerably from the actual grades, it is an indication that the model is not good enough. It might be that we do not have enough data to make reliable predictions or, on the contrary, that our model is overfitted to the training data.\n\nIn the fifth step, we evaluate the model performance, given that there are multiple ways to assess performance, we will use different indicators, each of them provides different insights. Among the most common metrics when evaluating a regression machine learning model are the root mean squared error (RMSE), R-squared (R²), and mean absolute error (MAE). RMSE is a measure of the differences between predicted and actual values. It is calculated as the square root of the average of the squared differences between predicted and actual values. RMSE is always a positive value (because the errors are squared), where lower RMSE values indicate a better fit of the model to the data. Further, RMSE is sensitive to outliers because RMSE squares the errors, inflating the weight of larger errors.\n\nR-squared (R² or rsq) measures the proportion of variance in the dependent variable (the final grade in our case) that is explained by the independent variables. R² values range from 0 to 1, where values of 1 indicate that the model explains all the variability and R² of 0 indicates that the model explains none (bad model). However, although R² is popular, it can be misleading, pointing to erroneous conclusions. A high R² does not necessarily mean that the model is good; it only means that the model explains a large portion of the variance in the dependent variable. A major issue is that R² only measures the goodness of fit between the model and the data, but it does not account for the complexity or interpretability of the model. Adding more independent variables to a model, regardless of their relevance, will always increase or at least not decrease the R² value, leading to a more complex model that may be hard to interpret. As such, high R² values may give a false impression of a model's predictive power. Furthermore, a high R² does not guarantee that the model will perform well on new, unseen data. Other metrics such as RMSE or MAE, are more useful in this regard. MAE measures the absolute average magnitude of the errors in a set of predictions (i.e., without considering the direction of the difference). It is calculated as the average of the absolute differences between predicted and actual values. Unlike RMSE, MAE is not sensitive to outliers (since no squaring is performed).\n\nThe sixth step in our analysis is creating better and enhanced model performance evaluation. In that, we visualize the predicted versus actual grades to see how the model fared. We also plot the variable importance in a better way using the `ggplot2` package as well as the residuals. Here are the steps of the tutorial in detail:\n\n### Loading the necessary libraries\n\nThe code below starts by loading the necessary libraries. The `randomForest` [@randomForest] library is used to build and work with random forest models, while `rsample` [@rsample] aids in splitting the dataset into training and testing subsets. The `yardstick` [@yardstick] package is used for evaluating the performance of the model, and `ggplot2` is employed for creating visualizations, although the latter is not explicitly mentioned in the code given that it is part of `tidyverse` [@tidyverse] that we loaded before. Next, we set the seed function to a number `set.seed(256)` to ensure that our results would repeat in a similar way when re-running the code, e.g., data splitting would be consistent across different runs of the code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Load necessary libraries\nlibrary(randomForest)  # For building the Random Forest model\nlibrary(rsample)       # For data splitting\nlibrary(yardstick)     # For model evaluation\n\n# Set seed for reproducibility\nset.seed(256)\n```\n:::\n\n\n### Splitting the dataset\n\nThen, in the second step, we split the dataset (`student_data_standardized`) into training and testing sets (@fig-workflow–C). This is done using the `initial_split` function from the `rsample` package, which divides the data into an 80% training set and a 20% testing set. The `training` function extracts the training subset, while the `testing` function retrieves the testing subset and they are both assigned to two data frames `train_data` and `test_data` respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 2: Split the data into training and testing sets\n# Using initial_split from rsample package for an 80/20 split\ndata_split <- initial_split(student_data_standardized, prop = 0.8)\ntrain_data <- training(data_split)\ntest_data <- testing(data_split)\n```\n:::\n\n\n### Creating and fitting the model\n\nIn the third step, we build and fit the random forest model (@fig-workflow–D). The `randomForest` function is used to create this model, where `Final_Grade` is predicted based on the engagement predictor variables such as `Freq_Course_View`, `Freq_Lecture_View`, and `Session_Count`. The model is configured to use 1000 trees, which is specified by the `ntree` parameter. In Random Forest models, specifying a large number of trees enhances performance by reducing variance and improving stability through the aggregation of predictions from 1000 diverse trees. Each tree provides a unique perspective due to its training on random data subsets, and averaging their predictions minimizes overfitting. Yet, whereas more trees may improve model performance, balancing the number of trees is important, as performance gains diminish ---or disappear--- beyond a certain point. Also, setting a very high number of trees incurs computational costs, increases the risk of overfitting, and training time.\n\nAfter fitting the model, the code prints a summary of the random forest model using `print(rf_model)`. This summary provides insights into the model’s performance and structure. Additionally, `importance(rf_model)` is called to extract and display the importance of each variable in the model, helping to identify which predictors contribute most to the model’s predictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 3: Create and fit a Random Forest model\n# Building the Random Forest model with 1000 trees\nrf_model <- randomForest(Final_Grade ~ \n                           Freq_Course_View + Freq_Lecture_View + Freq_Forum_Consume +\n                           Freq_Forum_Contribute + Regularity_Course_View +\n                           Regularity_Lecture_View + Regularity_Forum_Consume +\n                           Regularity_Forum_Contribute + Session_Count +\n                           Total_Duration + Active_Days,\n                         data = train_data, ntree = 1000)\n\n# Print model summary and variable importance\nprint(rf_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\n randomForest(formula = Final_Grade ~ Freq_Course_View + Freq_Lecture_View +      Freq_Forum_Consume + Freq_Forum_Contribute + Regularity_Course_View +      Regularity_Lecture_View + Regularity_Forum_Consume + Regularity_Forum_Contribute +      Session_Count + Total_Duration + Active_Days, data = train_data,      ntree = 1000) \n               Type of random forest: regression\n                     Number of trees: 1000\nNo. of variables tried at each split: 3\n\n          Mean of squared residuals: 0.7\n                    % Var explained: 33\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Printing the model summary and variable importance\nimportance(rf_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            IncNodePurity\nFreq_Course_View                     17.0\nFreq_Lecture_View                    14.5\nFreq_Forum_Consume                   24.0\nFreq_Forum_Contribute                47.7\nRegularity_Course_View               18.7\nRegularity_Lecture_View              13.1\nRegularity_Forum_Consume             13.7\nRegularity_Forum_Contribute          23.7\nSession_Count                        21.6\nTotal_Duration                       22.0\nActive_Days                           8.9\n```\n:::\n:::\n\n\n### Evaluating the model's performance\n\nThe next stage in our workflow is to evaluate how well our model predicts performance (@fig-workflow–E). In Step 4, we make predictions on the test data using our trained Random Forest model by using the `predict` function, which generates a set of predicted values based on the features in `test_data` and the algorithm estimated before.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 4: Make predictions on the test data\n# Making predictions based on the test data using the trained model\npredictions <- predict(rf_model, newdata = test_data)\n```\n:::\n\n\nIn Step 5, we add these predictions to the test dataset, creating a new data frame called `evaluation_data` that includes both the actual and predicted grades. We then use the `metrics` function from the yardstick `package` to evaluate our model's performance by comparing the predicted grades with the actual ones, and we print the performance results to obtain performance metrics RMSE, MAE, and R-squared.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 5: Evaluate the model's performance\n# Adding predictions to the test data for evaluation\nevaluation_data <- bind_cols(test_data, Predicted_Grade = predictions)\n\n# Evaluating model performance\nperformance_metrics <- evaluation_data |>\n  metrics(truth = Final_Grade, estimate = Predicted_Grade)\n\n# Print the model performance metrics\nprint(performance_metrics)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 rmse    standard       0.631\n2 rsq     standard       0.525\n3 mae     standard       0.480\n```\n:::\n:::\n\n\n\nIn step 6, we produce two visualizations. The first visualization plots the actual versus predicted grades (@fig-scatter). Examining the distance between the residual and the fitted line gives an idea about how the model fared. The other plot is an improved plot of the important variables (@fig-varimp).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 6: Visualize predicted vs actual grades\nggplot(evaluation_data, aes(x = Final_Grade, y = Predicted_Grade)) +\n  geom_point(color = \"blue\", alpha = 0.5) +\n  geom_abline(intercept = 0, slope = 1, color = \"red\", linetype = \"dashed\") +\n  labs(x = \"Actual Grade\", y = \"Predicted Grade\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Scatter plot comparing predicted vs. actual grades](ch03-prediction_files/figure-html/fig-scatter-1.png){#fig-scatter width=5in}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enhanced variable importance plot\n# Extracting variable importance from the Random Forest model\nvariable_importance <- importance(rf_model)\nvar_imp_df <- data.frame(Variable = rownames(variable_importance), \n                         Importance = variable_importance[, 1])\n\n# Plotting variable importance\nggplot(var_imp_df, aes(x = reorder(Variable, Importance), y = Importance)) +\n  geom_bar(stat = \"identity\", fill = \"skyblue\") +\n  coord_flip() +\n  labs(x = \"Variable\", y = \"Importance\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Variable importance](ch03-prediction_files/figure-html/fig-varimp-1.png){#fig-varimp width=5in}\n:::\n:::\n\n\nThis code snippet demonstrates how to create and interpret residual plots for a random forest model. The process begins by calculating residuals, which are the differences between the actual `Final_Grade` and the `Predicted_Grade`. These residuals are then visualized in two separate plots using `ggplot2`. The first plot is a basic scatter plot of residuals against predicted grades, with each point representing a prediction (@fig-residuals). A horizontal red dashed line at zero helps identify any systematic over- or under-prediction. The second plot builds upon the first by adding a green smoothed trend line, which can reveal non-linear patterns in the residuals. Ideally, the residuals should be randomly scattered around the zero line with no discernible pattern, indicating that the model's errors are randomly distributed and there are no underlying biases or issues with the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate residuals\nevaluation_data$residuals <- \n  evaluation_data$Final_Grade - evaluation_data$Predicted_Grade\n\n\n# Add a smoothed line to show trends\nggplot(evaluation_data, aes(x = Predicted_Grade, y = residuals)) +\n  geom_point(color = \"blue\", alpha = 0.5) +\n  geom_hline(yintercept = 0, color = \"red\", linetype = \"dashed\") +\n  geom_smooth(method = \"loess\", color = \"green\", se = FALSE) +\n  labs(x = \"Predicted Grade\", y = \"Residuals\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Residual Plot for Random Forest Model with Trend Line.](ch03-prediction_files/figure-html/fig-residuals-1.png){#fig-residuals width=672}\n:::\n:::\n\n\n### Other algorithms\n\nIn the same way, we can execute other algorithms. Here we use a simpler algorithm (linear regression) given that it assumes that the relation between predictors and predicted grades is linear. Also, linear regression model does not need tuning (e.g., number of trees etc.). The way variable importance is calculated also differs: Random forest provides an inherent measure of feature importance, whereas for linear regression, we use the absolute values of the coefficients for importance. The evaluation metrics and visualization steps remain largely the same, although the results and interpretations would likely differ due to the fundamental differences in the models. Not also that the linear regression had lower R² but higher error measures RMSE and MAE. Please also note the differences and similarities in variable importance between the two algorithms.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Create and fit a Linear Regression model\nlm_model <- lm(Final_Grade ~ \n               Freq_Course_View + Freq_Lecture_View + Freq_Forum_Consume +\n               Freq_Forum_Contribute + Regularity_Course_View +\n               Regularity_Lecture_View + Regularity_Forum_Consume +\n               Regularity_Forum_Contribute + Session_Count +\n               Total_Duration + Active_Days,\n               data = student_data_standardized)\n\n# Print model summary\nprint(summary(lm_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Final_Grade ~ Freq_Course_View + Freq_Lecture_View + \n    Freq_Forum_Consume + Freq_Forum_Contribute + Regularity_Course_View + \n    Regularity_Lecture_View + Regularity_Forum_Consume + Regularity_Forum_Contribute + \n    Session_Count + Total_Duration + Active_Days, data = student_data_standardized)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.5669 -0.4984  0.0593  0.5060  1.9453 \n\nCoefficients:\n                                         Estimate            Std. Error t value    Pr(>|t|)    \n(Intercept)                  0.000000000000000747  0.046179132911298881    0.00       1.000    \nFreq_Course_View            -0.004596244897394796  0.098861369352034281   -0.05       0.963    \nFreq_Lecture_View           -0.019940653761920547  0.064689500916218223   -0.31       0.758    \nFreq_Forum_Consume          -0.144808972991361057  0.118530889483868279   -1.22       0.223    \nFreq_Forum_Contribute        0.523780479201737648  0.089481942137727782    5.85 0.000000014 ***\nRegularity_Course_View       0.073043787722892314  0.105214018434519427    0.69       0.488    \nRegularity_Lecture_View      0.031349755109250026  0.081356823049423099    0.39       0.700    \nRegularity_Forum_Consume     0.050298824195160151  0.066285623420039699    0.76       0.449    \nRegularity_Forum_Contribute  0.106781491699962761  0.055297248687460540    1.93       0.055 .  \nSession_Count                0.278012448531555212  0.125078957967640347    2.22       0.027 *  \nTotal_Duration              -0.077927196019897907  0.100821687015266614   -0.77       0.440    \nActive_Days                 -0.035067688196140728  0.111265764443180828   -0.32       0.753    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.78 on 273 degrees of freedom\nMultiple R-squared:  0.416,\tAdjusted R-squared:  0.392 \nF-statistic: 17.7 on 11 and 273 DF,  p-value: <0.0000000000000002\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 2: Make predictions on the data\npredictions_lm <- predict(lm_model, newdata = student_data_standardized)\n\n# Step 3: Evaluate the model's performance\n# Adding predictions to the data for evaluation\nevaluation_data_lm <- bind_cols(student_data_standardized, \n                                Predicted_Grade_lm = predictions_lm)\n\n# Evaluating model performance\nperformance_metrics_lm <- evaluation_data_lm |>\n  metrics(truth = Final_Grade, estimate = Predicted_Grade_lm)\n\n# Print the model performance metrics\nprint(performance_metrics_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 rmse    standard       0.763\n2 rsq     standard       0.416\n3 mae     standard       0.602\n```\n:::\n:::\n\n::: {#fig-linear-reg .cell layout=\"[1,1]\"}\n\n```{.r .cell-code}\n# Step 4: Visualize predicted vs actual grades\nggplot(evaluation_data_lm, aes(x = Final_Grade, y = Predicted_Grade_lm)) +\n  geom_point(color = \"blue\", alpha = 0.5) +\n  geom_abline(intercept = 0, slope = 1, color = \"red\", linetype = \"dashed\") +\n  labs(x = \"Actual Grade\", y = \"Predicted Grade\") +\n  theme_minimal()\n\n# Step 5: Variable importance plot\n# Extracting variable importance from the Linear Regression model\nvariable_importance_lm <- abs(coef(lm_model)[-1])  # Exclude intercept\nvar_imp_df_lm <- data.frame(Variable = names(variable_importance_lm), \n                            Importance = variable_importance_lm)\n\n# Plotting variable importance\nggplot(var_imp_df_lm, aes(x = reorder(Variable, Importance), y = Importance)) +\n  geom_bar(stat = \"identity\", fill = \"skyblue\") +\n  coord_flip() +\n  labs(x = \"Variable\", y = \"Absolute Coefficient Value\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Scatter plot comparing actual grades to predicted grades.](ch03-prediction_files/figure-html/fig-linear-reg-1.png){#fig-linear-reg-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Variable importance.](ch03-prediction_files/figure-html/fig-linear-reg-2.png){#fig-linear-reg-2 width=672}\n:::\n\nLinear regression plots\n:::\n\n\n## Tutorial 2: A Modern Approach to Predictive Modelling using `tidymodels`\n\nHaving used the traditional way, now we introduce a more modern approach of doing machine learning in R using `tidymodels`. The `tidymodels` framework provides a consistent interface for modeling in R by integrating several packages that work together seamlessly throughout the modeling process. The `tidymodels` package eliminates the need to learn and remember the various syntax and functions required by different modeling packages. Instead of having to switch between different paradigms and approaches for each package, you can use the same set of tools and functions. This uniformity speeds up model development and enhances code readability and maintainability.\n\nAdditionally, `tidymodels` offers integrated tools for tasks like pre-processing, resampling, and performance evaluation, further simplifying and accelerating the entire modeling workflow. For instance, the `parsnip` package in `tidymodels` allows us to define models in a consistent manner, regardless of the underlying algorithm (e.g., `randomForest`, `ranger`, `xgboost`). It provides functions like `rand_forest()` to specify the model, `set_engine()` to choose the computational backend, and `set_mode()` to define whether the model is used for regression or classification.\n\nThis organization is achieved through the use of workflows, which combines the entire modeling process in a single, manageable object, ensuring that each component is handled systematically. The tidy approach includes several steps: 1) splitting the data into training and testing sets (as done before), 2) defining a model specification (we will do a Random Forest model) using the standard approach of `parsnip` package, 3) creating a workflow combining the model specifications, 4) fitting the model to the training data, 5) making predictions on the test data, and 6) evaluating the model's performance and visualizing the results. This tutorial will guide you through these steps, using `parsnip` to create a random forest model, evaluate its performance, and visualize the results. Below, we describe each step in detail:\n\n1.  **Data Splitting**: This step is done in the same way we did before.\n\n2.  **Selecting the predictor and target variables**: The formula specifies the relationship between the target variable and the predictor variables. In regression tasks, this formula includes the dependent variable (e.g., `Final_Grade`) and the independent variables — in our case, engagement indicators— such as `Freq_Course_View` and `Total_Duration`. Defining the formula clearly outlines which variables are used to predict the outcome, ensuring that the model is correctly specified. We can also reuse the formula in other models without having to specify the arguments again.\n\n3.  **Model Specification with `parsnip`**: Using `parsnip`, we define our random forest model with specific parameters. The `rand_forest()` function allows us to set the models parameters. The most important parameters are number of trees and number of variables to try in each split. In our model, we set number of trees (`trees`) to 1000 and the number of variables to sample at each split (`mtry`) to 3. Setting the engine to `\"randomForest\"` and the mode to `\"regression\"`, we configure the model to perform regression tasks using the random forest algorithm.\n\n4.  **Creating the Workflow**: A workflow is an object that combines together the model specification and the formula. This organized approach helps manage different components of the modeling process efficiently. Using the `workflow()` function, we add the random forest model specification and formula to create a complete modeling pipeline.\n\n5.  **Fitting the Model**: The model is fitted to the training data using the `fit()` function.\n\n6.  **Making Predictions and Evaluating Performance**: After fitting the model, we use it to make predictions on the test data as we did before. Similarly, for evaluation, these predictions are compared to the actual values. We calculate performance metrics such as R-squared (`rsq`), MAE (`mae`), and RMSE (`rmse`) using the `metrics()` function from the `yardstick` package. We will visually assess the model’s performance using plots as we have done before.\n\n### Load the necessary libraries\n\nFirst, we load the necessary libraries. The `tidymodels` package [@tidymodels] is a meta-package (a collection of packages) that loads several other packages useful for modeling, including `parsnip`, `rsample`, `recipes`, and more. Note that we will not run the data splitting code since it was already split before.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load necessary libraries\nlibrary(tidymodels) #Loading tidymodels loads all the necessary packages for estimation.\n# Set seed for reproducibility\nset.seed(256)\n\n# Step 1: Split the data into training and testing sets, this step will not be\n# run as it is already done before. In case you are running this code only,\n# you may need to uncomment it.\n# \n# data_split_tidy <- initial_split(student_data_standardized, prop = 0.8)\n# train_data <- training(data_split_tidy)\n# test_data <- testing(data_split_tidy)\n```\n:::\n\n\n### Select the predictor and target variables\n\nIn `tidymodels`, the models are specified using a formula that defines the target variable, and the predictors following a specific syntax: `target_variable \\~ predictor_1 + predictor_2 + ... + predictor_n`, where `target_variable` is the variable we want to predict. In our case, it is `Final_Grade`. In turn, `predictor_1`, `predictor_2`, ..., `predictor_n` are the predictor variables that will be used to make the prediction. In our case, these are the engagement indicators. See below how the formula is defined for our model in the same way.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 2: Define the formula\n# We define the formula to specify the relationship between the target variable \n# 'Final_Grade' and the predictor variables\nformula_tidy <- Final_Grade ~ Freq_Course_View + Freq_Lecture_View + \n                        Freq_Forum_Consume + Freq_Forum_Contribute + \n                        Regularity_Course_View + Regularity_Lecture_View + \n                        Regularity_Forum_Consume + Regularity_Forum_Contribute +\n                        Session_Count + Total_Duration + Active_Days\n```\n:::\n\n\n### Define the Random Forest Model Specification\n\nIn this step, we specify the random forest model we plan to estimate by defining the type of model, the engine (the computational back-end), and the hyperparameters (the model configurations). This process enables the creation of straightforward and modular machine learning pipelines (we can change any of these components easily). The package `parsnip` encompassed within `tidymodels` ecosystem provides a unified interface for defining and fitting various statistical and machine learning models. To specify a random forest model in `parsnip`, we use the `rand_forest()` function. This function allows us to define the type of model and set hyperparameters without immediately fitting the model. This separation of concerns is beneficial for the reusability of the code. The `mode` argument is set to `\"regression\"` because we are predicting a continuous outcome (`Final_Grade`). The `trees = 1000` argument specifies the number of trees in the forest. The `mtry` argument represents the number of predictors in each split. Setting this to `tune()` indicates that we want to tune this hyperparameter, meaning we will search for the optimal value during the model training process. The `set_engine()` function specifies the computational backend to use for fitting the model. In this case, we use `\"ranger\"`, which is a fast implementation of random forests suitable for large datasets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 3: Define a random forest model specification with `ntree` and `mtry` parameters\n# We specify the random Forest model with 1000 trees and 3 variables randomly \n# sampled at each split\nrf_specification_tidy <- rand_forest(trees = 1000, mtry = tune()) |>\n  set_mode(\"regression\") |>\n  set_engine(\"ranger\")\n```\n:::\n\n\nIn the `tidymodels` framework, we integrate this formula into a workflow to streamline the modeling process. The `workflow()` function initializes a new workflow. The `add_model` function allows us to specify the model which is the random forest in our case. And `add_formula` function allows us to add the formula to the workflow, specifying the relationship between the target variable and predictor variables. The workflow helps ensure that all necessary components for training the model are combined in a single object. This makes it easier to apply or modify the model, and helps maintain a tidy, reproducible code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 4: Create the workflow. We create a workflow that combines the model \n# specification with the formula\nrf_workflow_tidy <- workflow() |>\n  add_model(rf_specification_tidy) |>\n  add_formula(formula_tidy)\n```\n:::\n\n\nThe next steps are similar to our previous approach with small changes like using the pipe '\\|\\>' to enhance model readability. First, using the workflow, we fit the random forest model (corresponding to @fig-workflow–D) using the previously defined workflow and training data (step 5). Using the fitted model, we make predictions on the test data and combines these predictions with the original test data to evaluate the model performance (step 6, corresponding to @fig-workflow–E). Next, we calculate performance metrics (R-squared, MAE, and RMSE) by comparing the predicted values to the actual values and then print the results. The last part of the code visualizes the predicted versus actual grades as before (@fig-predvsactualtidy).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 5: Fit the random forest model\n# We fit the random forest model to the training data using the workflow\nrf_fitting_tidy <- rf_workflow_tidy |>\n  fit(data = train_data)\n\n# Step 6: Make predictions on the test data and evaluate the model's performance\n# We make predictions on the test data, calculate performance metrics, and \n# visualize the results\npredictions_tidy <- predict(rf_fitting_tidy, new_data = test_data) |>\n  bind_cols(test_data)\n\n# Calculate performance metrics: R-squared, MAE, and RMSE\nperformance_metrics_tidy <- predictions_tidy |>\n  metrics(truth = Final_Grade, estimate = .pred)\n\n# Print the model performance metrics\nprint(performance_metrics_tidy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 rmse    standard       0.705\n2 rsq     standard       0.431\n3 mae     standard       0.531\n```\n:::\n\n```{.r .cell-code}\n# Scatter plot comparing actual grades to predicted grades\nggplot(predictions_tidy, aes(x = Final_Grade, y = .pred)) +\n  geom_point(color = \"blue\", alpha = 0.5) +\n  geom_abline(intercept = 0, slope = 1, color = \"red\", linetype = \"dashed\") +\n  labs(x = \"Actual Grade\", y = \"Predicted Grade\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Predicted vs. Actual Grades](ch03-prediction_files/figure-html/fig-predvsactualtidy-1.png){#fig-predvsactualtidy width=672}\n:::\n:::\n\n\n### Multiple algorithms\n\nThe uniform framework of `tidymodels` enables easier estimation and comparison of multiple models and in fact several configurations of the same algorithm if needed. The next code uses `tidymodels` to build and evaluate five machine learning algorithms namely: linear regression, support vector machine (SVM), random forest, K-nearest neighbors (KNN), and a neural network. Using `tidymodels` saves a lot of time in working with diverse packages and interfaces for each algorithm. Given that we already used similar code before, and we already loaded and split the data, we briefly describe the code for the estimation.\n\n#### Model specification\n\nFirst, we define model specifications using the `parsnip` package. The `linear_reg` function is used to specify a linear regression model with the `lm` engine. For SVM , we use the `svm_rbf` function and set the engine to `kernlab`, specifying that it will be used for regression. The random forest model is specified using `rand_forest`, setting the number of trees to 1000 and allowing the number of variables randomly sampled at each split (`mtry`) to be tuned. The `nearest_neighbor` function specifies a KNN model with 5 neighbors, and the engine is set to `kknn`. Finally, for the neural network, the `mlp` function specifies a model with 10 hidden units and 100 epochs, using the `nnet` engine, set for regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear Regression specification\nlr_specification <- linear_reg() |> set_engine(\"lm\")\n\n# SVM specification\nsvm_specification <- svm_rbf() |> set_engine(\"kernlab\") |>\n  set_mode(\"regression\")\n\n# Random Forest specification with ntree and mtry parameters\nrf_specification <- rand_forest(trees = 1000, mtry = tune()) |>\n  set_engine(\"randomForest\") |>\n  set_mode(\"regression\")\n\n# KNN specification\nknn_specification <- nearest_neighbor(neighbors = 5) |>\n  set_engine(\"kknn\") |>\n  set_mode(\"regression\")\n\n# Neural Network specification\nnn_specification <- mlp(hidden_units = 10, epochs = 100) |>\n  set_engine(\"nnet\") |>\n  set_mode(\"regression\")\n```\n:::\n\n\n#### Create workflows\n\nNext, we create workflows for each model specification using the `workflow` function. This involves adding the model specification and the formula to the workflow. The formula defines the relationship between the predictors and the target variable `Final_Grade`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear Regression workflow\nlr_workflow <- workflow() |>\n  add_model(lr_specification) |>\n  add_formula(formula_tidy)\n\n# SVM workflow\nsvm_workflow <- workflow() |>\n  add_model(svm_specification) |>\n  add_formula(formula_tidy)\n\n# Random Forest workflow\nrf_workflow <- workflow() |>\n  add_model(rf_specification) |>\n  add_formula(formula_tidy)\n\n# KNN workflow\nknn_workflow <- workflow() |>\n  add_model(knn_specification) |>\n  add_formula(formula_tidy)\n\n# Neural Network workflow\nnn_workflow <- workflow() |>\n  add_model(nn_specification) |>\n  add_formula(formula_tidy)\n```\n:::\n\n\n#### Fit the models\n\nWe then fit each model to the training data using the `fit` function. This step trains the models using the specified workflows and the training dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the Linear Regression model\nlr_fitting <- lr_workflow |>\n  fit(data = train_data)\n\n# Fit the SVM model\nsvm_fitting <- svm_workflow |>\n  fit(data = train_data)\n\n# Fit the Random Forest model\nrf_fitting <- rf_workflow |>\n  fit(data = train_data)\n\n# Fit the KNN model\nknn_fitting <- knn_workflow |>\n  fit(data = train_data)\n\n# Fit the Neural Network model\nnn_fitting <- nn_workflow |>\n  fit(data = train_data)\n```\n:::\n\n\n#### Calculate Fit Indices and Residuals\n\nLastly, we create `calculate_metrics` function to assess the performance of each fitted model. It takes the model fit object and test data as inputs, makes predictions on the test data, and binds these predictions to the test data (@tbl-performancemetrics). Performance metrics such as R-squared, mean absolute error (MAE), and root mean squared error (RMSE) are calculated using the `metrics` function from the `yardstick` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to calculate metrics and residuals\ncalculate_metrics <- function(model_fitting, test_data, truth_col = \"Final_Grade\") {\n  # Make predictions\n  predictions <- predict(model_fitting, new_data = test_data) |>\n    bind_cols(test_data)\n  \n  # Calculate residuals\n  residuals <- predictions |>\n    mutate(residuals = !!sym(truth_col) - .pred)\n  \n  # Calculate performance metrics\n  performance_metrics <- residuals |>\n    metrics(truth = !!sym(truth_col), estimate = .pred)\n  \n  list(performance_metrics = performance_metrics, residuals = residuals)\n}\n\n# Calculate metrics and residuals for each model\nlr_results <- calculate_metrics(lr_fitting, test_data)\nsvm_results <- calculate_metrics(svm_fitting, test_data)\nrf_results <- calculate_metrics(rf_fitting, test_data)\nknn_results <- calculate_metrics(knn_fitting, test_data)\nnn_results <- calculate_metrics(nn_fitting, test_data)\n\n# Combine predictions and residuals\nlr_residuals <- lr_results$residuals |> mutate(model = \"Linear Regression\")\nsvm_residuals <- svm_results$residuals |> mutate(model = \"SVM\")\nrf_residuals <- rf_results$residuals |> mutate(model = \"Random Forest\")\nknn_residuals <- knn_results$residuals |> mutate(model = \"KNN\")\nnn_residuals <- nn_results$residuals |> mutate(model = \"Neural Network\")\n\ncombined_residuals <- bind_rows(lr_residuals, svm_residuals, \n                                rf_residuals, knn_residuals, nn_residuals)\n\n# Extract and combine performance metrics\nperformance_metrics <- bind_rows(\n  lr_results$performance_metrics |> mutate(model = \"Linear Regression\"),\n  svm_results$performance_metrics |> mutate(model = \"SVM\"),\n  rf_results$performance_metrics |> mutate(model = \"Random Forest\"),\n  knn_results$performance_metrics |> mutate(model = \"KNN\"),\n  nn_results$performance_metrics |> mutate(model = \"Neural Network\")\n) |> arrange(.metric)\n\n# Print performance metrics\nprint(performance_metrics)\n```\n:::\n\n::: {#tbl-performancemetrics .cell tbl-cap='Performance metrics by model'}\n::: {.cell-output-display}\n|.metric |.estimator | .estimate|model             |\n|:-------|:----------|---------:|:-----------------|\n|mae     |standard   |      0.48|Linear Regression |\n|mae     |standard   |      0.51|SVM               |\n|mae     |standard   |      0.53|Random Forest     |\n|mae     |standard   |      0.60|KNN               |\n|mae     |standard   |      1.11|Neural Network    |\n|rmse    |standard   |      0.62|Linear Regression |\n|rmse    |standard   |      0.67|SVM               |\n|rmse    |standard   |      0.70|Random Forest     |\n|rmse    |standard   |      0.75|KNN               |\n|rmse    |standard   |      1.35|Neural Network    |\n|rsq     |standard   |      0.52|Linear Regression |\n|rsq     |standard   |      0.45|SVM               |\n|rsq     |standard   |      0.43|Random Forest     |\n|rsq     |standard   |      0.35|KNN               |\n|rsq     |standard   |      0.05|Neural Network    |\n:::\n:::\n\n\nWen can plot the performance metrics to compare them across the models (@fig-comparing-models).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot performance metrics\nperformance_metrics |>\n  ggplot(aes(x = model, y = .estimate, fill = model)) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  facet_wrap(~ .metric, scales = \"free\") +\n  labs(x = \"Model\",\n       y = \"Metric Value\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![Comparing performance metrics across models](ch03-prediction_files/figure-html/fig-comparing-models-1.png){#fig-comparing-models width=672}\n:::\n:::\n\n\nWe can also create a scatter plot comparing actual grades to predicted grades, providing a visual assessment of the model's performance (@fig-scatter-actual).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_residuals |>\n  ggplot(aes(x = Final_Grade, y = .pred, color = model)) +\n  geom_point() +\n  # Add a linear model fit line\n  geom_smooth(method = \"lm\", se = FALSE, linetype = \"dashed\", color = \"black\") +  \n  facet_wrap(~ model) +\n  labs(x = \"Actual Final Grade\",\n       y = \"Predicted Final Grade\") +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Plot actual vs. predicted with a line matching the slope of actual vs. predicted](ch03-prediction_files/figure-html/fig-scatter-actual-1.png){#fig-scatter-actual width=604.8}\n:::\n:::\n\n\nYou can evaluate the results of each model by comparing it against the other models and choose the best performing model with lowest error rates.\n\n## Discussion and conclusions\n\nThis chapter has provided a comprehensive exploration of predictive modeling in the context of learning analytics, where we focus on the practical application of machine learning techniques to forecast student performance. We have systematically mapped the main steps of the predictive modeling process, from data preparation and exploratory analysis to the building, evaluation, and interpretation of various models. The chapter explored different traditions from traditional machine learning, to the modern tidy approach and comparison across several models (linear regression, random forests, support vector machines, K-nearest neighbors, and neural networks). Furthermore, we investigated the use of various evaluation metrics – RMSE, MAE, and R-squared – to estimate model accuracy, which can help us understand the trade-offs associated with each algorithm. We also shown how to visualize model predictions against actual outcomes and examine residual plots to assess the model fit and highlight areas that needed further consideration.\n\nSeveral important points need to be emphasized here. First, the important of data and variable selection according to a predefined learning theory that can offer a platform for variable inclusion and model results interpretation for more discussion of this issue, please refer to the vast literature on theory and predictive analytics. Second, the significance of careful data preprocessing cannot be overstated; even the most advanced algorithms cannot compensate for poor-quality data. Third, the absence of a single \"best\" algorithm became apparent, highlighting how algorithm choice is always dataset-specific, goal-oriented, and depends on the desired interpretability of the model. Fourth, we recognized that predictive models are tools to enhance decision-making, but do not replace human judgment and expertise, particularly in educational contexts, which require ethical considerations.\n\nFinally, this chapter has demonstrated that the practical application of data science techniques can help to inform and improve educational practices. However, it also highlighted the importance of understanding the limitations of predictive models and machine learning in general [@mustafa2024]. Worth also noting that while explanation and transparency of the machine learning models are useful, they still can do deliver results that are more data driven that plausible or aligned with theory [@Saqr2024-ie]. Other Issues like overfitting, data quality, and ethical considerations need to be carefully addressed to ensure responsible and meaningful use of predictive analytics in education. Finally, the chapter emphasized that predictive modeling is not just about achieving high accuracy, but also about gaining actionable insights into factors influencing student success and informing interventions and improving learning outcomes. We also need to emphasize that these results are aggregates of the whole dataset and therefore, it can be misleading and lacks full representation of each and everyone [@saqr2024; @LABOOK2_Chapter_22].\n\n\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "ch03-prediction_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}